### ISSUE TITLE
Won't Save To PES file

### ISSUE THREAD

**Issue by sunny5860** [inkstitch/inkstitch#2069] opened 2023-02-13 20:54 UTC
Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\extensions\base.py", line 200, in elements_to_stitch_groups
  File "lib\elements\element.py", line 329, in embroider
  File "lib\elements\element.py", line 387, in validate
  File "lib\elements\fill_stitch.py", line 321, in validation_errors
  File "lib\elements\fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'

![Hawks Logo_Inkscape](https://user-images.githubusercontent.com/125313016/218572364-56728691-58b7-451d-914a-9c3d3132a69c.svg)

**Comment by kaalleen** [comment] 2023-02-20 16:47
Try to spot small elements in your document. This is mostly what is causing the issue. Especially go through the blue elements one by one and render the stitch plan preview. Delete the small elements when you find them.

**Comment by kaalleen** [comment] 2023-02-25 12:56
Duplicate of #1742

**Closed by kaalleen** 2023-02-25 12:56 UTC
