### ISSUE TITLE
commands:  AttributeError: 'MultiPolygon' object has no attribute 'exterior'

### ISSUE THREAD

**Issue by britbrad96** [inkstitch/inkstitch#1578] opened 2022-02-12 20:50 UTC
Traceback (most recent call last):
  File "inkstitch.py", line 67, in <module>
  File "inkex\base.py", line 147, in run
  File "lib\extensions\object_commands.py", line 38, in effect
  File "lib\commands.py", line 384, in add_commands
  File "lib\commands.py", line 337, in get_command_pos
AttributeError: 'MultiPolygon' object has no attribute 'exterior'

**Comment by kaalleen** [comment] 2022-02-13 14:17
Thanks for your error report! Can you add your current Ink/Stitch version?

**Comment by kaalleen** [comment] 2023-03-04 14:36
Duplicate of #1768

**Closed by kaalleen** 2023-03-04 14:36 UTC
Labels: bug, need more information
