### ISSUE TITLE
error

### ISSUE THREAD

**Issue by carlasf** [inkstitch/inkstitch#2143] opened 2023-03-15 03:03 UTC
path883: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.2.0 (osx)

Traceback (most recent call last):
  File "lib/elements/fill_stitch.py", line 556, in to_stitch_groups
  File "lib/elements/fill_stitch.py", line 590, in do_underlay
  File "lib/debug.py", line 133, in decorated
  File "lib/stitches/auto_fill.py", line 62, in auto_fill
  File "lib/stitches/fill.py", line 163, in intersect_region_with_grating
ZeroDivisionError: float division by zero

**Comment by kaalleen** [comment] 2023-03-15 14:51
Remove small elements from the document and watch out, that your fill area isn't too thin in stitch direction.

**Comment by kaalleen** [comment] 2023-03-15 15:06
Duplicate of #1829

**Comment by carlasf** [comment] 2023-03-15 16:00
thank you! I will try that

**Comment by kaalleen** [comment] 2023-03-21 18:31
I'm closing the issue, because we have seen it so often. If you still have problems or need more help to bring your design to work, you can still post more questions in here or open a new issue.

**Closed by kaalleen** 2023-03-21 18:31 UTC
