### ISSUE TITLE
path10: error: Fill: Shape is not valid.  This can happen if the border crosses over itself.

### ISSUE THREAD

**Issue by JonZwei** [inkstitch/inkstitch#670] opened 2020-04-24 01:15 UTC
I get this error when trying to run params or simulate.  I am just going through the video tutorial and creating a circle and converting the object to a path.  Here is a screenshot of the error.

![Untitled](https://user-images.githubusercontent.com/64236520/80164609-aea72680-8596-11ea-9769-3d6d2482bbbd.png)

**Comment by kaalleen** [comment] 2020-04-25 13:05
Thanks for posting an issue here. This one we are seeing a lot.

It has been discussed a while ago in an other issue, maybe you want to have a look at it: #610
You can often solve it by just moving it a little around or grab just one node and move it around just a little. You could also try to find out which node it causing the error by running the troubleshoot extension.

@lexelby is working on a solution for this issue, which is possibly caused by very small loops in the path that we are not able to see in the given resolution.

**Comment by danielkschneider** [comment] 2020-05-06 20:28
IMHO, the problem is that InkScape does not create a circle but an arc (a figure like a pacman) and since it looks like a circle it has two points positioned on top of each other (to the right hand side). So you have to get rid of one of the points, but you cannot select one because they are identical. Smoothing will indeed destroy one most of the times, but may change the shape of your circle.

Another solution in this type of situation is to replace bezier curves by a set of straight lines.: Extensions -> Modify Path -> Flatten Beziers, input a low value, e.g. 0.2.

Another solution is to edit the SVG code and remove the identical double point, but for that you need to understand a bit of SVG path syntax.

**Comment by Augusa** [comment] 2020-05-06 20:38
I am not sure to understand the whole text but I use this tool when I have 2 nodes and I want only one. Sorry I don't know the name in english
![node](https://user-images.githubusercontent.com/54963659/81225858-399e0d00-8fea-11ea-92e5-8ec95cb3782c.jpg)

**Comment by kaalleen** [comment] 2020-05-07 06:45
Ok, that's interesting. I figured by now, that it helps to grab the point on the right, pull it to the side and press escape (while still grabbing it). The point will flip back to it's original position. But a none visible path operation was triggered (from arc to bezier curve), which will solve the invalid path issue in all of my test cases.

**Comment by kaalleen** [comment] 2020-05-16 10:44
This is a duplicate of #610

**Closed by kaalleen** 2020-05-16 10:44 UTC
