### ISSUE TITLE
Inkstitch issue

### ISSUE THREAD

**Issue by 128mega** [inkstitch/inkstitch#2271] opened 2023-05-05 15:57 UTC
Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 556, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 590, in do_underlay
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 62, in auto_fill
  File "lib\stitches\fill.py", line 163, in intersect_region_with_grating
ZeroDivisionError: float division by zero

**Comment by kaalleen** [comment] 2023-05-06 16:53
Try to remove small elements from yourr document. Also try to avoid thin fill stitch areas. I haven't seen your design, but think if they are possibly replaceable with a satin column or running stitch.

**Comment by kaalleen** [comment] 2023-05-15 21:05
Duplicate of #1829

**Closed** 2023-05-15 21:22 UTC
