### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'title'

### ISSUE THREAD

**Issue by tamapaan** [inkstitch/inkstitch#1022] opened 2021-02-06 11:10 UTC
Hello,
I have been trying to get inkstitch to work for some hours, but in vain. The following are the steps taken and basics:

Following the installation guide provided by Inkstitch, I set up Ubuntu with the following specs for Inkscape and Inkstitch. Running Inkscape:
Extensions for Inkstitch are shown in Inkscape. Executing any command results in an error to quick to be read, before it disappears again. Running ./inkstitch in a command prompt results in the following:

**/.config/inkscape/extensions/inkstitch/bin$ ./inkstitch
Traceback (most recent call last):
  File "/home/runner/work/inkstitch/inkstitch/inkstitch.py", line 33, in <module>
AttributeError: 'NoneType' object has no attribute 'title'
[7520] Failed to execute script inkstitch**

I have reinstalled several times. Tried different language versions. Added Python2.7 since Ubuntu comes with Python3.8.5 without any change to the error. I'd really love to use Inkstitch and am quite sad, that it doesn't seem to work. Can you help? I haven't been able to locate any log files to provide more information re. the error. I assume, Inkstitch just doesn't find necessary files or version of external..........but to be honest....I haven't a clue :o(
Many thanks for any form of support
Antje

OS Ubuntu 20.10
uname -a
Linux antje-tohuwabohu 5.8.0-41-generic #46-Ubuntu SMP Mon Jan 18 16:48:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Package
inkstitch-v1.29.1-linux-de_DE.zip

python2.7
Python 2.7.18 (default, Aug 24 2020, 19:12:23) 
[GCC 10.2.0] on linux2

Python 3.8.6 (default, Sep 25 2020, 09:36:53) 
[GCC 10.2.0] on linux

Installed Inkscape
 ../snap/inkscape
Version 1.0.1 (0767f8302a, 2020-10-17)

Inkstitch Extension Path
../.config/inkscape/extensions/
ls -l
-rwxr-xr-x  1 antje antje    30992 Aug 19 01:16 _codecs_iso2022.so
-rwxr-xr-x  1 antje antje   264464 Aug 19 01:16 _codecs_jp.so
-rwxr-xr-x  1 antje antje   137488 Aug 19 01:16 _codecs_kr.so
-rwxr-xr-x  1 antje antje   108816 Aug 19 01:16 _codecs_tw.so
drwxr-xr-x  2 antje antje        8 Feb  5 23:03 cryptography-1.2.3-py2.7.egg-info
-rwxr-xr-x  1 antje antje    10104 Aug 19 01:16 cryptography.hazmat.bindings._constant_time.so
-rwxr-xr-x  1 antje antje   882304 Aug 19 01:16 cryptography.hazmat.bindings._openssl.so
-rwxr-xr-x  1 antje antje    34352 Aug 19 01:16 _csv.so
-rwxr-xr-x  1 antje antje   140184 Aug 19 01:16 _ctypes.so
-rwxr-xr-x  1 antje antje    86512 Aug 19 01:16 _curses.so
-rwxr-xr-x  1 antje antje    15368 Aug 19 01:16 dbm.so
-rwxr-xr-x  1 antje antje     4504 Aug 19 01:16 _dummy.so
-rwxr-xr-x  1 antje antje    58432 Aug 19 01:16 _elementtree.so
-rwxr-xr-x  1 antje antje     7712 Aug 19 01:16 future_builtins.so
-rwxr-xr-x  1 antje antje   332168 Aug 19 01:16 gi._gi.so
-rwxr-xr-x  1 antje antje    33480 Aug 19 01:16 _hashlib.so
drwxr-xr-x  2 antje antje        4 Aug 19 01:14 icons
drwxr-xr-x  3 antje antje        3 Aug 19 01:17 include
-rwxr-xr-x  1 antje antje  5981256 Aug 19 01:16 inkstitch
.
.
.

**Comment by kaalleen** [comment] 2021-02-06 16:48
Can this info here help to solve your issue?
https://inkstitch.org/docs/install-linux/#inkstitch-dialogues-disappear-after-a-few-seconds
Sometimes it's also caused by missing libraries. But maybe the above solution already helps?

**Comment by tamapaan** [comment] 2021-02-06 19:40
Thanks for your repay, but that didn't help.
I started inkscape from a terminal to get an output, whcih I don't believe does help much. I'll post it, since nit may help developers:

inkscape

(inkscape:30048): Gtk-WARNING **: 20:37:46.730: Theme parsing error: gtk.css:1566:23: 'font-feature-settings' is not a valid property name

(inkscape:30048): Gtk-WARNING **: 20:37:46.740: Theme parsing error: gtk.css:3616:25: 'font-feature-settings' is not a valid property name

(inkscape:30048): Gtk-WARNING **: 20:37:46.742: Theme parsing error: gtk.css:4078:23: 'font-feature-settings' is not a valid property name

(org.inkscape.Inkscape:30048): Gtk-WARNING **: 20:37:46.916: Theme parsing error: gtk.css:1566:23: 'font-feature-settings' is not a valid property name

(org.inkscape.Inkscape:30048): Gtk-WARNING **: 20:37:46.925: Theme parsing error: gtk.css:3616:25: 'font-feature-settings' is not a valid property name

(org.inkscape.Inkscape:30048): Gtk-WARNING **: 20:37:46.927: Theme parsing error: gtk.css:4078:23: 'font-feature-settings' is not a valid property name

(org.inkscape.Inkscape:30048): Gtk-WARNING **: 20:37:47.059: Theme parsing error: gtk.css:1566:23: 'font-feature-settings' is not a valid property name

(org.inkscape.Inkscape:30048): Gtk-WARNING **: 20:37:47.067: Theme parsing error: gtk.css:3616:25: 'font-feature-settings' is not a valid property name

(org.inkscape.Inkscape:30048): Gtk-WARNING **: 20:37:47.069: Theme parsing error: gtk.css:4078:23: 'font-feature-settings' is not a valid property name

** (org.inkscape.Inkscape:30048): WARNING **: 20:37:47.725: Parameter 'feed_rate' in extension 'org.inkstitch.output.txt.de_DE' is visible but does not have a 'gui-text'.
Fontconfig warning: "/etc/fonts/fonts.conf", line 5: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/fonts.conf", line 6: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/fonts.conf", line 6: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/fonts.conf", line 6: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/fonts.conf", line 7: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/fonts.conf", line 7: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/fonts.conf", line 9: unknown element "description"

**Comment by kaalleen** [comment] 2021-02-06 21:35
Would you mind to test if this inkstitch version is running fine on your system?

https://github.com/inkstitch/inkstitch/releases/download/dev-build-kaalleen-inkscape1.0/inkstitch-kaalleen-inkscape1.0-linux-de_DE.zip

When you unwrap it into the extensions folder it is ok with this version to leave it inside a subfolder. I find it very convenient, so I thought I let you know ;)

**Comment by tamapaan** [comment] 2021-02-07 07:17
Thanks very much, I think, we are getting there. It may have to do with Python on my machine. The error message has shifted to

Traceback (most recent call last):
  File "inkstitch.py", line 36, in <module>
AttributeError: 'NoneType' object has no attribute 'title'
[14594] Failed to execute script inkstitch

Is there any logging I might be able to use?
Thanks again for you kind support :o)

**Comment by kaalleen** [comment] 2021-02-07 08:06
Oh, I should have noticed earlier. You have the snap package of Inkscape. Using snap to install Inkscape caauses trouble for Ink/Stitch, because it comes with some restrictions. With ubuntu you could install it through your package manager or use any other way described here https://inkscape.org/de/release/1.0.2/gnulinux/

As for logging without manual install, I wouldn't know anything better than the system protocoll.

**Comment by tamapaan** [comment] 2021-02-07 11:38
Hi Kaalleen,
That was the solution. The first install was automatically done in Snap. Now I start it from /opt/inkscape via symbolic link and Ink/Stitch seems to work fine. I have no experience with Inkscape and Ink/Stitch just yet, so it'll take a while for me to have tested it. 
The start of Inkscape does fail to load libcanberra-gtk-module though it is installed. As I understand, its not really necessary for Inkscape to work. 
Many thanks for your help and kind wishes from a very cold Hamburg 
Antje :o)

**Comment by kaalleen** [comment] 2021-02-07 12:11
Thanks for your reply. Glad to hear it is working now. Ink/Stitch doesn't really use your system libraries but comes with everything it needs. Sometimes it something is missing ... :D
But if it happens on the Inkscape startup it could also be an Inkscape dependecy missing rather than Ink/Stitch, not sure.

Oh yes, the winter has come back to us. Everything is white in the Ruhrpott-area as well ;)

**Comment by kaalleen** [comment] 2021-02-09 10:18
I've updated the installation page on our website to mention the installation issue with snap.
Since we found a solution I am going to close this issue. Please reopen if this is still needed.

**Closed by kaalleen** 2021-02-09 10:18 UTC
