### ISSUE TITLE
Auto_fill: ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by aliengravy** [inkstitch/inkstitch#920] opened 2020-12-14 21:37 UTC
path1179: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 212, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 149, in build_fill_stitch_graph
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

**Comment by kaalleen** [comment] 2020-12-15 18:11
Sorry, this error is annoying to many users lately. It is caused by very small fill objects in your document. You can remove them by running either of these functions:
* Extensions > Troubleshoot > Cleanup Document
* Extensions > Fill Tools > Break apart fill objects

Hope this helps.

**Comment by kaalleen** [comment] 2021-01-17 11:49
Duplicate of #734

**Closed by kaalleen** 2021-01-17 11:49 UTC
