### ISSUE TITLE
error

### ISSUE THREAD

**Issue by crazzy313** [inkstitch/inkstitch#2012] opened 2023-01-13 22:36 UTC
Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\troubleshoot.py", line 29, in effect
  File "lib\elements\fill_stitch.py", line 321, in validation_errors
  File "lib\elements\fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'

![Rm0109- 2](https://user-images.githubusercontent.com/122649781/212431728-fb64c724-1ee9-453f-9a81-8e00d93d4abc.svg)

**Comment by kaalleen** [comment] 2023-01-19 16:30
The error is caused by tiny elements in your document with a fill.
Open the layers and objects dialog and walk throught he list while deleting point-like elements.
Also you could consider to turn the flower outlines to a stroke (running - or bean stitch) or to a satin (depending on the size they will finally be stitched in).

**Comment by kaalleen** [comment] 2023-02-25 13:28
Duplicate of #1742

**Closed by kaalleen** 2023-02-25 13:28 UTC
