### ISSUE TITLE
Save as/Params inkstitch.py

### ISSUE THREAD

**Issue by mmacloud17** [inkstitch/inkstitch#488] opened 2019-07-05 00:56 UTC
This is what I get when I try to set params or save as on Mac Mojave 10.14.5:

Unexpected error launching Ink/Stitch.
If you're having trouble, please file an issue here, including the text below:
  https://github.com/inkstitch/inkstitch/issues

Tried to launch: inkstitch/bin/inkstitch
Arguments: ['inkstitch/bin/inkstitch', '--extension=params', '/var/folders/07/7ktrkcdd2j3gvkf7jnf16hyc0000gn/T/ink_ext_XXXXXX.svgD8553Z']
Debugging information:

Traceback (most recent call last):
  File "inkstitch.py", line 35, in <module>
    extension = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by lexelby** [comment] 2019-07-10 00:46
Hi here, and thanks for trying out Ink/Stitch!  We've had this problem a lot with Mac users, and I'm still not sure what's going on.  Since I don't have a Mac, it's hard for me to get to the bottom of it.

Do any of the other Ink/Stitch extensions work, like Embroider?

**Comment by kaalleen** [comment] 2020-04-10 07:45
Duplicate of #613 
Closing the issue now. Please report further issues on this matter there.

**Closed by kaalleen** 2020-04-10 07:45 UTC
