### ISSUE TITLE
bug in inkstitch

### ISSUE THREAD

**Issue by Irritantr** [inkstitch/inkstitch#2059] opened 2023-02-09 18:29 UTC
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\extensions\base.py", line 200, in elements_to_stitch_groups
  File "lib\elements\element.py", line 329, in embroider
  File "lib\elements\element.py", line 387, in validate
  File "lib\elements\fill_stitch.py", line 321, in validation_errors
  File "lib\elements\fill_stitch.py", line 274, in shape
AttributeError: 'Point' object has no attribute 'geoms'
![VXS embroidery](https://user-images.githubusercontent.com/56132908/217904728-21222c09-72f0-4578-bae6-45305eafee59.svg)

**Comment by kaalleen** [comment] 2023-02-12 12:14
Remove these two circles from your document. They have a 0 radius.
The next Ink/Stitch version will handle cases like this better.

**Comment by Irritantr** [comment] 2023-02-12 12:57
I will try it and get back to you, thanks.

Ian

**Comment by kaalleen** [comment] 2023-02-25 13:07
Duplicate of #1816

**Closed by kaalleen** 2023-02-25 13:07 UTC
