### ISSUE TITLE
Umlaut in SVG causes python exception

### ISSUE THREAD

**Issue by TheTinderstick** [inkstitch/inkstitch#478] opened 2019-06-16 21:00 UTC
Hi,
Awesome how this project evolved and improved in the last few years! Good job!
With the latest version (1.25.0) we ran into a problem with German umlaut "ü" in the SVG file name when trying to run "embroider". The actual line of code differs depending on the export format but it is always "AttributeError: unicode object has no attribute write".
I'm pretty sure the problem was already present in 1.21.0.
Bye,
S & R

**Comment by lexelby** [comment] 2019-06-19 15:53
Thank you, and thanks for using Ink/Stitch! :smile: 

I love it when people catch unicode errors, because they tend to be easy to fix.  Could you please paste the entire traceback from one of these errors?  It would help me narrow down the line of code that's causing the problem.

**Comment by lexelby** [comment] 2019-06-22 22:47
I fixed one bug with umlauts in file names, but not the one you're talking about.  I haven't been able to reproduce that AttributeError.  I think it might have to do with a bug that I fixed in a version more recent than 1.21.0.  Would you mind trying the latest version?

**Comment by TheTinderstick** [comment] 2019-06-23 17:54
Hi,
Sorry for the slow answer. Had to reproduce the error at my girlfriends place. The Problem is present in 1.25.0. Here is a screenshot of the error message.
![fehlermeldung](https://user-images.githubusercontent.com/41512486/59980015-2fe90200-95f0-11e9-81d1-3a4a771c78f5.png)

This is from trying the PES export. I'm pretty sure I did see other tracebacks when trying other formats, though.

**Comment by lexelby** [comment] 2019-06-27 00:39
Perfect, thank you!!

**Comment by kaalleen** [comment] 2019-06-29 08:52
This should be fixed by #485

**Comment by Moini** [comment] 2020-02-23 12:02
Hi, just to let you know the current status:

Just had a user in the German subforum at https://inkscape.org/forums/Deutsch/ink-stitch/ report this issue with 1.26.2-win32-de on Inkscape 0.92.4 and Win10 (ä in the Windows user name).

**Comment by lexelby** [comment] 2020-03-05 03:14
@Moini awesome!  Could you please ask them to post the full exception traceback?  Hopefully we can squash the last umlaut-related bug(s).

Or if you don't speak German, maybe @kaalleen can help?

**Comment by Moini** [comment] 2020-03-05 11:33
My German is quite good, actually ... I've been living in Germany all my life ;-)

The user isn't very technically inclined, though, and I don't know myself how to guide her to start Inkscape from the Windows command line, and to copy the messages (mostly because I'm not using Windows myself). If you know that, I could try to translate back and forth.

There's no message when she tries via GUI, she writes "Wenn ich auf das Fenster "Parameter" klicke, öffnet es sich ganz kurz und schließt automatisch bevor ich dort irgend etwas eingeben kann." ("When I click on the window 'parameters', it opens for a split second and closes again before I can enter any data there.").

**Comment by lexelby** [comment] 2020-03-05 13:06
Whoops!  Sorry about that, ignore me ;)

Let's not put you and her through the torture of trying to run from the command line.  I think you've already given me enough information to go on.  One more thing might help: do you know her Windows user name?  Having that would be useful, or if there are privacy concerns, perhaps you could invent a user name for me to test with?

**Comment by Moini** [comment] 2020-03-05 13:27
It's 'Bärbel'. 

Thank you :D

**Comment by lexelby** [comment] 2020-03-06 02:55
Got it, thanks!

**Comment by lexelby** [comment] 2020-03-06 03:44
Good news, bad news, and good news!

Good news: I was able to reproduce the exact problem that "Bärchen" and others have experienced.  I created a new Windows user named Bärchen, set up Inkscape and Ink/Stitch, and run it.  I see the window for a split second just like they described.

Bad news: It's an Inkscape bug.  Running the extension by hand from the command line, using Inkscape's `pythonw.exe` works great.  Testing with a very simple .inx and .py file in Inkscape results in the same behavior.  Inkscape is not able to run a Python extension in the user's extension directory if the user's name has an umlaut.

Good news: I had a pretty great breakthrough that allows us to work around this problem.  I was able to get Ink/Stitch working properly on my Bärchen user account.  I discovered that Inkscape is able to run an extension that's a .exe without an interpreter at all.  This is really what we want anyway!

I'll try to put together a new release soon with this fix, which will hopefully finally put this bug to rest.  For now, our friend with the umlaut in their user name can work around the problem by installing Ink/Stitch in the **system extensions directory**.  In Inkscape, go to Edit -> Preferences.  Under System, look for the "Inkscape extensions" path.  Mine is `C:\Program Files\Inkscape\share\extensions`.  If you install Ink/Stitch there, I think it should work.

**Comment by lexelby** [comment] 2020-03-06 03:51
@kaalleen It turns out we don't need stub.py at all!  Instead of this in an INX file:

```xml
<command reldir="extensions" interpreter="python">inkstitch.py</command>
```

we can simply do this:

```xml
<command reldir="extensions">inkstitch/bin/inkstitch.exe</command>
```

I can't believe I never tried just not having the `interpreter` attribute!  This works great on Windows.  We'll need to make it different for mac/linux (remove the `.exe`) but that should be doable.

I hope to get this done soon because this is going to resolve a huge barrier to entry that's been around for ages.

**Comment by Moini** [comment] 2020-03-06 12:48
@lexelby Can you try it with the unmodified extension and your beary user in a current 1.0.x version, too? 
The original Inkscape issue could be fixed there, I seem to remember something similar. Just to make sure the fixes won't interfere somehow.

The latest successful build is available from 
https://ci.appveyor.com/project/inkscape/inkscape/builds/31275009/job/6qlw7hymkay25yx6/artifacts

**Comment by Moini** [comment] 2020-03-06 12:50
Better link, because it's stable and updated automatically: 
https://alpha.inkscape.org/snapshots/latest_1.0.x_x64.html

**Comment by lexelby** [comment] 2020-03-15 02:29
@Moini Could you have them try out this version? https://github.com/inkstitch/inkstitch/releases/tag/dev-build-lexelby-no-stub

Not only does that fix the umlaut issue, it also gets rid of that annoying black box that always pops up on windows.

**Comment by Moini** [comment] 2020-03-15 12:53
Thank you, @lexelby ! I've pinged her about it, will let you know as soon as I get a reply.

**Closed** 2020-03-18 18:50 UTC
Labels: bug
