### ISSUE TITLE
(UnicodeDecodeError) Traceback (most recent call last):

### ISSUE THREAD

**Issue by Omarzon** [inkstitch/inkstitch#1030] opened 2021-02-09 19:13 UTC
Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "D:\a\inkstitch\inkstitch\inkscape\share\extensions\inkex.py", line 283, in affect
  File "D:\a\inkstitch\inkstitch\lib\extensions\embroider.py", line 86, in effect
  File "D:\a\inkstitch\inkstitch\lib\extensions\embroider.py", line 49, in get_output_path
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\encodings\utf_8.py", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf1 in position 35: unexpected end of data

**Comment by kaalleen** [comment] 2021-02-09 19:32
Sorry for that... thanks for reporting. This error is caused by a special char in your filename or path. We also would suggest not to use the "embroider" function anymore. You can export your files through `File > Save a copy...`. This method is known to be working a little bit better. When doing so, try to avoid special chars.

**Comment by morgatina** [comment] 2021-02-11 19:00
Hi. I am using Inkstitch and getting the same error message as Omarzon when saving as an embroidery file. I assume chars means characters but there is nothing exceptional in the titles. So far I have been unable to save anything as an embroidery file although Inkscape is saving svgs as normal.
    Thanks for ink stitch. I can see how good it is but can't go further without a save.  Morgatina

**Comment by kaalleen** [comment] 2021-02-23 19:49
Is there a special character in the path you are trying to save your file in? Maybe in the user name?
An other possible issue could be an error message which cannot be displayed because of the encoding error. Is the simulator or any other preview working?

**Comment by kaalleen** [comment] 2021-05-15 12:11
This should be fixed in the newest version of Ink/Stitch. Please reopen, if this error shows up again.

**Closed by kaalleen** 2021-05-15 12:11 UTC
