### ISSUE TITLE
Pull compensation for autofill?

### ISSUE THREAD

**Issue by Augusa** [inkstitch/inkstitch#2865] opened 2024-04-28 22:02 UTC
I see a lot of great new possibilities for the next version but nothing about pull compensation for autofll. It is so usefull. It is really helpfull to get embroidery without gap between objects.

**Comment by kaalleen** [comment] 2024-04-29 05:33
Thanks for the reminder :) And yes, it is not forgotten. @lexelby was actually working on it.

I'll close this request as a duplicate of #1776

**Closed by kaalleen** 2024-04-29 05:33 UTC
