### ISSUE TITLE
User Experience for Invalid Geometry

### ISSUE THREAD

**Issue by wwderw** [inkstitch/inkstitch#175] opened 2018-05-30 13:48 UTC
Have it to where Ink/Stitch will catch "invalid" geometry errors and suggest tips on how to fix the error.

**Comment by lexelby** [comment] 2018-09-22 19:45
#323 effectively a duplicate of this one, but I'm going to close his one since #323 has more detail on what a solution will look like.

**Closed by lexelby** 2018-09-22 19:45 UTC
Labels: feature request

**Comment by aloxyz** [comment] 2020-05-13 11:35
Has this been implemented yet?

**Comment by kaalleen** [comment] 2020-05-14 10:25
Yes, it's the troubleshoot extension.
