### ISSUE TITLE
Applocker

### ISSUE THREAD

**Issue by EnterSanderman** [inkstitch/inkstitch#2632] opened 2023-12-11 11:53 UTC
Hi, my workplace has applocker on the python files etc. Is there a way to get around this? We have tried whitelisting, but there are too many different files. The problem is that we get inkstitch to install, but when we open simulator preview we get error messages.

**Comment by kaalleen** [comment] 2023-12-13 15:53
Can you show us the error messages?

**Comment by EnterSanderman** [comment] 2023-12-14 08:50
We can't whitelist whole folders because end user have read/right permission to their appdata. If the python and dll files are signed, we can whitelist them. Some were, but some were not.

**Comment by EnterSanderman** [comment] 2023-12-14 10:55
> Can you whitelist the entire ink/stitch folder in applocker? Can you show us the error messages?

Some of the files looks like it was generated randomly

**Comment by kaalleen** [comment] 2023-12-25 10:44
Hm, that's unfortunate. I'm just happy that we are aiming to rework the simulator to use the same gui as params and lettering for some future versions. That may solve your issue.

**Comment by EnterSanderman** [comment] 2024-01-03 08:54
So c++ and not python for simulator? That would work I think. But signing all the files would also work. Thanks for the reply, forwarding to the end user.

**Comment by kaalleen** [comment] 2024-12-15 21:03
I'm going to close the issue as the simulator uses wxpython now. If the problem is still a problem, please open a new issue.

**Closed by kaalleen** 2024-12-15 21:03 UTC
