### ISSUE TITLE
Issue Installing on Mac 

### ISSUE THREAD

**Issue by embroider011** [inkstitch/inkstitch#1858] opened 2022-10-11 21:09 UTC
When I am trying to install inkstitch onto my Macbook it gets so far and then says - 
"The installation failed. The installer encountered an error that caused the installation to fail. Contact the software manufacturers for assistance" Are you able to help me with this? 

Thank You

**Comment by tyrosinase** [comment] 2022-10-11 21:39
Did you install (and open, at least once) Inkscape first? Ink/Stitch is a plugin, not a standalone program.

**Comment by embroider011** [comment] 2022-10-11 21:44
Yes, I installed and run Inkscape before trying to install ink/stitch.

**Comment by tyrosinase** [comment] 2022-10-11 22:05
Hmm, is it an M1? I know there's some requirements involving Rosetta, especially (only?) on the M1, but that's the extent of my knowledge (I run Linux, not Mac) and one of the devs will have to step in with more detail.

**Comment by embroider011** [comment] 2022-10-11 22:11
It is a MacBook Pro - M1 Chip - macOS Monterey. I can't find anywhere that says there's different requirements for things.

**Comment by tyrosinase** [comment] 2022-10-11 22:14
Oh, are you installing the current version? Because that one, yeah, is supposed to "just work" but there were more steps on older versions. Although #1855 seems to be a similar issue so maybe there's something going on with the current version as well. @kaalleen will probably know more than me, though.

**Comment by embroider011** [comment] 2022-10-11 22:17
Yes, I have tried the new version, old version and the link and not one of them will install :( thank you for trying to help.

**Comment by george-steel** [comment] 2022-10-11 22:20
Are you using an X11 or a Quartz build of Inkscape?

**Comment by embroider011** [comment] 2022-10-11 22:26
I'm not sure, how would I find that out?

**Comment by kaalleen** [comment] 2022-10-15 14:30
There is no X11 or Quartz builds anymore. There is just an Intel or M1 builds.

Did you install Inkscape into a specific folder (not into the apps folder? We had a similar issue which was caused by that here: https://github.com/inkstitch/inkstitch/issues/1855#issuecomment-1279113539

A missing Rosetta installation can always be a problem on M1 processors, but it usually only shows only after the installation. If Ink/Stich doesn't run properly when installed on an M1 computer, run this command in your terminal: `softwareupdate --install-rosetta --agree-to-license`

**Comment by embroider011** [comment] 2022-10-15 22:37
Hi, unfortunately when I just tried this it did not work. I tried it with Inkscape in the apps folder and a different one and ink/stitch still wouldn't install :/

**Comment by kaalleen** [comment] 2022-10-16 08:15
Can you precisely describe the steps you've done to install Inkscape and Ink/Stitch?

**Comment by embroider011** [comment] 2022-10-16 09:44
Firstly I go onto the Inkscape site and click on - “MacOS”. I then click “dmg file for arm64 architecture” (M1). Once that has downloaded I then run it for a few minutes. Then I go onto the ink/stitch website and click on “MacOS”, once clicking that I click on “Download ink/stitch v2.2.0 for MacOS - Big Sur/Monterey”. Once that has downloaded I try to install it and it doesn’t work :)

**Comment by kaalleen** [comment] 2022-10-16 15:12
>  Once that has downloaded I then run it for a few minutes.

What does it mean. You dragged and dropped Inkscape into your `/Applications` folder and run Inkscape afterwards. Then closed Inkscape before running the Ink/Stitch installer?

**Comment by embroider011** [comment] 2022-10-16 15:39
Yes

**Comment by kaalleen** [comment] 2022-10-16 16:38
Ok, good. Then we are talking about the Ink/Stitch installer.
When it comes to choose the installation hard drive. Do you have more than one to select from?

Like this:
![harddrive_selection](https://user-images.githubusercontent.com/36401965/196047244-5debf582-98ed-46cd-b850-58409e1cc176.png)

Or is there only one harddrive?

**Comment by embroider011** [comment] 2022-10-16 16:45
No, I only have Macintosh HD

**Comment by kaalleen** [comment] 2022-10-16 18:31
Ok good.
Can you post the path to your extensions folder?
You find it in Edit > Preferences > System > User extensions

**Comment by embroider011** [comment] 2022-10-16 19:03
I am not quite sure what you mean. How am I doing it sorry?

**Comment by kaalleen** [comment] 2022-10-16 19:10
Open Inkscape. In the menu click on `Edit` then on `Preferences`. In the preferences window click on the left sidebar on `System`. Then you will see a list of file paths. One of them is called `User extensions`. Copy this path and paste it here.

**Comment by embroider011** [comment] 2022-10-16 19:29
/Users/jadehazlewood/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extenstions

**Comment by tyrosinase** [comment] 2022-10-16 19:55
If it's actually `extenstions` that's probably the problem.

**Comment by kaalleen** [comment] 2022-10-16 20:05
Hm, that's more likely wrongly copied over to here. If so, I'm not sure why you cannot install Ink/Stitch.

Maybe you want to do it manually: https://inkstitch.org/docs/install-macos/#installation-fails

* Download the zip file for monterey
* Extract the zip file to the user extensions folder

**Comment by embroider011** [comment] 2022-10-16 20:44
trying to do it that way and this is what it says 
"Inkstitch cannot be opened because the developer cannot be verified. 
MacOS cannot verify that this app is free from malware.
Safari downloaded this file today at 21:42."

**Comment by kaalleen** [comment] 2022-10-17 16:30
https://inkstitch.org/docs/install-macos/#xxxx-cannot-be-opened-because-the-developer-cannot-be-verified

> `Ctrl+Click` on the downloaded file and click on `Open`.

**Closed** 2023-07-02 15:48 UTC
