### ISSUE TITLE
Stitch Ends in New Color Starting Point

### ISSUE THREAD

**Issue by st11x** [inkstitch/inkstitch#2025] opened 2023-01-22 02:54 UTC
Hi, 

No matter if it was a running stitch or fill, at the color change, the last color will end at the start of the new color.
We can only set end points for fills, but I don't think that's the problem.

Any ideas?

thanks
  Matt

**Comment by st11x** [comment] 2023-01-23 22:02
I made 2 different colored parallel lines in this demo. This arrow points to the part where it stops and sews that 1 more stitch before the color change. 

![image](https://user-images.githubusercontent.com/7398499/214159641-a571d4c8-2242-4455-a409-c33f859a597f.png)

I also made a short video of how the machine sew that. 

https://www.dropbox.com/s/0vj4w87vy59hkln/sew.mp4?dl=0

Is that normal?

**Comment by st11x** [comment] 2023-01-24 21:03
I found a workaround for this. I export the file to either a .xxx or .jef and it works as expected. I didn’t even need to set any start or stop points. The 2 Brother formats that my machine accepts (PES, PEC) didn’t work. 

I did not try any other formats so maybe it is a limitation between the Brother formats and my machine.

**Comment by kaalleen** [comment] 2023-07-02 14:46
Thanks for your feedback and sorry for the delay of my answer.
Would you mind to try if this is still happening with Ink/Stitch v3.0.1?

**Comment by st11x** [comment] 2023-07-02 18:06
Thanks @kaalleen I don't have the opportunity to verify that now, but when I do, I'll be sure to update this.

**Comment by kaalleen** [comment] 2024-01-01 11:20
Closing. Please open a new issue if the problem is still occurring.

**Closed by kaalleen** 2024-01-01 11:20 UTC
