### ISSUE TITLE
Hi. I do not code at all, but here is a thing that happened. idk if this helps.

### ISSUE THREAD

**Issue by mickeymaeart** [inkstitch/inkstitch#2058] opened 2023-02-07 20:29 UTC
path8258: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 556, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 590, in do_underlay
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 75, in auto_fill
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 630, in path_to_stitches
  File "lib\stitches\auto_fill.py", line 591, in travel
  File "networkx\algorithms\shortest_paths\generic.py", line 167, in shortest_path
  File "networkx\algorithms\shortest_paths\weighted.py", line 2377, in bidirectional_dijkstra
networkx.exception.NetworkXNoPath: No path between (215.43307086614175, 77.69638627775167) and (216.36226172287587, 88.86149481513768).

**Comment by lexelby** [comment] 2023-02-08 01:02
Actually yes, that helps a ton!  I'm not sure if we've seen this particular error before.

Would you be willing to share your SVG with us?  Or even just an SVG with only path8258 in it?

It's okay if you're not willing to share it, but even a screenshot of the shape would help.  I have a theory about what happened here and getting a look at the shape might confirm it.

**Comment by mickeymaeart** [comment] 2023-02-08 16:38
![CartoonDog](https://user-images.githubusercontent.com/124733591/217593837-f92614bf-12ea-44c9-85b7-130b45aa423c.svg)

**Comment by mickeymaeart** [comment] 2023-02-08 16:40
That path was I think the black outline around the pink in the right ear.

**Comment by kaalleen** [comment] 2023-03-04 13:38
Thank you for the file. I cannot reproduce the error with your file.
But we received an other file which can reproduce the error: #2056

**Comment by kaalleen** [comment] 2023-03-04 13:55
I'll close this issue in favor of #2056

**Closed by kaalleen** 2023-03-04 13:55 UTC
