### ISSUE TITLE
Unexpected error launching Ink/Stitch.

### ISSUE THREAD

**Issue by CaliKane** [inkstitch/inkstitch#637] opened 2020-03-15 02:05 UTC
Unexpected error launching Ink/Stitch.
If you're having trouble, please file an issue here, including the text below:
  https://github.com/inkstitch/inkstitch/issues

Tried to launch: inkstitch\bin\inkstitch
Arguments: ['inkstitch\\bin\\inkstitch', '--collapse_len_mm=3', '--hide_layers=true', '--output_format=pec', '--extension=embroider', 'C:\\Users\\CALIKA~1\\AppData\\Local\\Temp\\ink_ext_XXXXXX.svgDF70G0']
Debugging information:

Traceback (most recent call last):
  File "inkstitch.py", line 34, in <module>
    extension = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Program Files\Inkscape\lib\python2.7/subprocess.py", line 325, in __init__
    errread, errwrite)
  File "C:\Program Files\Inkscape\lib\python2.7/subprocess.py", line 575, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by kaalleen** [comment] 2020-03-15 11:22
Hello @CaliKane and welcome to the project!
Have a look at issue #617 
It is probably the same cause?!

**Comment by kaalleen** [comment] 2020-04-10 07:45
Duplicate of #613 
Closing the issue now. Please report further issues on this matter there.

**Closed by kaalleen** 2020-04-10 07:45 UTC
