### ISSUE TITLE
Inkstitch -- cannot run params

### ISSUE THREAD

**Issue by cindyyd** [inkstitch/inkstitch#1249] opened 2021-06-13 14:40 UTC
Did anyone encounter such error when you run the params in extension?
Params gives me such error:

Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\params.py", line 626, in effect
  File "lib\extensions\params.py", line 340, in __init__
  File "lib\extensions\params.py", line 606, in create_tabs
  File "lib\extensions\params.py", line 69, in __init__
wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(0, 0), "C") == 0" failed at ..\..\src\common\intl.cpp(1694) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!

**Comment by tyrosinase** [comment] 2021-06-13 15:04
That's a known problem: look at #1232 for a fix.

**Comment by kaalleen** [comment] 2021-07-19 07:07
Duplicate of #1232

**Closed by kaalleen** 2021-07-19 07:07 UTC
