### ISSUE TITLE
tuples??

### ISSUE THREAD

**Issue by Lenise22** [inkstitch/inkstitch#2065] opened 2023-02-11 07:28 UTC
Traceback (most recent call last):
  File "shapely/speedups/_speedups.pyx", line 90, in shapely.speedups._speedups.geos_linestring_from_py
AttributeError: 'list' object has no attribute '__array_interface__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 231, in run
  File "lib/extensions/cleanup.py", line 45, in effect
  File "lib/elements/stroke.py", line 330, in shape
  File "lib/elements/stroke.py", line 334, in as_multi_line_string
  File "lib/elements/stroke.py", line 334, in <listcomp>
  File "shapely/geometry/linestring.py", line 46, in __init__
  File "shapely/speedups/_speedups.pyx", line 156, in shapely.speedups._speedups.geos_linestring_from_py
ValueError: LineStrings must have at least 2 coordinate tuples
![killua nike ink](https://user-images.githubusercontent.com/124225238/218246294-1270ffef-8852-4528-bb62-ed4b5de6f60b.svg)

**Comment by bianchifan** [comment] 2023-02-11 10:04
I guess you're running another OS
No traceback here, but the result does not satisfy, the satin seems broken.

![Bildschirmfoto vom 2023-02-11 10-56-58](https://user-images.githubusercontent.com/17491743/218252171-57132652-702a-4208-8a83-9246eb82c2e2.jpg)

**Comment by Lenise22** [comment] 2023-02-11 16:45
im pretty new to this how do i fix that is it a drawing issue?

**Comment by kaalleen** [comment] 2023-02-25 13:03
Are you running Ink/Stitch v2.2.0 ? It's possible, that you run an older Ink/Stitch verison (not sure though), just wondering.

If you wonder about the edges in your zig zag... Convert the outlines to a satin column: https://inkstitch.org/docs/stitches/satin-column/

**Comment by kaalleen** [comment] 2023-03-04 14:24
I'm closing this issue as a duplicate of #1742 and it has been fixed for the next release already.
If you have more questions about it, you can still post them here or open a new issue.

**Closed by kaalleen** 2023-03-04 14:24 UTC
