### ISSUE TITLE
clamp_path_to_polygon: TopologyException

### ISSUE THREAD

**Issue by kchiron** [inkstitch/inkstitch#3181] opened 2024-09-01 14:14 UTC
Hi,

I was working on an embroidery pattern with Inkscape and Ink/Stitch extension. I changed the embroidery angle for each part of my SVG and got this error on exporting my SVG into embroidery file .pes :

Windows 10 version: 10.0.22631

Ink/Stitch Version: v3.1.0 (windows) 2024-07-27 09:04

Traceback (most recent call last):
  File "lib\elements\element.py", line 641, in handle_unexpected_exceptions
  File "lib\elements\element.py", line 605, in embroider
  File "lib\elements\fill_stitch.py", line 942, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 1020, in do_underlay
  File "lib\debug\debug.py", line 166, in decorated
  File "lib\stitches\auto_fill.py", line 116, in auto_fill
  File "lib\debug\debug.py", line 166, in decorated
  File "lib\stitches\auto_fill.py", line 929, in path_to_stitches
  File "lib\stitches\auto_fill.py", line 885, in travel
  File "lib\utils\clamp_path.py", line 118, in clamp_path_to_polygon
  File "shapely\geometry\base.py", line 545, in buffer
  File "shapely\decorators.py", line 77, in wrapped
  File "shapely\constructive.py", line 180, in buffer
shapely.errors.GEOSException: TopologyException: assigned depths do not match at 308.61887304701003 -70051.418601954123

I had only one element selected when error occured, .pes export worked better after unselecting and selecting all paths.
Here the file :
![broderie](https://github.com/user-attachments/assets/d846854c-45d3-4f6e-9dc7-a89ea98f1723)

Hope it helps otherwise you can close this issue :).

**Comment by kaalleen** [comment] 2024-10-04 15:00
Do you remember which element you had selected?

**Comment by kaalleen** [comment] 2024-11-27 16:33
Closing as duplicate of #3193

**Closed by kaalleen** 2024-11-27 16:33 UTC
Labels: bug, fill stitch

**Comment by kchiron** [comment] 2024-11-27 16:42
Hi, I'm sorry, I didn't have notification for your question. I don't remember which part was selected during the export :/.
