### ISSUE TITLE
path70: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

### ISSUE THREAD

**Issue by basedgodkat** [inkstitch/inkstitch#817] opened 2020-09-12 08:36 UTC
path70: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/auto_fill.py", line 212, in to_patches
  File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 55, in auto_fill
  File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 149, in build_fill_stitch_graph
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

Does anybody know how I could fix this? I spent the whole day trying to get Ink/Stitch to work and I finally figured it out. I'm literally at the last step of exporting it as a PES file, but it is unable to save due to this error. Thanks for your help!

**Comment by ecc521** [comment] 2020-09-13 18:11
I've seen this one before, and I'm pretty sure it's a duplicate. Can you upload your SVG?

**Comment by kaalleen** [comment] 2020-09-27 09:47
Duplicate of #734

**Closed** 2020-10-04 12:35 UTC
