### ISSUE TITLE
NickAinley needs updated, Bluenesia needs added

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#1878] opened 2022-10-26 17:31 UTC
The NickAinley alphabet pre-dates the current conversion method, so it lacks a proper spacing setup. It's just set to zero spaces everywhere, which is mostly fine for the lowercase since it is continuous, but means the uppercase gets a little wonky in places. It probably needs re-converted, at least as far as building the JSON, and then the JSON needs updated so the spacing matches the scale of the digitized version.

Also I think the version in the last release has almost none of the punctuation, and I've added some since then.

Also also Bluenesia should go in. It's just waiting for me to finish making all the acute/grave/circumflex/umlaut variations of the vowels. My computer's really getting bogged down by trims (which is super-annoying, Inkscape, those layers are *hidden* just leave them alone). So if someone with a snappier computer wants to tackle doing all the combos that would be fine.

(I assigned this to myself but it needs done before the next release so if I haven't gotten it done by the time the release is ready to go, call me out.)

**Comment by tyrosinase** [comment] 2023-04-17 23:41
Somebody might need to fix NickAinley for me; I have the impression the next release is coming out very soon but we are racing the moving truck for the next week and I will *not* have a chance at it.

I might be able to dig out the punctuation updates I made, but also I might have overwritten them. (The perils of ADHD: "I'll just try this exclamation point out temporarily in the live file [two hours later]... there, that's a bunch of new glyphs done." And then you load a new release without remembering to copy the live file back into the repo where you're *supposed* to be working on it)

**Comment by claudinepeyrat06** [comment] 2023-04-21 09:18
@tyrosinase 
I will deal with the json, but if you do have a better version of the font (that is with punctuation)I'd rather do it from that one.

**Comment by claudinepeyrat06** [comment] 2023-04-22 17:02
@tyrosinase 
can you check if you are happy with the attached file?  i had to modify both the svg ( x position of the glyph) and de json to have something close to the ttf. Close but not exactly the same because we need integer values in the json....
[nick_ainley.zip](https://github.com/inkstitch/inkstitch/files/11301869/nick_ainley.zip)

**Comment by claudinepeyrat06** [comment] 2023-04-22 17:04
I think that someone already dealt with Bluenesia. If not let me know and i will add it with the other fonts.

**Comment by tyrosinase** [comment] 2023-04-22 17:46
We're less than 48 hours from the moving truck arrival so I shouldn't even be typing this, but: the punctuation is only about five glyphs, and of course it's in two different files. One;
![→](https://user-images.githubusercontent.com/9473609/233799118-7c21f472-f09d-42da-9e06-57fb3f1d7bd4.svg)

**Comment by tyrosinase** [comment] 2023-04-22 17:47
![→](https://user-images.githubusercontent.com/9473609/233799138-c86c425c-7203-40c3-9ece-3be34a54ab1b.svg)

**Comment by tyrosinase** [comment] 2023-04-22 17:47
and two.

Thanks for doing this, sorry my move is so ill-timed. (Moves are *always* ill-timed, I am never moving again)

**Comment by claudinepeyrat06** [comment] 2023-04-22 17:58
Thanks. Hope your moving will be smooth....

**Comment by kaalleen** [comment] 2023-07-02 15:40
I think this is done? Well, Bluenesia wasn't included due to license issues.
I'm closing the issue now. Please protest if I am wrong.

**Comment by claudinepeyrat06** [comment] 2023-07-02 22:28
yes i have updated  nickAInley

**Comment by tyrosinase** [comment] 2023-07-02 23:03
And if I ever come up with the spoons to contact a stranger about Bluenesia licensing, I can just open a new issue (or figure out how these "pull request" gizmos work).

**Comment by kaalleen** [comment] 2023-07-09 09:53
Sounds good. Ask for help when you are ready :)

**Comment by tyrosinase** [comment] 2023-08-14 15:50
Okay, I'm finally getting around to updating poor old Nick.

It pre-dated the tutorial at https://inkstitch.org/tutorials/font-creation/ - I used to just copy the whole alphabet into my piece and drag-and-drop the letters and let the snap match them up. So when I turned it into an Ink/Stitch font I didn't go back to the otf, and it never had a proper json file. I'm fixing that now.

I've gone through the process to build it from scratch, then copypasted the existing glyphs over into the shiny new file. I dropped that starting point into the custom font directory (with a different name), typed the alphabet into the Lettering box, switched to the previewless new font and... it just hangs. Ruh roh. I do get an empty dialog that I can drag around for fun special effects.

![image](https://github.com/inkstitch/inkstitch/assets/9473609/c70a0059-0454-45b3-88e5-3082a343aedb)

Any ideas on where to start troubleshooting? I'm using a pre-release, so for starters I'm guessing I need to get on one that has the most stable Lettering stuff (or roll back to the current release).

**Comment by tyrosinase** [comment] 2023-08-14 15:51
It's got a bunch of empty glyph layers (so many missing glyphs...), but unless I failed to copy one in correctly (very possible!) my selection shouldn't have pinged any of them.

**Comment by tyrosinase** [comment] 2023-08-14 16:04
Ah, wait, when I hard-close the preview window it does throw an error, and that probably does mean there's an empty glyph.

```Traceback (most recent call last):
  File "lib/extensions/lettering.py", line 414, in apply
  File "lib/extensions/lettering.py", line 355, in update_lettering
  File "lib/lettering/font.py", line 195, in render_text
  File "lib/lettering/font.py", line 107, in _load_variants
  File "lib/lettering/font_variant.py", line 61, in __init__
  File "lib/lettering/font_variant.py", line 77, in _load_glyphs
  File "lib/lettering/glyph.py", line 40, in __init__
  File "lib/lettering/glyph.py", line 86, in _process_bbox
ValueError: min() arg is an empty sequence```

**Comment by claudinepeyrat06** [comment] 2023-08-14 16:07
What i did for the last release was recreate a json by exporting a svg font from the ttf file in  fontforge. I had the feeling that the kerning was quite ok.... looking at it now, i think that "horiz_adv_x_space" needs to be increase as the space between words is smaller than when using the ttf font.
Sorry, but no idea why you get these new problems.

**Comment by tyrosinase** [comment] 2023-08-14 16:09
> Sorry, but no idea why you get these new problems.

Because my motto in life is "hmm, what happens if I take this shortcut?" :laughing:

**Comment by tyrosinase** [comment] 2023-08-14 16:10
(And the kerning is pretty terrible on some of the capitals, because of all the swashing. Some of them will squish up against the rest of the word, others will leave a big space between.)

**Comment by claudinepeyrat06** [comment] 2023-08-14 16:21
Yes,  you are right, but the problem is already there in the ttf font. 
To correct that i would  add more kerning pairs in the json, but you need quite a lot, so maybe your way is faster.....

**Comment by tyrosinase** [comment] 2023-08-14 16:29
(to be clear, I meant the kerning on my version, not yours... my local one has overridden the one that currently ships because I never got around to clearing mine)

**Closed** 2023-12-31 14:25 UTC
