### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by Eric-Walp** [inkstitch/inkstitch#3207] opened 2024-09-22 03:06 UTC
![RMenergyLogo_Patch](https://github.com/user-attachments/assets/df15bcef-8eb5-496c-b9c0-1768940638cd)

When trying to simulate to see realistic view, it will not load file.  It will work for other files.  below is the error message. 

Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\troubleshoot.py", line 33, in effect
  File "lib\elements\satin_column.py", line 652, in validation_errors
  File "lib\elements\satin_column.py", line 1262, in to_stitch_groups
  File "lib\elements\satin_column.py", line 1090, in do_satin
  File "lib\debug.py", line 231, in decorated
  File "lib\elements\satin_column.py", line 898, in plot_points_on_rails
  File "lib\elements\satin_column.py", line 629, in flattened_sections
  File "lib\elements\satin_column.py", line 629, in <listcomp>
IndexError: tuple index out of range

**Comment by tyrosinase** [comment] 2024-09-22 19:20
Ah, the dreaded tuple-index. Luckily, 3.1.0 fixes that error. If for some reason you can't upgrade, the problem is caused by a single line (often a rung that's gotten disconnected) that's marked as a satin stitch.

**Closed by tyrosinase** 2024-09-22 19:20 UTC

**Comment by gusvisser** [comment] 2024-09-22 19:41
I just had a look at the file and it turns out on the letter I there is a running stitch with no params on it as soon as the running stitch param was applied everything works fine
![image](https://github.com/user-attachments/assets/c15a9794-de4d-492a-a5d1-65fee18d43c2)
