### ISSUE TITLE
params: Exception AttributeError: "'NoneType' object has no attribute 'GEOSSTRtree_destroy'"

### ISSUE THREAD

**Issue by kirtighate** [inkstitch/inkstitch#1089] opened 2021-03-15 14:05 UTC
I have installed inkstitch today only. But it is not working.I watched all videos . 
when i rum firt param this error come I didnt even saw preview like a video. I tried some other stitches they show previe but then they show some kind of error. im strugggling for 5 hours
Exception AttributeError: "'NoneType' object has no attribute 'GEOSSTRtree_destroy'" in <bound method STRtree.__del__ of <shapely.strtree.STRtree instance at 0x0B0584B8>> ignored

**Comment by MK-12-20MM** [comment] 2021-03-16 20:46
Hey Friend, @kirtighate 

Not sure if this related, but I will get this response if I get impatient and quit the parms dialog before it's done processing the design.  Larger designs or complex designs may take little longer than you think. You may have other other issues with your design, let the parms dialog run it's course, systematically then see what else comes.  In my experience, when I have had a lot of objects for the parms simulator to run, thinking there is another problem, this error will pop up when quitting the simulator too early on more complex designs.  In my cases there was nothing actually wrong.

In any case, I don't know if your issue is related to my experience as user.  Just a thought.

**Comment by kirtighate** [comment] 2021-03-18 07:26
Thank you so much .This was very helpful.

**Comment by kaalleen** [comment] 2021-04-12 17:33
I'll close this issue now, since this is a duplicate of #578
Please reopen or comment in #578 if you have more questions.

**Closed by kaalleen** 2021-04-12 17:33 UTC
