### ISSUE TITLE
No embroidery file save possible when "threadlist" is selected.

### ISSUE THREAD

**Issue by bianchifan** [inkstitch/inkstitch#2538] opened 2023-10-03 14:35 UTC
One of the designs I worked on for the "Kielux" presentation last month didn' t wrote a zip output with a selected threadlist.
Without a threadlist all was fine...
![Bildschirmfoto vom 2023-10-02 13-00-10](https://github.com/inkstitch/inkstitch/assets/17491743/a192427f-aed7-49b7-8e64-0f1951da4de2)

SVG was my "Black Swan in Flames" 13x20
![Burning Black Swan](https://github.com/inkstitch/inkstitch/assets/17491743/02772b56-d872-485c-a0ab-467f97c02845)

**Comment by kaalleen** [comment] 2023-10-11 17:33
I tried to save your svg with current main and cannot reproduce the error.
Can you narrow it down to a specific element by deleting more and more parts of the design while saving it again and see when it will actually saves the zip archive?

**Comment by kaalleen** [comment] 2024-12-15 21:04
This seemed to be a problem when no thread palettes were installed. I'm going to close the issue.
If this is still happening with current dev releases, please report to a new issue.

**Closed by kaalleen** 2024-12-15 21:04 UTC
Labels: needs steps to reproduce
