### ISSUE TITLE
Trouble with Troubleshooting, Simulator/Realistic Preview, and Params

### ISSUE THREAD

**Issue by 333rach** [inkstitch/inkstitch#2611] opened 2023-11-17 23:55 UTC
Hey everyone,

This is my first time using InkScape and I am trying to embroider my logo. I use MacOS Ventura 13.4.1 - I downloaded the v3.0.1 Monterey version.

I am having issues with trying to use the troubleshoot function I get this error message: 

Traceback (most recent call last):
  File "shapely/geometry/multipolygon.py", line 189, in geos_multipolygon_from_polygons
TypeError: 'Polygon' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 250, in run
  File "lib/extensions/troubleshoot.py", line 33, in effect
  File "lib/elements/fill_stitch.py", line 608, in validation_errors
  File "lib/elements/fill_stitch.py", line 542, in shape
  File "lib/elements/fill_stitch.py", line 592, in _get_clipped_path
  File "shapely/geometry/multipolygon.py", line 60, in __init__
  File "shapely/geometry/multipolygon.py", line 191, in geos_multipolygon_from_polygons
AttributeError: 'list' object has no attribute '_ndim'

I also do not see previews when using the Params option and when I try to use the realistic preview for my entire design (selected everything) it does not stop loading. However, when I click a single path the realistic preview works. Please help! 

Here is the SVG:
![CREST](https://github.com/inkstitch/inkstitch/assets/151270012/e6836179-6fd7-4ead-9765-01d3f6fdfc01)

**Comment by bianchifan** [comment] 2023-11-19 10:30
I've no skills with Mac OS but I guess no one can help you without the SVG which causes these messages.

**Comment by 333rach** [comment] 2023-11-19 18:29
> I've no skills with Mac OS but I guess no one can help you without the SVG which causes these messages.

Hello, I just edited and attached my SVG. I'm not sure why it looks like that :(

**Comment by tyrosinase** [comment] 2023-11-19 19:03
Github's SVG preview is always a little interesting, but the actual file is (usually) fine.

Looks like your issue is a duplicate of #2575. If so, there's a fix for the raw error message pending in the next release, and the comments there will have some explanation of the changes you'll need to make in your file. The new version will give you a more informative message but still won't stitch out the file without quite a bit more work. You'll want to do a lot of conversions to satins, and finding a pre-made font for your lettering will save you a huge amount of work.

I'm going to close the issue as redundant, but you can continue the comment thread if you need more help.

**Closed by tyrosinase** 2023-11-19 19:03 UTC
