### ISSUE TITLE
auto_fill: ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by ohmygoditsmimi** [inkstitch/inkstitch#1007] opened 2021-01-30 13:11 UTC
Hello,I designed this simple applique file and each object worked fine individually as well as in all layers. I was able to save it as an SVG file, but when I tried to save it as a PES I got the message below. For some reason I can't send the SVG file as an attachment. Thanks so much for any help you can provide!

path7335: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "d:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 212, in to_patches
  File "d:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "d:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "d:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "d:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 149, in build_fill_stitch_graph
  File "d:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

**Comment by kaalleen** [comment] 2021-01-30 13:21
This error we see a lot lately. Sorry for that. It is caused by very small fill shapes which are too small to embroider.
Run the extension under Extensions > Ink/Stitch > Troubleshoot > Cleanup document ...
This will remove them and you can go on working on your design.

**Comment by ohmygoditsmimi** [comment] 2021-01-30 14:27
I'm so sorry... when I go to troubleshoot it says all shapes are valid. It doesn't give me the option to clean up document. 😕

**Comment by kaalleen** [comment] 2021-01-30 15:56
Yes, we did not intend to make Ink/Stitch fail on these shapes, so troubleshoot will not see it.
In the troubleshoot menu there are more options than just troubleshoot objects, but also an option cleanup document. Which version of Ink/Stitch are you using?

**Comment by ohmygoditsmimi** [comment] 2021-01-31 03:21
I have version 1.0.0
Do I need to uninstall my old version before installing the newest version?

**Comment by ohmygoditsmimi** [comment] 2021-01-31 03:22
Wait, in have inkscape 1.0.0....I don't know which ink stitch I have. I'll check

**Comment by ohmygoditsmimi** [comment] 2021-01-31 04:40
Welp, I removed the ink stitch I currently  used and installed v1.29.1. Still don't have clean up document....this is so frustrating. Certainly not catastrophic, but upsetting nonetheless :(

**Comment by kaalleen** [comment] 2021-01-31 08:47
Does your menu look different from this?

![Cleanup](https://user-images.githubusercontent.com/36401965/106379014-47ca5f80-63a9-11eb-85f2-a3af1a275995.png)

**Comment by kaalleen** [comment] 2021-01-31 08:49
Of course it does... Sorry, I am on a developement branch.
But it should be the same in the troubleshoot section.

**Comment by ohmygoditsmimi** [comment] 2021-01-31 10:01
ugh....it definitely doesn't have that option. Can you suggest a video or tutorial on how to exactly go about installing the newest version of ink stitch? I'm not so computer literate and quite unable to understand what may seem like the most basic of instructions.
Thanks for being so patient and kind. :)

**Comment by ohmygoditsmimi** [comment] 2021-01-31 13:36
Okay, back again!! I finally figured out what I was doing wrong and it worked!! So excited 🤩

**Comment by kaalleen** [comment] 2021-02-03 17:26
Great :) Thank you for your feedback. I will close this issue then. Please reopen if needed.

**Closed by kaalleen** 2021-02-03 17:26 UTC
