### ISSUE TITLE
Inkstitch not working

### ISSUE THREAD

**Issue by densay1** [inkstitch/inkstitch#621] opened 2020-02-24 06:12 UTC
I have downloaded inkstitch extracted files to inkscape extension pathway. Inkstitch appears on extension list in inkscape. 
When i draw object make an object path go to inkstitch params this is the message i get:
Tried to launch: inkstitch\bin\inkstitch
Arguments: ['inkstitch\\bin\\inkstitch', '--id=path815', '--extension=params', 'C:\\Users\\denis\\AppData\\Local\\Temp\\ink_ext_XXXXXX.svgZL4XG0']
Debugging information:

Traceback (most recent call last):
  File "inkstitch.py", line 35, in <module>
    extension = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Program Files\Inkscape\lib\python2.7/subprocess.py", line 325, in __init__
    errread, errwrite)
  File "C:\Program Files\Inkscape\lib\python2.7/subprocess.py", line 575, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
Can you assist

**Comment by kaalleen** [comment] 2020-02-25 17:36
Most probably your antivirus program decided to delete inkstitch.exe.
The solution could be to whitelist it. Hope this helps.

**Comment by kaalleen** [comment] 2020-04-10 07:49
Duplicate of #613 
Closing the issue now. Please report further issues on this matter there.

**Closed by kaalleen** 2020-04-10 07:49 UTC
