### ISSUE TITLE
Mini-extension to set up embroidery origin guides

### ISSUE THREAD

**Issue by lexelby** [inkstitch/inkstitch#117] opened 2018-03-05 04:19 UTC
Now that we have the ability to specify the embroidery origin using guides, we should create an extension that adds the guides to the document.  Then the user can just drag them to wherever they'd like.

**Comment by thewildotter** [comment] 2018-03-07 19:19
A modest **about level**  level meta-data proposal(stolen mostly from OS directory meta-data)

"Now that we have the ability to specify the embroidery origin using guides,"  Arrrggh, I'm so uninformed!
When searching for origin or guide or ... I seem to sacrifice all relevance for excessive recall.
Is this an INKSCAPE reference, an SVG reference, a level reference, an "embroidery level" reference, an object reference,...  Sorry, but EXACTLY WHERE should I read about this to see authoritatively what 
this(guides) is and how to use it with providing an embroidery origin as the goal.  My first thought was that it was an svg document scope reference for INKSCAPE. Furthermore, I fantasized that a documentation level might always(if not preferenced to bit bucket) be appended(created if not yet there) with the origin guides used possibly included.  A documentation level possibly named("about") might also be preferenced to log what versions of what extensions(who) created what additional levels, when and who/when they were last updated.  Note that this does not grow without bound but tracks the level count.   Other preferences might allow more detailed and thus expansive logging which should not be default enabled.  I have not researched what already exists in favor of blurting this out to get history/advice from the more inkscape/inkstitch/svg experienced about what exists and where to authoritatively read about it. If that means read the code, then so-be-it but I figured I'd ask first since code usually does not retain lore(historical perspective.)
   My casual whim would be a normally not visible "about" layer with INKSCAPE origin labeled guides,
ink---stitch origin (embroidery origin) labeled guides, and creation/lastAccess loging unobtrusively tucked away but explicitly accessible.  I perceive no need for an extension specific to ink---stitch since this "about" level would be implicitly created or updated whenever any well behaved extension creates or updates a level.  I am fully aware that this is as-time-allows software but _I thought I might propose this vision as a possibility_.
   Inkscape itself might provide an "about" level mini-API to standardize the "about" level access  to the meta-data by the various extensions to encourage code reuse/modularization, reduce effort, and minimize bugs.  Ink---stitch coders(or anyone else available) might actually generate the first version of this if time allows.   As an API it should be a chunk of work which is well isolated and containable and  a development phase-in "about editor" using the API could look like an extension and provide a means to repair any damaged "about" levels from here on out and for regression testing API changes.

thewildotter

**Comment by lexelby** [comment] 2018-03-08 00:57
Sorry for the rough edge here!  There is no documentation for this feature yet.  You can read more about it in pull request #52.  This comment has an example of using guides to define the embroidery origin: https://github.com/lexelby/inkstitch/pull/52#issuecomment-368330194

v1.4.0 has this feature.  The two guides must be named "embroidery origin" or at least start with "embroidery origin", and they must intersect somewhere.  That intersection point becomes 0,0 in the embroidery machine output file.

Hmm, as I'm reading your suggestion, I wonder... when you say "level", do you mean "layer"?

**Comment by thewildotter** [comment] 2018-03-08 13:32
**The Chip Design Automation vs Graphic Design Correlation**

Yep, I meant layer.  I retired from a chip design automation job where the layers were called levels(chip manufacturing processing levels).  There are LOTS of similar problems so I am sorry that I may be blasting a firehose of proposals.   Hopefully, you will find some useful gems in the heaps of stuff.  My last effort prior to retiring was kind of a project management software package which generated an HTML output comparing >27 different chip design databases for coarse inconsistencies in design data for a specific chip, so I have seen a great many solutions to a lot of generic problems.  Design inconsistencies were highly correlated to incomplete work in any specific application so my insight was to evaluate the completeness status of a specific project based on how consistent the design data was across all the (yes, due to VLSI design automation history we had excruciating redundancy) various tools packages in use for a project.  The tool packages were kind of like inkscape extensions on steroids.  Since I had been an architect during the development of many of the packages, I had inside info on how to read each of them so I was uniquely positioned to read them all and highlight coarse inconsistencies to sleuth out early warning signs of potential schedule impacts due to incomplete efforts by users to exercise their toolkit on their piece(s) within the design hierarchy of the chip being designed.   One spinoff of my project management tool was the identification of modularization techniques which ultimately worked well across all of design automation.  Several tools were able to steal API's from other toolsets when they were unhappy with how their original roll-your-own solutions to peripheral problems worked.  Voluntary code reuse is a beautiful thing.   Open Source recognizes this already so I am happy that my experience matches the general direction of this community.

thewildotter

**Comment by X3msnake** [comment] 2018-03-08 22:32
@wwderw just posted a video documenting this enjoy ;)

https://youtu.be/w7ZjgxdcAp4

**Comment by kaalleen** [comment] 2018-11-20 16:58
Closing this. We do not use the origin guides anymore. Origins are set with the commands extension by now.

**Closed by kaalleen** 2018-11-20 16:58 UTC
Labels: feature request, help: docs, information
