### ISSUE TITLE
auto_fill: ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by pedrud** [inkstitch/inkstitch#1092] opened 2021-03-20 03:11 UTC
I got this error when trying to export to dst format. 

Traceback (most recent call last):
  File "/home/runner/work/inkstitch/inkstitch/lib/elements/auto_fill.py", line 212, in to_patches
  File "/home/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/home/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 55, in auto_fill
  File "/home/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/home/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 149, in build_fill_stitch_graph
  File "/home/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

**Comment by MK-12-20MM** [comment] 2021-03-20 13:07
@pedrud 

Hi,
Sounds like you have a small fill area or artifact in your document to small to realistically stitch .  You should be able to clean these up by Inktitch > Troubleshoot> Cleanup Document. 

Just a tip: Since you are trying to export, everything else worked I will assume. From my experience parms can be ran on selected objects or the whole document. Troubleshoot objects works the same way. From this perspective, inadvertently parms or the Trouble Objects running on selected objects may not reveal that there is an issue in somewhere in the document until you export. As a user, I do this all the time where everything is good until the export.  You might want to try parms on your design or even the Troubleshoot  Objects - with no objects selected. This should reveal if there is a small artifact in your document. Else run the Cleanup Document. That tool will indicate you have an object that may be to small and can remove it.

Most of these small fills or artifacts come from Inkscape when using some of tools and tracing. Most of mine are just accidently clicking on mouse using the Inkscape drawing tools and leaving a very small artifact to small to really see.

Hopefully this helps (at least from my experience).

**Comment by pedrud** [comment] 2021-03-20 19:09
@MK-12-20MM 

Thanks for the reply and correcting my title. So I didn't end up using Troubleshoot (just seeing your response now) as you suggest, but went about it in a slightly more tedious manner. I went and tested params on each individual layer until I found what was throwing the error. One layer did in fact have several artifacts and had a few points that crossed. I completely deleted that layer and remade it and then it worked fine. 

The other item was a bigger issue that I wasn't sure how to work around. I had some Japanese text as a layer in the svg file. In the same layer I also had some curved text on a path. Ink/stitch did not like either one of those, even after I converted them to a path. I ended up modifying the design and left them out.

After that, there were no more errors and I was able to successfully export to a .dst file.

I suppose I should have noted in my initial post that I am using Ubunutu 20.10, Inkscape 1.0.2, and ink/stitch v. 1.29.1. 

Any idea when there will be another update to the project?

**Comment by MK-12-20MM** [comment] 2021-03-22 14:30
@pedrud

I am glad that some of that worked out. BTW- I am just a Ink/Stitch user.  Just trying to help out where I can or have possible solutions. 

About your other issues, you did not indicate which or what type of error occurred. I think more details on that the error is needed.  

My understanding  is that a new release is being worked on aggressively. Devs will have to comment on that portion.

**Comment by pedrud** [comment] 2021-03-22 18:49
@MK-12-20MM 

Thanks, much appreciated. I honestly don't have any more info on the error aside from the popup I received, which I copied on my post above.

**Comment by kaalleen** [comment] 2021-03-23 16:40
We believe the error will be fixed in the upcoming release. It should be out soon, maybe within the next month.

**Comment by kaalleen** [comment] 2021-03-28 09:03
Duplicate of #734

**Closed by kaalleen** 2021-03-28 09:03 UTC
