### ISSUE TITLE
Error received:  Extensions > Ink/Stitch > Visualise and Export > Embroidery

### ISSUE THREAD

**Issue by dygrieve** [inkstitch/inkstitch#962] opened 2021-01-03 02:22 UTC
Working on a logo image, received this error when trying to convert to embroidery file:

path552_7: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/auto_fill.py", line 212, in to_patches
  File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 55, in auto_fill
  File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 149, in build_fill_stitch_graph
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

I also can't seem to save my embroidery file!

**Comment by kaalleen** [comment] 2021-01-03 16:11
Thanks for your report. This error we have seen often. It seems to be caused by very small fill objects. Try to trace them down and delete them. The functions "cleanup document" or "break apart fill objects" might help in order to do that.

**Comment by kaalleen** [comment] 2021-01-17 11:52
Duplicate of #734

**Closed by kaalleen** 2021-01-17 11:52 UTC
