### ISSUE TITLE
auto_fill: min() arg is an empty sequence

### ISSUE THREAD

**Issue by santiagodmt** [inkstitch/inkstitch#1046] opened 2021-02-19 17:03 UTC
Hello, i had many problems to save in .pes for a Brother embroidery doc in Inkscape!, i make designs in Adobe Illustrator, everything in order using layers from any color and a specific layer for stroke, i save in PDF, i can open in Inkscape and bring parameters each one layers of my design, but when im going to save in .pes, doesnt work!
![pantallazo-01](https://user-images.githubusercontent.com/79327739/108536074-0216fd80-72aa-11eb-8b02-12fb4aa88f25.png)
And dont let me save in .pes for embroidery document!
![image](https://user-images.githubusercontent.com/79327739/108536312-53bf8800-72aa-11eb-8588-12f1704ffa07.png)

I dont know what can i do, please help me!,
thanx so much ( sorry for my english)

**Comment by tyrosinase** [comment] 2021-02-19 17:14
Usually that means there are pieces too small for Ink/Stitch to figure out how to stitch. Check the `Ink/Stitch > Troubleshoot` menu, and also use `Path > Break Apart` on any same-color objects that are multiple separate pieces.

**Comment by santiagodmt** [comment] 2021-02-19 20:04
Thank you pal!

**Comment by kaalleen** [comment] 2021-03-06 13:11
This is a duplicate of #734. I will close this issue now. Please reopen if it is still needed.

**Closed by kaalleen** 2021-03-06 13:11 UTC
