### ISSUE TITLE
Fill seems not to work (v1.28.0, Inkscape 1.0, Catalina)

### ISSUE THREAD

**Issue by magnustron** [inkstitch/inkstitch#704] opened 2020-05-16 20:14 UTC
Hi Inkstitch developers,

I am new to inkstitch, so please forgive me any beginners mistake. But, it seems as if filling does not work. I am on Catalina and Inkscape 1.0 (4035a4f, 2020-05-01), and installed the latest release: https://github.com/inkstitch/inkstitch/releases/tag/v1.28.0

This is the file that I used to try, just a simple triangle (zipped svg, as svg upload is not supported):
[foo.zip](https://github.com/inkstitch/inkstitch/files/4639147/foo.zip)

When opening the `Params`, I do not see any preview (unlike cases of shapes with strokes, where the satin stitches are shown). Then, when clicking on `Stich Plan Preview`, I get the error below.

Would be great if you could have a look!
Cheers,
Magnus

```
Ink/Stitch experienced an unexpected error.
If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below: 

Traceback (most recent call last):
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/inkstitch.py", line 44, in <module>
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/inkscape/share/extensions/inkex.py", line 283, in affect
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/extensions/stitch_plan_preview.py", line 18, in effect
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/extensions/base.py", line 185, in elements_to_patches
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/elements/element.py", line 307, in embroider
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/elements/element.py", line 364, in validate
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/elements/fill.py", line 147, in validation_errors
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/backports/functools_lru_cache.py", line 124, in wrapper
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/elements/fill.py", line 135, in shape
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/elements/fill.py", line 135, in <lambda>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/geometry/base.py", line 438, in area
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/topology.py", line 55, in __call__
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/topology.py", line 18, in _validate
ValueError: Null geometry supports no operations
```

**Comment by kaalleen** [comment] 2020-05-16 20:57
Hm, yes, we've heard this one before (#448).
I tested your file (thank you for sending it with the issue!) and cannot reproduce the issue.
But still, we are going to have a look into it. It somehow thinks, that the shape isn't valid.

**Comment by magnustron** [comment] 2020-05-16 21:26
Great!
In case it helps, I changed the `.inx` to get access to the parameters that inkscape sends to the inkstitch extension. These are the command line arguments:
```
--id=path833
--extension=stitch_plan_preview
/var/folders/b7/7f0qtnnx30j46wq_mg6rbsx40000gn/T/ink_ext_XXXXXX.svgI9XQK0
``` 
And I attach you here the file that is passed:
[ink_ext_XXXXXX.svgI9XQK0.zip](https://github.com/inkstitch/inkstitch/files/4639247/ink_ext_XXXXXX.svgI9XQK0.zip)

**Comment by kaalleen** [comment] 2020-05-17 14:28
I had someone test it (both versions) with Ink/Stitch v1.28.0 and Inkscape 1.0 on Catalina. Impossible to catch the error. I don't know where the invalid shape would come from?! This is very odd.

@lexelby could you have a look at this?

**Comment by magnustron** [comment] 2020-05-18 07:13
After a bit of trial and error: when removing `shapely.speedups._speedups.so` **it works!** This is super-strange.

I was also running the `inkstitch` executable from the command line trying to exclude some library mix-up:
```bash
sudo dtruss -f ./inkstitch/bin/inkstitch  --extension=stitch_plan_preview /tmp/foo.svg 2>&1 | grep 'shapely'
```
and did not get any mentioning of `shapely`. I thought that I would at least see the a sys call trying to open a python file or shared library. Anyhow.

**Comment by danielkschneider** [comment] 2020-05-18 15:47
I got a similar weird bug and the file is attached. It seems to be valid XML (W3C validator). I made the example with the online SVG-Edit tool and then imported to InkScape.
[tronc-svg-demo3.zip](https://github.com/inkstitch/inkstitch/files/4645169/tronc-svg-demo3.zip)

Using Windows 10, Inkscape 1.0 and InkStitch 1.28.

`Ink/Stitch a connu une erreur inattendue.
Si vous souhaitez nous aider à résoudre ce problème, veuillez soumettre un problème à https://github.com/inkstitch/inkstitch/issues et inclure la description complète de l'erreur ci-dessous : 

Traceback (most recent call last):
  File "d:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "d:\a\inkstitch\inkstitch\inkscape\share\extensions\inkex.py", line 283, in affect
  File "d:\a\inkstitch\inkstitch\lib\extensions\params.py", line 586, in effect
  File "d:\a\inkstitch\inkstitch\lib\extensions\params.py", line 322, in __init__
  File "d:\a\inkstitch\inkstitch\lib\extensions\params.py", line 551, in create_tabs
  File "d:\a\inkstitch\inkstitch\lib\extensions\params.py", line 481, in get_nodes_by_class
  File "d:\a\inkstitch\inkstitch\lib\extensions\base.py", line 167, in get_nodes
  File "d:\a\inkstitch\inkstitch\lib\extensions\base.py", line 159, in descendants
  File "d:\a\inkstitch\inkstitch\lib\extensions\base.py", line 145, in descendants
  File "d:\a\inkstitch\inkstitch\lib\elements\element.py", line 177, in has_style
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\backports\functools_lru_cache.py", line 124, in wrapper
  File "d:\a\inkstitch\inkstitch\lib\elements\element.py", line 160, in _get_style_raw
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\backports\functools_lru_cache.py", line 124, in wrapper
  File "d:\a\inkstitch\inkstitch\lib\elements\element.py", line 154, in parse_style
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\tinycss2\parser.py", line 175, in parse_declaration_list
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\tinycss2\parser.py", line 20, in _to_token_iterator
 
[tronc-svg-demo3.zip](https://github.com/inkstitch/inkstitch/files/4645151/tronc-svg-demo3.zip)

TypeError: 'NoneType' object is not iterable`

**Comment by kaalleen** [comment] 2020-05-18 15:48
Wow, interesting! Wouldn't have thought of that.

We use shapely a lot and for everything. The speedup functionality is enabled by default since shapely 1.6: https://shapely.readthedocs.io/en/latest/manual.html#performance

**Comment by kaalleen** [comment] 2020-05-18 15:52
@danielkschneider I think this is an other cause. But I can reproduce your issue and will have a look into it.

**Comment by lexelby** [comment] 2020-05-25 19:56
Wow, I wouldn't have thought of that either.  I also have no idea why removing the speedups library works, but I'm glad you found a solution.

@kaalleen I'm not really sure how to handle this, maybe an FAQ entry or something?!

**Comment by kaalleen** [comment] 2020-05-27 14:20
> @kaalleen I'm not really sure how to handle this, maybe an FAQ entry or something?!

Sure, can do.

**Comment by kaalleen** [comment] 2021-04-04 09:11
Our Website informs about this error whic occurs to somew macOS users if they don't delete the shapely speedup files.

I'll have to update the path to the speedup file for the new Ink/Stitch version, but this error still occurs (even with the shapely update).

Since there is no better solution and we have the documentation, I'll close the issue now.

**Closed by kaalleen** 2021-04-04 09:11 UTC
Labels: bug
