### ISSUE TITLE
PES FILES (AGAIN)

### ISSUE THREAD

**Issue by harvey08999** [inkstitch/inkstitch#2087] opened 2023-02-22 19:56 UTC
nk/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\extensions\base.py", line 200, in elements_to_stitch_groups
  File "lib\elements\element.py", line 329, in embroider
  File "lib\elements\element.py", line 387, in validate
  File "lib\elements\fill_stitch.py", line 321, in validation_errors
  File "lib\elements\fill_stitch.py", line 274, in shape
AttributeError: 'Point' object has no attribute 'geoms'

![image](https://user-images.githubusercontent.com/126018294/220744348-6a6a1e4c-029d-421f-b975-94c97a480dd7.png)

**Comment by kaalleen** [comment] 2023-02-25 12:35
Search for small elements in your file and remove them.

**Comment by kaalleen** [comment] 2023-02-25 12:47
Duplicate of #1742

**Closed by kaalleen** 2023-02-25 12:47 UTC
