### ISSUE TITLE
Adaptable preview filter selection

### ISSUE THREAD

**Issue by AnasImr** [inkstitch/inkstitch#3192] opened 2024-09-12 21:58 UTC
So all the realstic images that I export contain weird areas of a different shade of the main color, regardless of the angle of the stitches I use
![وَدِيـنـي دِيـنُ عِـزٍّ black](https://github.com/user-attachments/assets/a7983f20-a4b3-4402-b69c-ae83c0d68021)
![Selma arabic calligraphy_realistic](https://github.com/user-attachments/assets/34414c7c-2d69-4dc5-861d-03e3a06c36d7)
this is especially bothering since It doesn't look natural like the realistic previews of other softwares like wilcom e4, theirs looks like this:
![image](https://github.com/user-attachments/assets/227fd9dd-5ef2-4376-9362-4adcee35f042)
- I would love it if there was a feature that allows the users to adjust the looks of the realistic stitches, this could expand to people having shareable templates/styles for realistic stitches, where they would share them to the community so everyone benefits
- For now I would be happy if someone could give me a quick solution to make all realistic stitches have the same shade of color, accros all the embroidery, that way the realistic preview is presentable to people, as I need it in my business, thanks :)

**Comment by AnasImr** [comment] 2024-09-13 05:44
A user already found a workaround in #3183, But I'm still open to other solutions if anyone has one !

**Comment by kaalleen** [comment] 2024-09-14 08:38
Closing as duplicate of #3183

I just noticed that the other issue also suggests a custom filter selection. So we can close this as it requests the very same thing.

**Closed by kaalleen** 2024-09-14 08:38 UTC
Labels: feature request, stitch plan preview
