### ISSUE TITLE
AutoFill: ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by stlbr** [inkstitch/inkstitch#884] opened 2020-11-14 21:38 UTC
path1525: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/auto_fill.py", line 212, in to_patches
  File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 55, in auto_fill
  File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 149, in build_fill_stitch_graph
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

**Comment by kaalleen** [comment] 2020-12-03 20:06
Duplicate of #734 

Read through the thread I mentioned above. You should try to remove tiny objects from your document. Sorry for this error to happen. It is an annoying error to a lot of users lately. We hope to fix it soon in a future release.

**Closed** 2021-01-17 11:48 UTC
