### ISSUE TITLE
Sections of fill stitch seem to be missing in relation to page

### ISSUE THREAD

**Issue by Vueldon** [inkstitch/inkstitch#2298] opened 2023-05-16 22:10 UTC
This file seems to have an issue with fill stitches that I can't seem to deduce. When simulated as is, the fill of the sails and hull of the boat design have a chunk sliced off on the left side. However, the location and size of the missing chunk/s changes if you move the overall design—like the issue is related to the page itself.
![image](https://github.com/inkstitch/inkstitch/assets/54679363/3766e086-568e-456e-84aa-25086599ddd7)
![Boat-Test-4](https://github.com/inkstitch/inkstitch/assets/54679363/ef6661a9-b906-44e7-bd75-f1b64b8f9fb7)
I used the object troubleshooter and fixed all of the listed issues within the design, but it made no difference. Everything else about the file seems to work properly, and I was preparing to add commands and run an embroidery test, but I cannot figure this out.

**Comment by Vueldon** [comment] 2023-05-19 13:32
**Computer**
Edition:	Windows 10 Pro
Version:	22H2
Installed on:	‎10/‎6/‎2021
OS build:	19045.2965
Experience:	Windows Feature Experience Pack 1000.19041.1000.0

**Inkscape**
Inkscape 1.2.2 (732a01da63, 2022-12-09)

**InkStitch**
InkStitch v2.2.0

**Comment by kaalleen** [comment] 2023-07-02 07:03
Do you still see the same problem with the latest release?

**Comment by kaalleen** [comment] 2023-07-16 07:39
Since I'm not able to reproduce the issue I'll close it now. If you are still seeing similar problems with the newest Ink/Stitch release, please protest and I'll reopen the issue again and investigate what is going wrong.

**Closed by kaalleen** 2023-07-16 07:39 UTC

**Comment by Vueldon** [comment] 2023-07-24 19:14
I've been away, but I wanted to let you know that the issue does indeed seem to be fixed with the new release.
