### ISSUE TITLE
stitch_plan: IndexError: list index out of range

### ISSUE THREAD

**Issue by jromebrown** [inkstitch/inkstitch#1240] opened 2021-06-10 01:52 UTC
I'm trying to save my logo as a .dst file so that I can have it embroidered but I received this error message:

/Users/user/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/inkstitch.app/Contents/MacOS/lib/extensions/base.py:58: DeprecationWarning: inkex.etree was removed, use "from lxml import etree"
Ink/Stitch experienced an unexpected error.

Also, after prompting me to go to this website, it said to include this:

Ink/Stitch Version: v2.0.0 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex/base.py", line 141, in run
  File "lib/extensions/output.py", line 56, in effect
  File "lib/stitch_plan/stitch_plan.py", line 26, in patches_to_stitch_plan
IndexError: list index out of range

**Comment by kaalleen** [comment] 2021-06-10 16:24
Thank you for reporting your issue. We have seen it several times by now. Usually there has been the problem, that there was no embroiderable path in the document (e.g. only a text or image elements). If that is not the case with your file, we would really like to have a look into it. If you like, you can post your file here or send it to us: send-us-files@inkstitch.org

**Comment by jromebrown** [comment] 2021-06-11 00:45
Awesome, this is the file:
![RD Letter Mark](https://user-images.githubusercontent.com/85656749/121614502-72e25100-ca24-11eb-8fde-1f9ad6de258a.png)

**Comment by jromebrown** [comment] 2021-06-11 00:46
and this one
![RAWDADDY WHITE](https://user-images.githubusercontent.com/85656749/121614539-82619a00-ca24-11eb-9b9e-0b3453e57b81.png)

**Comment by kaalleen** [comment] 2021-06-12 07:24
Thank you! Try to run Path > Convert Object to Path
This will help you to receive an embroiderable element.

If you have letters such as an i (disconnected shapes), you will also need to run Extensions > Ink/Stitch > Fill Tools > Break apart fill objects. But this won't be necessary for the letters in your image.

**Comment by kaalleen** [comment] 2021-07-19 07:01
Duplicate of #1199

**Closed by kaalleen** 2021-07-19 07:01 UTC
