### ISSUE TITLE
Cannot save as pes

### ISSUE THREAD

**Issue by andyyrogers** [inkstitch/inkstitch#1344] opened 2021-09-16 15:50 UTC
I have tried everything and read all of the forums on here and am about to pull my hair out!! I am not an artist by any means, I don't understand how to do bitmap tracing and make it come out right considering what I need this software for is to make real pictures (not cartoon, graphics, or logos) turn into an embroidery stitch. I used another website to convert the photo to an svg. the svg loads great and even gets drawn out when i use params, but it will not, by any means, save as a pes. I have tried to go to the embroidery save, change the name, and do everything mentioned in the other forums. Someone please give me an answer! 

Codes that come up:

when I use "save as", "save as a copy", embroider

lib/extensions/base.py:58: DeprecationWarning: inkex.etree was removed, use "from lxml import etree"
Ink/Stitch experienced an unexpected error.

If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below:

Ink/Stitch Version: v2.0.0 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex/base.py", line 141, in run
  File "lib/extensions/output.py", line 56, in effect
  File "lib/stitch_plan/stitch_plan.py", line 26, in patches_to_stitch_plan
IndexError: list index out of range

**Comment by tyrosinase** [comment] 2021-09-16 16:31
Sometimes this comes up when there's a malformed svg - try changing the colors on each object to make sure there's nothing weird in there. If that doesn't fix it, then doing a Path > Union on each single object will usually cause Inkscape to build a fresh object free of inherited oddities (it'll also clear Ink/Stitch params if you've changed any).

It's always better to use Inkscape itself to convert a bitmap to an SVG. There are a lot of buttons and dials to tweak, but if you duckduck "Inkscape bitmap" you'll find a ton of tutorials, some of which start with photographs.

**Comment by andyyrogers** [comment] 2021-09-16 21:02
I tried all of that and still received this:

lib/extensions/base.py:58: DeprecationWarning: inkex.etree was removed, use "from lxml import etree"

**Comment by andyyrogers** [comment] 2021-09-16 21:15
I get this one occassionally too:

lib/extensions/base.py:58: DeprecationWarning: inkex.etree was removed, use "from lxml import etree"
path125-4: error: Fill: Shape is not valid.  This can happen if the border crosses over itself.

**Comment by tyrosinase** [comment] 2021-09-16 21:41
The deprecation warning shouldn't hurt anything; I think one of the devs mentioned it will go away in the next release. As long as you're not also getting errors, the file will write fine.

The border-crosses thing can be fixed with... uh... Troubleshoot > Cleanup Items, I think. (I always clean up my stuff manually and *then* remember that's a thing now.)

**Comment by andyyrogers** [comment] 2021-09-16 22:04
tried that and am still not able to save. How is this still happening I don't understand

**Comment by calybr** [comment] 2021-09-16 23:55
I was has having the same issue earlier... I'm completely new to embroidery and Inkscape/Inkstitch so this may not be helpful to you, but have you gone to Extensions > Ink/Stitch > Troubleshoot > Troubleshoot objects?  That was the only way I was able to figure out what was going wrong on mine, but I was only using text so it may not be as simple for you.  Good luck!

**Comment by andyyrogers** [comment] 2021-09-17 00:23
> I was has having the same issue earlier... I'm completely new to embroidery and Inkscape/Inkstitch so this may not be helpful to you, but have you gone to Extensions > Ink/Stitch > Troubleshoot > Troubleshoot objects? That was the only way I was able to figure out what was going wrong on mine, but I was only using text so it may not be as simple for you. Good luck!

that still didnt work:( thank you though

**Comment by tyrosinase** [comment] 2021-09-17 02:25
When you say that didn't work, are you saying it told you all your objects were valid?

**Comment by jinnyanctil** [comment] 2021-10-20 00:03
> When you say that didn't work, are you saying it told you all your objects were valid?

Hi! I have the same problem and when I do that, it says that all my shapes are valid even tho when its time to save they are not...

**Comment by kaalleen** [comment] 2021-12-08 09:45
@andyyrogers @jinnyanctil were you able to fix your issues?

**Comment by Jaga1203** [comment] 2022-05-11 03:12
Hi all

I am starting to have the exact same problem.   I've been using inkstitch for a while with no error messages, however recently i got this error.

lib\extensions\base.py:58: DeprecationWarning: inkex.etree was removed, use "from lxml import etree"  

I got to this but i see no clear solution has been found

**Comment by Gmazz7** [comment] 2022-08-10 04:29
I am having the Issue that was first described where my file will not save as a PES even though it runs without a problem through Params and visualization.  When I try to save as PES, I get error message 912 that says shape is not valid. Maybe because border crosses over itself.  However, when I run the troubleshooting on objects, I received a message that all shapes are valid. 
I sent my svg file to the email noted above.
Any help to resolve and prevent me from having the same error going forward, would be appreciated.

**Comment by lexelby** [comment] 2022-08-10 11:12
First thing: please try the latest version of Ink/Stitch.  We've made some changes under the hood and now it tries to make objects valid on its own instead of showing that error.

**Comment by Gmazz7** [comment] 2022-08-11 21:57
That did it! Once I installed the update, it saved as a PES.
Thank you

**Comment by Gmazz7** [comment] 2022-08-12 04:35
Thank you - it worked now.

**Closed** 2023-07-23 07:53 UTC
Labels: needs steps to reproduce

**Comment by ameliazoe1990** [comment] 2024-05-22 21:55
Did you saved as your PES? Error 912 in a PES file typically indicates a problem with the file structure or formatting. It may arise due to issues during the digitizing process or when attempting to read the file with embroidery software. This error often requires troubleshooting the file or re-digitizing the design to resolve the issue. 

I had a same issue when i digitize a design for embroidery machine i have DST file. The issue is I tried so many ways to get PES file format. I didn't get any solution. There are 100s of online converters and all are FAKE except one image2emb. They have real digitizers on their back who [converts jpeg to dst online](https://image2emb.com/dst-file-converter/jpeg-to-dst-file-converter/) in fast turnaround time. I asked them is there any way to get this online ? They said its no possible in this life to upload any jpeg and it turn automatic into stitches form. This work is only done by manual digitizing by embroidery softwares. I guess they are right!
