### ISSUE TITLE
Failure trying to save as .pes

### ISSUE THREAD

**Issue by lovidlovid** [inkstitch/inkstitch#1203] opened 2021-05-12 00:43 UTC
Unable to save as .pes 
Getting the following error message:
//
Ink/Stitch experienced an unexpected error.

If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below:

Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\stitch_plan\stitch_plan.py", line 26, in patches_to_stitch_plan
IndexError: list index out of range
//
Windows 10 home x 64 based PC

**Comment by Tina-Chris** [comment] 2021-05-12 12:07
@kaalleen Is this is the same as https://github.com/inkstitch/inkstitch/issues/1199 ?

**Comment by kaalleen** [comment] 2021-05-15 08:24
Duplicate of #1199 

Therefore I'll close the issue. This doesn't mean, we will not be working on it. Read updates upon this issue there.

It seems to be caused when a rendering extension (such as exporting the embroidery designs) is called on a single non embroiderable object (for example text elements). Text needs to be converted into a valid path as a minimum requirement. It would look best with a satin column in most cases though.

**Closed by kaalleen** 2021-05-15 08:24 UTC
