### ISSUE TITLE
stitch_plan: IndexError: list index out of range

### ISSUE THREAD

**Issue by Klauwdia** [inkstitch/inkstitch#1245] opened 2021-06-11 10:44 UTC
Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\stitch_plan\stitch_plan.py", line 26, in patches_to_stitch_plan
IndexError: list index out of range

**Comment by tyrosinase** [comment] 2021-06-11 11:30
On Fri, Jun 11, 2021, at 6:44 AM, Klauwdia wrote:
> 

> Ink/Stitch Version: v2.0.0 (windows)


> Traceback (most recent call last):
> File "inkstitch.py", line 52, in 
> File "inkex\base.py", line 141, in run
> File "lib\extensions\output.py", line 56, in effect
> File "lib\stitch_plan\stitch_plan.py", line 26, in patches_to_stitch_plan
> IndexError: list index out of range


That's the same error as here: https://github.com/inkstitch/inkstitch/issues/1244
(I'm not a dev and can't merge the issues, but the explanation of what's going on is there)

**Comment by kaalleen** [comment] 2021-07-19 07:01
Duplicate of #1199

**Closed by kaalleen** 2021-07-19 07:01 UTC
