### ISSUE TITLE
Issue when trying to preview and save

### ISSUE THREAD

**Issue by btenn10** [inkstitch/inkstitch#2076] opened 2023-02-19 16:46 UTC
nk/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v2.2.0 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 231, in run
  File "lib/extensions/stitch_plan_preview.py", line 39, in effect
  File "lib/extensions/base.py", line 200, in elements_to_stitch_groups
  File "lib/elements/element.py", line 329, in embroider
  File "lib/elements/element.py", line 387, in validate
  File "lib/elements/fill_stitch.py", line 321, in validation_errors
  File "lib/elements/fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'
![KOKO stitch](https://user-images.githubusercontent.com/125818970/219962176-02dccf35-c450-4649-bc30-bd80242b96f2.svg)

**Comment by kaalleen** [comment] 2023-02-20 16:29
Remove these two paths here

![2077](https://user-images.githubusercontent.com/36401965/220159268-ba51e156-3556-4ef9-bc89-835fe99f04e3.png)

**Comment by kaalleen** [comment] 2023-02-25 12:52
Duplicate of #1742

**Closed by kaalleen** 2023-02-25 12:52 UTC
