### ISSUE TITLE
Inkstitch is downloaded, but not available

### ISSUE THREAD

**Issue by dledwards09** [inkstitch/inkstitch#717] opened 2020-05-20 20:57 UTC
I have tried downloading this several times. Uninstalling Inkscape and reinstalling the newest version also. I got Inkstitch downloaded into the correct path, however, the only choices that are not grayed out still are commands, fill tools, and satin tools. But, when I click on those, they are not working properly either. So, the extensions are showing up, but are not working. I am not getting any type of error message. They are just not available to use. I'm running Windows x64, so I downloaded the only Windows US version available. What else can I do? Is there another version available? Any help or suggestion would be appreciated!

**Comment by geonom** [comment] 2020-05-21 13:10
Ah, this could be related to my issue and be a Duplicate of #718 or the other way round - because the same appearance happens on my computer and that of a friend of mine - Win 10 quarantines the inkstitch.exe file automatically (the friend of mine got a warning - mine was quarantined without even a warning :/ ).

**Comment by geonom** [comment] 2020-05-21 13:13
Can you check in your protection history, whether there was a "severe threat" blocked? See #711

**Comment by dledwards09** [comment] 2020-05-21 17:20
That’s what’s happening! See below. So, can you help me fix that? Or is there a way to fix it? Thanks for your help in figuring it out. I thought I was going crazy!

[cid:image001.png@01D62F72.A0969A50]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by geonom** [comment] 2020-05-21 17:43
Well, if you are sure, that inkstitch.exe does not contain a virus despite the warnings, then in your protection history, you can click on the "Actions" button below and click on "Allow".

I would not recommend that though until developers can make sure, there is no virus and that the warning is false positive.

**Comment by dledwards09** [comment] 2020-05-21 17:51
Oh! So how do developers know to check it for viruses? And how do I know when to try to redownload a different version? Thank you so much for your help.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by geonom** [comment] 2020-05-21 17:57
You can find the previous version here:
https://github.com/inkstitch/inkstitch/releases/tag/v1.27.2

With that version, I did not encounter this issue, as far as I remember. Best to scan that as well, though.

**Comment by geonom** [comment] 2020-05-21 20:16
It could be, that our issue is the same issue, described on the installation help page of inkstitch:

https://edutechwiki.unige.ch/en/InkStitch_-_installation#First_time_Ink.2FStitch_base_installation

Under Windows 10, there is a rather generic hint:

> If you use a very high level of Windows Defender protection, you may run into trouble and you may have to white list the extension directory.

> Go to Start > Settings > Updates & Security > Windows Security > Virus & threat protection > Virus & threat protection settings > Add or remove exclusions.

That probably is the same hint - however as it is very unspecific, it is hard to tell.

**Comment by dledwards09** [comment] 2020-05-21 22:28
I think that did it! Thank you so much!

**Closed** 2022-04-10 13:48 UTC
