### ISSUE TITLE
Fedora 40

### ISSUE THREAD

**Issue by yegnal** [inkstitch/inkstitch#2909] opened 2024-05-14 17:25 UTC
Fedora 40 has broken Inkstitch.

Clean install was tried after removing both Inkscape and Inkstitch.  Inkstitch appears in the menu but commands do not run.  

I've tried running with and without the x11 workaround, Inkstitch just not working since installing Fedora 40.

**Comment by kaalleen** [comment] 2024-05-15 05:29
Interesting. Would you mind to try out a recent development version and see if it works on your system?

You can find them here, just pick one from the top of the list: https://github.com/inkstitch/inkstitch/releases

**Comment by yegnal** [comment] 2024-05-15 09:34
I tried; installed all the dependencies found in requirements.txt but couldn't 'make' without errors.       On Wednesday, May 15, 2024 at 01:30:12 AM EDT, Kaalleen ***@***.***> wrote:  
 
 


Interesting. Would you mind to try out a recent development version and see if it works on your system?

You can find them here, just pick one from the top of the list: https://github.com/inkstitch/inkstitch/releases

**Comment by bkmgit** [comment] 2024-05-15 09:55
Could you give the full steps you followed so I can reproduce this.

**Comment by yegnal** [comment] 2024-05-15 10:07
135 | install python3-tomli.noarch                                               | 2024-05-15 05:24 | Install        |    1   
   134 | install python3-flask-cors.noarch                                          | 2024-05-15 05:17 | Install        |    1      133 | install python3-diskcache.noarch                                           | 2024-05-15 05:16 | Install        |    1      132 | install python3-trimesh.noarch                                             | 2024-05-15 05:11 | Install        |  507      131 | install python3-fonttools.x86_64                                           | 2024-05-15 05:09 | Install        |    7      130 | install python3-flask.noarch                                               | 2024-05-15 05:08 | Install        |    4      129 | install python3-jinja2.noarch                                              | 2024-05-15 05:06 | Install        |    1      128 | install python3-appdirs.noarch                                             | 2024-05-15 05:05 | Install        |    1      127 | install python3-shapely.x86_64                                             | 2024-05-15 05:03 | Install        |    1      126 | install python3-networkx.noarch                                            | 2024-05-15 05:02 | Install        |    1      125 | install python3-wxpython4.x86_64 
Downloaded colormathpip install colormath

Inside Inkstitch-main <make>


I'm not the most experienced at installing from source, novice at best actually    On Wednesday, May 15, 2024 at 05:56:20 AM EDT, Benson Muite ***@***.***> wrote:  
 
 


Could you give the full steps you followed so I can reproduce this.

**Comment by kaalleen** [comment] 2024-05-15 18:17
Oh, you want to go manual?
I thought you just wanted to test a packaged version. If so, you can just install development builds just the same way as the latest release.

**Comment by yegnal** [comment] 2024-05-15 18:25
I didn't see a packaged version from that link, rather I went to the code on GitHub.
Honestly would be much easier if there's an early release .rpm you'd like me to test...


Yahoo Mail: Search, Organize, Conquer 
 
  On Wed, May 15, 2024 at 14:17, ***@***.***> wrote:   


Oh, you want to go manual?
I thought you just wanted to test a packaged version. If so, you can just install development builds just the same way as the latest release.

**Comment by kaalleen** [comment] 2024-05-15 19:11
Just click on any of the releases. There is a list of files. rpm is there as well.

**Comment by bkmgit** [comment] 2024-05-16 04:54
Have found the tar.xz method to be more reliable on Fedora. First
install Inkscape from Fedora repositories, then install Inkstitch see
https://inkstitch.org/docs/install-linux/

**Comment by yegnal** [comment] 2024-05-16 09:02
Trying 'Params' & realistic preview:
'Params' error:
Traceback (most recent call last):  File "inkstitch.py", line 29, in <module>  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module  File "lib/extensions/__init__.py", line 30, in <module>  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module  File "lib/extensions/lettering.py", line 13, in <module>  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module  File "wx/__init__.py", line 17, in <module>  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module  File "wx/core.py", line 12, in <module>ImportError: libnsl.so.1: cannot open shared object file: No such file or directory[9614] Failed to execute script 'inkstitch' due to unhandled exception!


Realistic preview doesn't provide anything like the above, just doesn't do anything. 
I also ran using the export GDK_BACKEND=x11 && inkscape method.

My instances of Inkscape and Inkstitch are as clean an install as I know how to do....  
First I removed using dnf package manager.   Then did a < sudo find / -maxdepth 8 -iname "*inkscape*" -exec rm -rf {} \; >Did the same with Inkstitch just to start with a clean slate.
Hope this helps in some meaningful way.  
p.s.  Everything works fine in Linux Mint out of the box.    It's definitely specific to Fedora.  Fedora 39 required the X11 workaround to use 'Params' and Fedora 40 nothing is working.      On Thursday, May 16, 2024 at 12:54:33 AM EDT, Benson Muite ***@***.***> wrote:  
 
 

Have found the tar.xz method to be more reliable on Fedora. First
install Inkscape from Fedora repositories, then install Inkstitch see
https://inkstitch.org/docs/install-linux/

**Comment by rejbasket** [comment] 2024-05-16 11:10
The Fedora distro doesn't install libnsl library by default. Install the missing library:
```shell
sudo dnf install libnsl
```

**Comment by rejbasket** [comment] 2024-05-16 13:24
The missing library hasn’t been an issue with Arch Linux and openSUSE, to the best of my knowledge.

For the issue with Wayland and wxpython can be mitigated by logging in with Gnome on Xorg. At the bottom right hand corner of the login screen, there will be a small gear icon, I think it will appear as you type in your password, choose Gnome on Xorg and the export will not be necessary to run inkstitch.

**Comment by yegnal** [comment] 2024-05-16 13:40
Many open source projects have a donation link, but I couldn't find it on your page..
 If I knew how to code I would contribute that way but I'm of no use in that department..


Yahoo Mail: Search, Organize, Conquer 
 
  On Thu, May 16, 2024 at 9:25, ***@***.***> wrote:   


The missing library hasn’t been an issue with Arch Linux and openSUSE, to the best of my knowledge.

For the issue with Wayland and wxpython can be mitigated by logging in with Gnome on Xorg. At the bottom right hand corner of the login screen, there will be a small gear icon, I think it will appear as you type in your password, choose Gnome on Xorg and the export will not be necessary to run inkstitch.

**Comment by yegnal** [comment] 2024-05-16 14:34
I created a script in $HOME/bin with the x11 workaround, then aliased the command 'inkscape' to it.  Works and is easily escaped.


Yahoo Mail: Search, Organize, Conquer 
 
  On Thu, May 16, 2024 at 9:40, ***@***.***> wrote:   Many open source projects have a donation link, but I couldn't find it on your page..
 If I knew how to code I would contribute that way but I'm of no use in that department..


Yahoo Mail: Search, Organize, Conquer 
 
  On Thu, May 16, 2024 at 9:25, ***@***.***> wrote:   


The missing library hasn’t been an issue with Arch Linux and openSUSE, to the best of my knowledge.

For the issue with Wayland and wxpython can be mitigated by logging in with Gnome on Xorg. At the bottom right hand corner of the login screen, there will be a small gear icon, I think it will appear as you type in your password, choose Gnome on Xorg and the export will not be necessary to run inkstitch.

**Comment by kaalleen** [comment] 2024-05-19 17:32
Yes, we do not have a donation link yet, but thanks for considering!
I'll close the issue as it seems to be solved. Please complain if I am wrong :)

**Closed by kaalleen** 2024-05-19 17:32 UTC
