### ISSUE TITLE
most windows do not open on Mac with M1/Monterey 12.6

### ISSUE THREAD

**Issue by schepaqua** [inkstitch/inkstitch#1833] opened 2022-09-25 08:02 UTC
Some windows open, like _Settings_ or _cutwork_. Others do not like _parameters_ or _Simulator/realistic preview_

**Comment by rejbasket** [comment] 2022-09-26 11:46
This issue is caused by not having Rosetta 2 installed. Ink/Stitch is compiled for Intel processors, Apple provides software to allow apps to run on Apple Silicon. Run this command in Terminal:

softwareupdate --install-rosetta

After the installation Ink/Stitch should work.

**Comment by schepaqua** [comment] 2022-09-26 12:24
Now it works, thank you so much! (I am new to Mac and wasn't aware of this)

**Comment by erikaleonard** [comment] 2022-09-28 04:58
Hey, 
I have done all the updates but inkstitch is not opening my svg fonts. I am trying to open them to convert to gyph but it won’t open the file. I just get the spinning wheel for almost an hour before I force quite.

**Comment by kaalleen** [comment] 2022-10-02 08:41
Just to verify: did you follow this https://inkstitch.org/tutorials/font-creation/#1-create-a-file-with-glyph-layers and you have problems with step 7?

**Comment by erikaleonard** [comment] 2022-10-02 17:35
I did follow this, and I have successfully digitized glyphs. The problem I am having is that inkstitch isn’t opening the fonts files anymore. It won’t open worked I’ve completed and saved or the original svg font file that I created in font forge. 
Erika Leonard 
970-200-3098

**Comment by kaalleen** [comment] 2022-10-02 17:59
It's difficult to say what is happening without the files. Would you mind to send your font files so we can have a look at them?

**Comment by kaalleen** [comment] 2023-02-25 13:55
No respond. Closing. Please open a new issue if you are still having problems.

**Closed by kaalleen** 2023-02-25 13:55 UTC
