### ISSUE TITLE
AssertionError: too many color changes

### ISSUE THREAD

**Issue by krc0411** [inkstitch/inkstitch#2740] opened 2024-02-24 02:39 UTC
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: 3.0.1 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 231, in run
  File "lib/extensions/output.py", line 65, in effect
  File "lib/output.py", line 109, in write_embroidery_file
  File "pyembroidery/EmbPattern.py", line 1727, in static_write
  File "pyembroidery/EmbPattern.py", line 1644, in write_embroidery
  File "pyembroidery/PesWriter.py", line 50, in write
  File "pyembroidery/PesWriter.py", line 110, in write_version_1
  File "pyembroidery/PecWriter.py", line 40, in write_pec
  File "pyembroidery/PecWriter.py", line 64, in write_pec_header
AssertionError: too many color changes, (261) out of bounds (0, 255)

**Comment by krc0411** [comment] 2024-02-24 02:42
<img width="478" alt="Screen Shot 2024-02-23 at 9 42 14 PM" src="https://github.com/inkstitch/inkstitch/assets/161098384/d17c9976-519b-4230-a12b-d4dd6823fc43">

**Comment by kaalleen** [comment] 2024-02-24 06:26
This means you've got a lot of color changes in your file. You won't like to sit at your machine and change colors 261 times, For embroidery you will need to simplify your design as much as possible.

**Comment by krc0411** [comment] 2024-02-24 06:57
thank you, but the design is all black so that doesn't make sense

**Comment by kaalleen** [comment] 2024-02-24 08:45
Can you post your design? Or double check if you haven't any stroke color set to your fill objects...

**Comment by kaalleen** [comment] 2024-03-03 19:18
Closing as it is a duplicate of #2574

**Closed by kaalleen** 2024-03-03 19:18 UTC
