### ISSUE TITLE
Simulator is showing artifacts after window scaling

### ISSUE THREAD

**Issue by bianchifan** [inkstitch/inkstitch#2904] opened 2024-05-13 13:08 UTC
Since "electron" seems to be wiped out I noticed a couple of probs with the all actual dev versions, I reported these probs a couple of days ago on a german forum.

Systems:
Dell Studio XPS 1340 with Linux Mint 21.3
Dell XPS15 9550 with automatically downgraded Windows 11(from my XPS 13) -> Windows 10 due to CPU restrictions
All reported problems occured on both systems.
My Dell XPS 13 does not work any more ..(issue #2867)

1. Weired rendering results when scaling the simulator window
2. Missing switch for realistic view 
3. Missing switch for rendering jumps
BTw.. TNX for possibility of changing background :)

![Unbenannt2](https://github.com/inkstitch/inkstitch/assets/17491743/3f5da23d-02b4-4665-95eb-a65ab5484320)

4. Unsmooth countour underlay, leaving the object's shape in narrow curves
 
![Ornament 30°](https://github.com/inkstitch/inkstitch/assets/17491743/d742ab1c-c411-4e7f-94c4-85886aacfa5a)
![Simulator-fix](https://github.com/inkstitch/inkstitch/assets/17491743/1d2ebea9-f779-40fe-8712-acc95d1c476e)

Last dev with correct underlay George Steel's random enhancement
![GeorgeSteel-random](https://github.com/inkstitch/inkstitch/assets/17491743/947ab571-00dd-4e45-9206-3385fa935f8d)

**Comment by kaalleen** [comment] 2024-05-13 15:00
> 1. Weired rendering results when scaling the simulator window

Ok, that's weird. Does it update correctly with the next animated stitch?

> 2. Missing switch for realistic view

There is no realistic view mode in the simulator anymore. It can now be found in the stitch plan preview.

> 3. Missing switch for rendering jumps

I can see it in your images. It's the frog.

> 5. Unsmooth countour underlay, leaving the object's shape in narrow curves

As you found out already, that's fixed :)

**Comment by kaalleen** [comment] 2024-05-13 15:03
Btw. I can't reproduce the artifact issue. That would make it hard for me to fix them.
Will test on Windows when I get the chance.

**Comment by bianchifan** [comment] 2024-05-13 18:02
> Btw. I can't reproduce the artifact issue. 

I couldn't reproduce it just now on my hot chiliiiied Mint system with meeting version

**Comment by kaalleen** [comment] 2024-05-15 05:16
> I couldn't reproduce it just now on my hot chiliiiied Mint system with meeting version

Ok, then I'll close the issue. Discussion was ongoing in an other thread anyway and this one was boiled down just to the simulator artifacts. Ongoing discussion: #2905

You can't know, but I have a favor to ask to make life easier for us. When you find several issues, it would be helpful if you could also separate them into several issue reports. This is some sort of bug tracker and it is hard to keep track of the single issues if there are many just in one thread.

**Comment by kaalleen** [comment] 2024-05-18 17:33
Simulator artifacts after scaling seems to be a problem (although I cannot reproduce on my computer).

**Closed** 2024-06-07 08:33 UTC
