### ISSUE TITLE
new issue

### ISSUE THREAD

**Issue by jawsfree** [inkstitch/inkstitch#1453] opened 2021-11-22 16:34 UTC
use8530: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "lib\elements\auto_fill.py", line 223, in to_patches
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 63, in auto_fill
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 144, in build_fill_stitch_graph
  File "lib\stitches\fill.py", line 146, in intersect_region_with_grating
  File "shapely\geometry\base.py", line 676, in intersection
  File "shapely\topology.py", line 70, in __call__
  File "shapely\topology.py", line 35, in _check_topology
shapely.errors.TopologicalError: The operation 'GEOSIntersection_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.multipolygon.MultiPolygon object at 0x0737D130>

shapely.geos - ERROR - TopologyException: Input geom 1 is invalid: Self-intersection at or near point -57.166347237686338 838.51731846382449 at -57.166347237686338 838.51731846382449
shapely.geos - INFO - Self-intersection at or near point -57.166347237686338 838.51731846382449

**Comment by kaalleen** [comment] 2021-11-23 19:36
Interesting. Would you mind to send the svg file which is causing this? You can either send it here or to send-us-files@inkstitch.org

**Comment by kaalleen** [comment] 2021-12-08 09:15
Duplicate of #1449

**Closed by kaalleen** 2021-12-08 09:15 UTC
