### ISSUE TITLE
ink stitck keeps freezing when entering params

### ISSUE THREAD

**Issue by TJDevelopeer** [inkstitch/inkstitch#1000] opened 2021-01-28 03:32 UTC
hello this is my first post here im posting about inkscape freezing  when i enter params section it dosent crash but it freezes~~
it outputs this
Exception AttributeError: "'NoneType' object has no attribute 'GEOSSTRtree_destroy'" in <bound method STRtree.__del__ of <shapely.strtree.STRtree instance at 0x0CBCC508>> ignored
~~and the gui for the stitching dosent show up  after i close the params tab the program goes back to normal it also dosent let me see the interactive stitching so... basically i cant do anything
![stitchcapture](https://user-images.githubusercontent.com/52419236/106086117-20dd0680-60e7-11eb-9b91-b734c0acddf1.PNG)

**Comment by kaalleen** [comment] 2021-01-29 17:15
Nice catch. Thank you for informing us about your trouble. Would it be possible to send your svg file to us?

**Comment by kaalleen** [comment] 2021-04-25 10:54
Duplicate of #578

**Closed by kaalleen** 2021-04-25 10:54 UTC
