### ISSUE TITLE
Fill: ZeroDivisionError

### ISSUE THREAD

**Issue by smataitsane** [inkstitch/inkstitch#1783] opened 2022-08-12 10:06 UTC
![Nupsawlogo](https://user-images.githubusercontent.com/110632362/184332746-dc223a23-0c64-40b8-921e-5369763487f4.svg)
![Nupsawpta](https://user-images.githubusercontent.com/110632362/184332860-b27c5aff-b2b8-44c8-bc80-93448a8e8192.jpg)
![image](https://user-images.githubusercontent.com/110632362/184331838-9797f6b4-d4b1-4fa4-9088-95dea805be9d.png)

**Comment by smataitsane** [comment] 2022-08-12 10:08
Please help me with getting this logo on a Bernina Artista 200 Embroidery Machine

**Comment by tyrosinase** [comment] 2022-08-12 13:22
This looks like the same bug as https://github.com/inkstitch/inkstitch/issues/1764, which as of that report hadn't been duplicated by the devs... there are instructions there on how to send them a file with the problem.

It's probably caused by too-tiny-to-stitch paths, though, so after you send them the current file, you can delete some of the speckles and it'll probably solve the problem.

For overall digitizing advice, read through the tutorial at https://silverseams.com/tutorials/digitizing-with-ink-stitch/index.html .

You'll probably want to substitute some of Ink/Stitch's built-in lettering, since that'll save you a lot of work. Ink/Stitch doesn't fit text to curves (yet?) but it's relatively easy to do manually: https://silverseams.com/tutorials/text-on-a-curve-with-ink-stitch/

**Comment by kaalleen** [comment] 2022-10-02 09:01
Closing in favor of #1829

**Closed by kaalleen** 2022-10-02 09:01 UTC
