### ISSUE TITLE
Inkstitch Error Code

### ISSUE THREAD

**Issue by NaeNicole** [inkstitch/inkstitch#1160] opened 2021-04-22 12:26 UTC
I've reinstalled/installed Inkscape and inkstitch several times and I keep getting this code:
Exception AttributeError: "'NoneType' object has no attribute 'GEOSSTRtree_destroy'" in <bound method STRtree.__del__ of <shapely.strtree.STRtree instance at 0x0CE18670>> ignored

**Comment by kaalleen** [comment] 2021-04-25 10:57
Thank you for reporting your issue. At the moment it doesn't look like we can do much about it, since it is caused by an external library we use. Have a look at this issue here #578, where it has been discussed.

**Comment by kaalleen** [comment] 2021-05-04 17:04
Closing (duplicate)

Please reopen or discuss in the mentioned issue if you have questions.

**Closed by kaalleen** 2021-05-04 17:04 UTC
