### ISSUE TITLE
Trying to resize a PES file

### ISSUE THREAD

**Issue by BrooksIsCrazy** [inkstitch/inkstitch#2022] opened 2023-01-20 19:00 UTC
I'm a total newbie. I tried to reduce it from a 4x4 hoop to a 2.5x3.5 hoop. I used CTRL plus grabbing a corner to drag it down to the size I wanted and then when I did save as I got this:

path2028: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 562, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 611, in do_auto_fill
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 75, in auto_fill
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 630, in path_to_stitches
  File "lib\stitches\auto_fill.py", line 591, in travel
  File "networkx\algorithms\shortest_paths\generic.py", line 167, in shortest_path
  File "networkx\algorithms\shortest_paths\weighted.py", line 2377, in bidirectional_dijkstra
networkx.exception.NetworkXNoPath: No path between (120.51183409763945, 89.76377952755905) and (120.99809471640293, 88.87087950325315).

**Comment by kaalleen** [comment] 2023-01-23 20:05
Would it be possible for you to send us your svg file (or parts of it) so we can try to reproduce the error?

**Comment by kaalleen** [comment] 2023-01-23 20:07
Resizing embroidery files is somewhat difficult though. If you do not rework the stitch placements, it is very likely that you stitcches will come out too small and your embroidery machine may not like that.

**Comment by kaalleen** [comment] 2023-03-04 13:51
Duplicate of #2056

**Closed by kaalleen** 2023-03-04 13:51 UTC
