### ISSUE TITLE
error when trying to get stitch preview as well as save file as pes

### ISSUE THREAD

**Issue by Lenise22** [inkstitch/inkstitch#2047] opened 2023-02-02 02:44 UTC
Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\extensions\base.py", line 200, in elements_to_stitch_groups
  File "lib\elements\element.py", line 329, in embroider
  File "lib\elements\element.py", line 387, in validate
  File "lib\elements\fill_stitch.py", line 321, in validation_errors
  File "lib\elements\fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'

**Comment by Lenise22** [comment] 2023-02-02 04:11
when i go to paths then combine it solves all the issues however, i lose the colors in my file 
![PRIVACY CLUB EARTH DAY (1)](https://user-images.githubusercontent.com/124225238/216229794-113437d9-71df-42ae-872b-529bdbb16d5a.svg)

**Comment by bianchifan** [comment] 2023-02-07 12:03
No probs here with your SVG..
I put PES and dst into the zip below.

[216229794-113437d9-71df-42ae-872b-529bdbb16d5a.zip](https://github.com/inkstitch/inkstitch/files/10674779/216229794-113437d9-71df-42ae-872b-529bdbb16d5a.zip)

Reopend PES looks like this
![Bildschirmfoto vom 2023-02-07 12-49-10](https://user-images.githubusercontent.com/17491743/217239743-77c4d1b0-5e81-41f5-beb2-fa9e6f826b4f.jpg)

**Comment by Lenise22** [comment] 2023-02-11 06:47
Thank you!

**Comment by kaalleen** [comment] 2023-03-04 14:29
Duplicate of #1742

**Closed by kaalleen** 2023-03-04 14:29 UTC
