### ISSUE TITLE
Inkstitch Auto satin error

### ISSUE THREAD

**Issue by caye85** [inkstitch/inkstitch#1173] opened 2021-04-29 11:04 UTC
Not quite sure whether I am running into a directory issue on Win8, but I do not have a D drive installed.
Errors occure when running auto satin on a closed path.

  File "D:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "D:\a\inkstitch\inkstitch\inkscape\share\extensions\inkex.py", line 283, in affect
  File "D:\a\inkstitch\inkstitch\lib\extensions\auto_satin.py", line 54, in effect
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_satin.py", line 318, in auto_satin
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_satin.py", line 393, in get_starting_and_ending_nodes
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_satin.py", line 407, in find_node
ValueError: min() arg is an empty sequence

**Comment by kaalleen** [comment] 2021-04-29 17:43
This is caused by very small fill shapes. Try to remove them from your document with Extensions > Ink/Stitch > Troubleshoot > Cleanup document ...
Thank you for reporting this bug. It will be fixed with the next release.

**Comment by kaalleen** [comment] 2021-04-29 20:32
Sorry, I've been a little bit fast with this one. I confused it with an error message which we have seen a lot lately.
Would it be possible for you to send us the svg file which is causing the error?

**Comment by caye85** [comment] 2021-04-29 20:45
Here's my file, also I ran Cleanup document, with no difference in the resulting error message.
[Kopie.zip](https://github.com/inkstitch/inkstitch/files/6401544/Kopie.zip)

**Comment by kaalleen** [comment] 2021-05-01 09:22
Thank you for sharing your file. Sorry about the cleanup thing. I have answered the other error message so often, that I didn't look carefully into yours. But yours is an other cause.

I am wondering. In your file I cannot seem to find a satin column. Is the file in it's current state causing the error on your computer?

**Comment by caye85** [comment] 2021-05-01 17:31
Yep that is the exact file :(

**Comment by tyrosinase** [comment] 2021-05-01 17:42
I think the problem is that you're expecting auto-route satin to do a lot more than it can. It's not going to convert a letter outline to satin stitch all by itself.

With that said, I get (on Linux):

Ink/Stitch experienced an unexpected error.
If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below: 

Traceback (most recent call last):
  File "/home/runner/work/inkstitch/inkstitch/inkstitch.py", line 44, in <module>
  File "/home/runner/work/inkstitch/inkstitch/inkscape/share/extensions/inkex.py", line 283, in affect
  File "/home/runner/work/inkstitch/inkstitch/lib/extensions/auto_satin.py", line 54, in effect
  File "/home/runner/work/inkstitch/inkstitch/lib/stitches/auto_satin.py", line 316, in auto_satin
  File "/home/runner/work/inkstitch/inkstitch/lib/stitches/auto_satin.py", line 456, in add_jumps
  File "/home/runner/.local/lib/python2.7/site-packages/networkx/algorithms/connectivity/edge_augmentation.py", line 264, in k_edge_augmentation
NetworkXUnfeasible: impossible to 1 connect in graph with less than 2 nodes

And I suspect Ink/Stitch should probably respond with something more graceful, on the order of "that's not a satin stitch, y'all."

**Comment by kaalleen** [comment] 2021-05-01 17:59
Oh, ha, thanks @tyrosinase I don't know where I lost my head lately :D 

> And I suspect Ink/Stitch should probably respond with something more graceful, on the order of "that's not a satin stitch, y'all."

This has been taken care for already. Ink/Stitch now refuses to try making satin columns out of fill stitches.

@caye85 using satin columns for letters is a good idea, but Ink/Stitch cannot convert a fill area into satin columns. You would need to split them up and generate the satin columns manually. Fonts are not an easy starting point though. The next Ink/Stitch version will come with a lot more fonts than the old one. You could have a look at these fonts on how they are build etc. and learn from them. You won't need to wait long for the next release anymore.

**Comment by caye85** [comment] 2021-05-02 10:47
Thanks a lot! The official tutorial I was following is not a 100% clear on that matter. As a beginner, I really thought the auto-route satin function would to the job of creating the satin columns for me. 
[https://inkstitch.org/tutorials/font-creation/#2-digitize-the-glyphs](url)
Looking forward to the next release then!

**Comment by kaalleen** [comment] 2021-05-02 11:23
Oh I see. Thanks for the hint! I'll have a look into for improvement.
This document is already set for the new version too. So do not wonder if there are options mentioned that are not available yet.

**Closed** 2021-05-15 12:07 UTC
