### ISSUE TITLE
Initial install not working... need a little help

### ISSUE THREAD

**Issue by kwiecki** [inkstitch/inkstitch#577] opened 2019-11-14 03:49 UTC
I installed for the first time and think I did everything correctly.
Below is the error I received when trying Params after creating a circle and changing object to path.  Also, after I receive the error, a few seconds later, I see a message of 'params working, please wait', but nothing happens.

I have Inkscape .92
Thanks

Inkscape has received additional data from the script executed.  The script did not return an error, but this may indicate the results will not be as expected.

Tried to launch: inkstitch\bin\inkstitch
Arguments: ['inkstitch\\bin\\inkstitch', '--id=path817', '--extension=params', 'C:\\Users\\myname\\AppData\\Local\\Temp\\ink_ext_XXXXXX.svgXWNVA0']
Debugging information:

Traceback (most recent call last):
  File "inkstitch.py", line 35, in <module>
    extension = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Program Files\Inkscape\lib\python2.7/subprocess.py", line 325, in __init__
    errread, errwrite)
  File "C:\Program Files\Inkscape\lib\python2.7/subprocess.py", line 575, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by mossypy** [comment] 2019-11-19 12:17
I get the same problem. I dont have much time to look into what might be casuing it. I am using Inkscape 0.92.3

**Comment by lexelby** [comment] 2019-11-20 00:38
Hi, folks.  From what we can tell, this problem is most commonly caused by your antivirus deleting inkstitch.exe.  Maybe you can add an exception for it?

**Comment by tyrosinase** [comment] 2019-11-20 15:37
On 11/19/19 7:38 PM, Lex Neva wrote:
>
> Hi, folks. From what we can tell, this problem is most commonly caused
> by your antivirus deleting inkstitch.exe. Maybe you can add an
> exception for it?
>

(or, if you're using something beyond Windows Defender... just don't.
MalwareBytes, if you *really* feel like you need something more, but if
you're also keeping your browser up to date, running uBlock Origin or
Privacy Badger and not opening random email attachments you probably don't)

(if Windows Defender or MalwareBytes is deleting inkstitch we need to
look at what inkstitch is doing though)

**Comment by lexelby** [comment] 2019-11-20 16:26
I get the impression that lots of projects using PyInstaller run into this problem.

**Comment by kwiecki** [comment] 2019-11-20 17:50
I was poking around some of the Inkscape files and found a file named extension errors. There’s 2 that stand out to me. One says I need to install Dia.  It also says pstoedit needs to be installed.  Could this be related to my inkstitch problem?  Thanks

**Comment by lexelby** [comment] 2019-11-21 20:13
No, I don't think that's related.  Those messages are probably coming from extensions that are bundled with Inkscape.  Ink/Stitch doesn't use Dia or pstoedit.

**Comment by kaalleen** [comment] 2020-04-10 07:49
Duplicate of #613 
Closing the issue now. Please report further issues on this matter there.

**Closed by kaalleen** 2020-04-10 07:49 UTC
