### ISSUE TITLE
unknown error in inkstitch

### ISSUE THREAD

**Issue by kabbuhl** [inkstitch/inkstitch#1268] opened 2021-07-07 01:43 UTC
this is the error msg i get, just started using this program, all im trying to do i change the file type from jpeg to jef, for my sewing machine
Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\stitch_plan\stitch_plan.py", line 26, in patches_to_stitch_plan
IndexError: list index out of range

**Comment by tyrosinase** [comment] 2021-07-07 03:42
jpeg to jef is a complicated path.

Ink/Stitch isn't really capable of just producing an embroidery design out of a bitmap. (Really, no embroidery program is, though some will make a stab at it.)

This blog entry explains how to convert a font, some of the same things apply other than you'll want to start with Inkscape's Trace Bitmap instead of converting a font to objects. And it really doesn't go into what you would want to do with large fill areas (border them with satin, etc.) so I guess I should write up another post on that sort of thing. Unless someone else has, which I hope they have because I've only been doing this a couple of years. https://silverseams.com/2020/03/monogramming-without-a-font/

**Comment by kaalleen** [comment] 2021-07-19 07:02
Duplicate of #1199

**Closed by kaalleen** 2021-07-19 07:02 UTC
