### ISSUE TITLE
auto_fill: ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by karovrdg** [inkstitch/inkstitch#1095] opened 2021-03-21 17:54 UTC
i can´t save it in PES and this come out in the screen:

path202: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 212, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 149, in build_fill_stitch_graph
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

**Comment by MK-12-20MM** [comment] 2021-03-21 21:06
@karovrdg 

You might want to look at this issue here [auto_fill: ValueError: min() arg is an empty sequence #1092](https://github.com/inkstitch/inkstitch/issues/1092)

I think this may help since you are at the point of exporting a design to PES.

**Comment by kaalleen** [comment] 2021-03-28 09:04
Duplicate of #734

**Closed by kaalleen** 2021-03-28 09:04 UTC
