### ISSUE TITLE
HELP - "Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch."

### ISSUE THREAD

**Issue by chennalb** [inkstitch/inkstitch#2017] opened 2023-01-16 22:00 UTC
Ink/Stitch Version: v2.2.0 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 231, in run
  File "lib/extensions/output.py", line 56, in effect
  File "lib/extensions/base.py", line 200, in elements_to_stitch_groups
  File "lib/elements/element.py", line 329, in embroider
  File "lib/elements/element.py", line 387, in validate
  File "lib/elements/fill_stitch.py", line 321, in validation_errors
  File "lib/elements/fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'

![DST](https://user-images.githubusercontent.com/122836063/212771798-703ccb25-9405-4e24-b77e-854abaefe59d.svg)

**Comment by kaalleen** [comment] 2023-01-19 16:18
The holes in the letters are separate elements. You will want to combine them with the letter itself. But what is causing problems in your document are the little tiny objects which are not good for embroidery. Since they are so many, your best option is to select everything you want to keep and then reverse the selection and delete everything in the reversed selection.
Then finally, plan the stitch path with start and stop commands and adapt your params as you like.

Her an example (with default embroidery settings).
![2017_edited](https://user-images.githubusercontent.com/36401965/213495181-ef41dde6-887e-44ec-98ae-99fbec3f0306.svg)

**Comment by kaalleen** [comment] 2023-02-25 13:27
Duplicate of #1742

**Closed by kaalleen** 2023-02-25 13:27 UTC
