### ISSUE TITLE
Auto_fill: ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by musicfreak1** [inkstitch/inkstitch#988] opened 2021-01-23 04:45 UTC
I'm having issues saving my design, it seems to be working in both the embroidery and prarams veiws but won't save. Comes with this message whole.

path30: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 225, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 149, in build_fill_stitch_graph
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

**Comment by kaalleen** [comment] 2021-01-24 19:28
Could you check your document if it contains very small fill elements? This bug seems to be triggert by those. You can try to clean up your document with the function found under Extensions > Ink/Stitch > Troubleshoot > Cleanup document ...

Sorry for your troubles. We hope this will not happen anymore in the very next release.

**Comment by kaalleen** [comment] 2021-02-06 17:05
Duplicate of #734

**Closed by kaalleen** 2021-02-06 17:05 UTC
