### ISSUE TITLE
autofill! ???

### ISSUE THREAD

**Issue by bburke1234** [inkstitch/inkstitch#2204] opened 2023-04-07 19:23 UTC
Ink/Stitch Version: v2.2.0 (osx)

Traceback (most recent call last):
  File "lib/elements/fill_stitch.py", line 556, in to_stitch_groups
  File "lib/elements/fill_stitch.py", line 590, in do_underlay
  File "lib/debug.py", line 133, in decorated
  File "lib/stitches/auto_fill.py", line 62, in auto_fill
  File "lib/stitches/fill.py", line 163, in intersect_region_with_grating
ZeroDivisionError: float division by zero

**Comment by kaalleen** [comment] 2023-04-08 18:31
Try to avoid thin areas in stitch direction. Also remove small elements from your document. In the current Ink/Stitch version they will cause trouble. We are going to improve with the next release, I promise.

**Comment by kaalleen** [comment] 2023-05-15 21:14
Duplicate of #1829

**Closed** 2023-05-15 21:23 UTC
