### ISSUE TITLE
auto_fill: ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by CMipe** [inkstitch/inkstitch#821] opened 2020-09-14 22:19 UTC
Convert a picture, tried to run "Simulate", only waiting and then:

path1994_6: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 212, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 149, in build_fill_stitch_graph
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\SocketServer.py", line 599, in process_request_thread
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\SocketServer.py", line 334, in finish_request
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\SocketServer.py", line 655, in __init__
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\werkzeug\serving.py", line 329, in handle
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\BaseHTTPServer.py", line 340, in handle
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\werkzeug\serving.py", line 364, in handle_one_request
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\werkzeug\serving.py", line 306, in run_wsgi
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\werkzeug\serving.py", line 294, in execute
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\flask\app.py", line 1997, in __call__
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\flask\app.py", line 1982, in wsgi_app
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\flask\app.py", line 1598, in dispatch_request
  File "D:\a\inkstitch\inkstitch\lib\api\stitch_plan.py", line 14, in get_stitch_plan
  File "D:\a\inkstitch\inkstitch\lib\extensions\base.py", line 194, in elements_to_patches
  File "D:\a\inkstitch\inkstitch\lib\elements\element.py", line 329, in embroider
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 240, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\elements\element.py", line 353, in fatal
SystemExit: 1

**Comment by kaalleen** [comment] 2021-03-06 13:15
Thanks for reporting your issue. It looks like you have very small fill elments in your document. At the moment Ink/Stitch is having some issues with those (it will be fixed soon). Until then, please try to remove these little fragments. Ink/Stitch has a tool to help you with it: Extensions > Ink/Stitch > Troubleshoot > Cleanup document ...

**Comment by kaalleen** [comment] 2021-03-06 13:17
This issue is a duplicate of #734 . That's why I am closing this issue now. Please reopen, if you see this anwer does not satisfy your needs.

**Closed by kaalleen** 2021-03-06 13:17 UTC
