### ISSUE TITLE
fill: ValueError: need more than 0 values to unpack

### ISSUE THREAD

**Issue by KTYRELL88** [inkstitch/inkstitch#1019] opened 2021-02-05 03:24 UTC
path1079: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/auto_fill.py", line 212, in to_patches
  File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 55, in auto_fill
  File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 133, in build_fill_stitch_graph
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/fill.py", line 91, in intersect_region_with_grating
ValueError: need more than 0 values to unpack

**Comment by kaalleen** [comment] 2021-02-06 16:42
Thanks for reporting your issue. Would it be possible for you to send us your svg file? It would be interesting to see where this bug is coming from.

**Comment by kaalleen** [comment] 2021-02-09 13:38
This issue could be caused by a parameter value (expand or underlay inset). It can shrink the shape until it is empty.
I hope it is fixed in the next release. It would be great to have your feedback if that is true.

Check out the pre-release here: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-inkscape1.0
Pick the osx version and your prefered language. Install as you are used to install the official releases.

You don't have to worry about unwrapping it directly into the extensions folder anymore. It will be also fine inside a subdirectory of that folder.

**Comment by KTYRELL88** [comment] 2021-02-09 13:54
Good Morning,

Thank you for following up with me. I actually figured out my issue by
playing around with the other satin column settings.

Best,

**Comment by kaalleen** [comment] 2021-02-09 13:56
Satin columns? This issue looks like being about a fill shape?
Did you turn it into a satin column?

**Comment by KTYRELL88** [comment] 2021-02-09 14:08
Yes.

**Comment by kaalleen** [comment] 2021-04-04 08:30
See #1071

**Closed by kaalleen** 2021-04-04 08:30 UTC
