### ISSUE TITLE
auto_fill: ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by mxwoodson** [inkstitch/inkstitch#934] opened 2020-12-25 02:50 UTC
I keep on receiving an error os "Inkscape received additional data from the script excused. The script did not return an error, but this may indicate the results will not be as expected." "Error writing to ./city.jpg.vp3: read-only file system" 
 
When I'm in Inkscape it will not allow me to go to "Extension; Ink/Stitch; Visualise and Export;  then Embroider." I get the error above. What am I doing wrong?

**Comment by mxwoodson** [comment] 2020-12-25 03:41
ath194: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/auto_fill.py", line 212, in to_patches
  File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 55, in auto_fill
  File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 149, in build_fill_stitch_graph
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

**Comment by kaalleen** [comment] 2021-02-09 10:57
Hey there. Thank you for reporting your issues and sorry for the late reply. When time has been short I was only looking for issues with no answer, so I must have missed this issue here.

To 1: Try to save your file not with the embroider function but through file > save a copy...
This somehow works much better than the embroider function (which will be removed soon).

To2: This error is caused by very small fill objects. Also an error which we try to avoid in our next release. For now you will have to remove these objects. Best tool for this matter is the cleanup document ... function which you can find under Extensions > Ink/Stitch > Troubleshoot > Cleanup document...

**Comment by mxwoodson** [comment] 2021-02-09 13:13
Thank you! You mention you are removing the embroidery function, is it being replaced with a better version.

Uvonne

**Comment by kaalleen** [comment] 2021-02-09 13:18
Yes, we will only rely on the `File > Save a copy ...` method to export embroidery files.

**Comment by tyrosinase** [comment] 2021-02-14 03:21
On 2/9/21 8:18 AM, Kaalleen wrote:
>
> Yes, we will only rely on the |File > Save a copy ...| method to 
> export embroidery files.
>
I wanna go on record as kinda hating this idea. Because I am 
connnnnstantly bouncing back and forth between exporting the PES, trying 
it out, making some tweaks, and changing the SVG.

**Comment by mxwoodson** [comment] 2021-02-14 14:28
I just started using the embroidery feature and I love it because you can jump back and forth in the project. I wish you could leave it on there.

**Comment by kaalleen** [comment] 2021-02-15 17:07
What exactly would you miss about the embroider function. The option to save the backup files?

**Comment by tyrosinase** [comment] 2021-02-15 17:31
Yep! I am constantly saving *both* the embroidery file and the SVG, and while it's a little more difficult these days to get to the embroidery function (it's a menu deeper than it used to be), it's very easy to ctrl-s to save the SVG periodically.

Maybe my workflow is just weird (I mean, I _know_ I don't use my embroidery machine like normal people do) but I really use both functions a lot, and it's a pain in the neck to keep doing `Save As...` every time.

**Comment by kaalleen** [comment] 2021-02-15 20:05
Oh, in that case I would like to give you an alternative. When you use `save a copy ...` (Shift+Ctrl+Alt+S) you can save it as your embroidery file and use Ctrl+S to save the svg file. It will remember your embroidery file format in the save a copy dialog. You can even change the keyboard shortcut to be a bit easier to access. This workflow wouldn't take you longer than your old one.

**Comment by mxwoodson** [comment] 2021-02-15 22:45
I’m new to using this program but the embroidery function allowed me to see how it would look after it’s was done and I could save it as a VP3 file. I haven’t worked with it enough to tell you a lot it details but I was starting to get use to the program and now it’s changing. I would like more videos on it to see it’s potential.

**Comment by mxwoodson** [comment] 2021-02-15 22:59
I don’t use it everyday because it’s a hobby for me but if I could play around with the program everyday I would know more about it.  Do you know know of any videos that could show me how to use the program more efficiently?

**Comment by mxwoodson** [comment] 2021-02-15 23:00
Thank you for the tip!

**Comment by tyrosinase** [comment] 2021-02-16 03:04
On 2/15/21 3:06 PM, Kaalleen wrote:
>
> Oh, in that case I would like to give you an alternative. When you use 
> |save a copy ...| (Shift+Ctrl+Alt+S) you can save it as your 
> embroidery file and use Ctrl+S to save the svg file. It will remember 
> your embroidery file format in the save a copy dialog. You can even 
> change the keyboard shortcut to be a bit easier to access. This 
> workflow wouldn't take you longer than your old one.
>

Oh hmm, that would probably work. Okay, carry on.

**Comment by kaalleen** [comment] 2021-03-06 13:07
@mxwoodson We have a YouTube channel. The videos are a bit old by now, but still helpful https://m.youtube.com/channel/UCJCDCFuT_xQoI55e10HRiRw

But there are more and more videos an YouTube which you can find searching for Ink/Stitch on YouTube.

I will close this issue now (as a duplicate of #734). Please reopen, if this is still nedded.

**Closed by kaalleen** 2021-03-06 13:07 UTC
