### ISSUE TITLE
.svg file not able to save as embroidery file (neither .vp3 nor .pes)

### ISSUE THREAD

**Issue by boundtoliberty** [inkstitch/inkstitch#2091] opened 2023-02-24 23:44 UTC
Anybody else with this issue when "save a copy" - try to save the .svg as .vp3 ?

Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\extensions\base.py", line 200, in elements_to_stitch_groups
  File "lib\elements\element.py", line 329, in embroider
  File "lib\elements\element.py", line 387, in validate
  File "lib\elements\fill_stitch.py", line 321, in validation_errors
  File "lib\elements\fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'

**Comment by kaalleen** [comment] 2023-02-25 12:30
Thank you for your error report. Search for small elements in your svg document and remove them. This should fix your problem.

**Comment by kaalleen** [comment] 2023-02-25 12:46
Duplicate of #1742

**Closed by kaalleen** 2023-02-25 12:46 UTC
