### ISSUE TITLE
Proposal: electron

### ISSUE THREAD

**Issue by lexelby** [inkstitch/inkstitch#426] opened 2019-04-04 00:06 UTC
After bashing my brain against yet another complicated wxpython incantation, I found myself thinking again: maybe there's a better way to do a cross-platform GUI for Ink/Stitch?

And it hit me: we can *use [Electron](https://electronjs.org/)*.  The idea is that we'd use Python as an API server for the client-side JavaScript (just as we do for the Print PDF feature).  Instead of opening in the user's default browser, we would bundle our own in the form of Electron, which packages Chromium under the hood.  We would do this for _all_ GUIs, not just Print PDF.

Here's a tutorial explaining how this kind of thing is done: https://www.fyears.org/2017/02/electron-as-gui-of-python-apps-updated.html

*Advantages:*
  * We could use the latest web technologies and take greater advantage of @kaalleen's experience with JavaScript.
  * Our GUIs will probably look a ton better judging by @kaalleen's awesome work on Print PDF ;)
  * We may be able to attract more developers to work on the UI since the code will be much more familiar.
  * We can target a single version of a single browser and avoid Firefox compatibility issues.
  * Native looking GUI windows.
  * No need to pop up that message about "go check your browser".  The window will pop up right alongside Ink/Stitch.
  * The Simulator will be vastly simplified: we can just toggle the CSS `display` property on each stitch in turn to animate.
  * No need to package wxPython/wxGTK, which is a substantial part of the size of the Ink/Stitch install zip.
  * The build system will be much simpler because we won't have to jump through all the complicated hoops to install wxPython's dependencies on each platform.
  * npm for easy management of JavaScript dependencies.

*Disadvantages:*
  * For awhile, until we transition all GUIs to Electron, we'll have to package both Electron and wxPython/wxGTK, so the ZIP will get bigger.
  * Startup may be slower since we'll have to launch both Python and Chromium.
    * Could possibly mitigate this by keeping the Electron app running after Ink/Stitch finishes.
  * We'll need to spend the effort to transition the build system and the existing GUIs.

So, what do you folks think?

**Comment by wwderw** [comment] 2019-04-04 01:13
Forgive me lack of programming knowledge, just trying to wrap my head around this:

Does this mean that it's still an Inkscape extension, it just opens a browser window for each module of Ink/Stitch like the Print-PDF?

Or

Is it becoming more of a browser based application that runs within it's own instance of Chromium?

I wonder if we should bundle a version of Vivaldi, if that's possible?  I'm just thinking of what would keep those links in the Print-PDF live without having to get an extension that throws it to an internet based service to keep those links live.  If it isn't possible, I would think it would be better to have those links "dead" then to bundle an extension that sends it to an offsite service for conversion (tin foil hat time).

**Comment by kaalleen** [comment] 2019-04-07 08:32
@wwderw Electron uses Chrome, this would be difficult to change to any other browser. You would see the browser as if it was a desktop application. Internet connection is not necessary and it is still an Inkscape extension.

@lexelby and all the others 

My first reaction was... no, oh no, no. I am really not a friend of these web-based desktop frameworks and I actually do like python for it's clean appearance. But on a second thought I am quiet undecided which opinion to give.

The speed of calling Ink/Stitch functions is very important while working with Ink/Stitch. The print preview e.g. is a function that I am thinking twice, if it is necessary calling or not. Just because it takes so long to show up. If it slows down the process, I would rather stay with wxpython. As this is the biggest issue for me in this matter.

You came up with a solution for this part already (keep electron alive), this on the other hand might even help to speed up the print function. But there we run into the next problem. It eats up a lot of memory and could be therefore annoying (especially if we keep the process alive all the time). I never tested this though, but there must be some truth about it.

Next there are security concerns. But you might be better judging those than I am.

Also it is a Microsoft product by now. I already know, that this is no argument for all the others in our team... I just cannot help but mention it.

The positive side would be an improvement of the GUI and possibly also the usability. We could help the user by giving more information about the functions and maybe show them explanatory images alongside. Last week I happened to search the german part of the internet for Ink/Stitch topics. I had to learn, that people seem to be confused if e.g. running stitch exists. The GUI in its present self, you really have to find this function through the website. Ink/Stitch itself doesn't give a hint about using dashed lines at all. Things like this could be easily improved.

So, my conclusion for now is: I really don't know :D.
If we can reach an acceptable speed while saving system resources, I am all in.

**Comment by wwderw** [comment] 2019-04-07 12:16
> Electron uses Chrome, this would be difficult to change to any other browser.

Personally, I'm not a fan of Chrome.  While Google for some things may be a reluctant necessity, I'm not one that actively likes to use it for other things then absolutely necessary.

>Also it is a Microsoft product by now. I already know, that this is no argument for all the others in our team... I just cannot help but mention it.

No, this is a concern of mine as well.  I try to be a little more open minded towards them, but again, like Chrome/Google, I don't know if I would be willing putting in their stuff into projects.


As far as changing for a GUI improvement, speed of the program etc, if it's feasible, I would think would be to have our own standalone app, that way we aren't using another layer of another project between us and what we are trying to do.

Also, we wouldn't be dependent on that other project's direction/longevity.

Maybe have an extension for Inkscape that imports whatever active document is running, opens up our program with the Inkscape file locked (maybe have one for GIMP and Krita as well, since this would be manual(semi-manual) digitizing, it wouldn't have to be a vector file as the source file) and ready to digitize on top of.  But, still have that ability to directly import into the program as well.

Maybe take an already existing open source embroidery project (EmbroiderModder, Thred) and using that as a basis for a GUI and wrapping that around the library that we have.  This would also help with tooltips etc, we could have some tip/hint pop out if a person hovers over an icon for so long etc.

If we go the standalone app, bundle that as an AppImage for linux and then just due binary archive for Windows and Mac would be a DMG I believe it it's standalone and not an extension.

Ultimately, I think that if we have to have total control over everything, from the speed, resources, all of the GUI etc, it would have to be as a standalone app.  Use one of the GUIs of the 2 above mentioned (I lean more to EmbroiderModder's GUI as that is more modern that people would expect), think about which one fits the overall aesthetic that we want to go in and then go from there and just wrap that around the digitizing and the file library that we have (the stitch engine and the file library of this project is significantly better in this project, especially with the re-vamp recently, so I would only use those other 2 projects to help get a jump start on the GUI).

**Comment by kaalleen** [comment] 2019-04-08 18:41
@wwderw Here are some thoughts or let's say concerns I have about this:

I don't think Inkscape is actually a bad starting point for an embroidery extension, it comes with a lot of nice features that we can make use of. If we had to code a whole standalone application, it would be a draw back for years (and we still would need to decide on a GUI-system that we are able (and have fun) to create).

Yes, we have to find creative solutions to make things work and yes, we possibly could make the workflow more obvious, if the whole program was designed for embroidery matters. But Inkscape connects so well to our needs.

We actually have tooltips in our GUI, but we have no way (until now) to help users to find e.g. the dashed stroke trick for running stitch - unless they read the website. To help the matter (of which I really wasn't aware of) we also could improve the existing GUI - or an other one - whatever the decision will be.

Changing the GUI is one thing, but creating a whole new app would require more dedicated developers - and might even kill the project. While we have so many nice features to work on ...

......
By the way, there is an active project right now, which is aiming for an standalone app, but it's not released yet: http://openembroidery.com/en/the-software/

**Comment by wwderw** [comment] 2019-04-08 19:03
> I don't think Inkscape is actually a bad starting point for an embroidery extension, it comes with a lot of nice features that we can make use of.

I think I misspoke.

I love the integration into Inkscape, I do like that.  You see some of that going on the commercial world, were you have integration between 2 stand along program (not many plugins for embroidery that I'm aware of).  The one thing that has always made me leary (and with Inkscape it my not be an issue at all) is future viability, if something happens with that project down the line.

Now, I'm leary of integration of 2 other pieces of software for the framework that may or may not have stability or stay with the same direction that they are on now.  And my own concerns (may just be all in my head though) of key players behind those technologies.

Now, having said that, this is coming from a non programmer and like you mentioned there are ramifications of that inability on my part as well.  I may be more tinfoil hatting it then what is really deserving with the situation.  Unfortunately, that also means that I don't know what would be a good alternative(s) to introducing these things to solve the problem (which has it's own issues as well) as far as the GUI goes.

Maybe it's just a concern born out of ignorance on my part.  I dunno.

**Comment by kaalleen** [comment] 2019-04-08 19:42
Oh, sorry for misunderstanding. I see what you mean now and I totally agree that we must be choosing our dependencies carefully.

**Comment by lexelby** [comment] 2019-04-08 21:44
Thanks folks, lots of great discussion here.  I definitely don't want to move in a direction that will upset or alienate folks.  I hope I might be able to alleviate some of your fears though.

A couple of points:

### Standalone App ###

I believe we've discussed this one before.  I agree that it would be great if we could not depend on Inkscape, as it enforces a number of constraints on us and forces us to be "creative" with the UI.

The simple fact is that I have no interest in building a vector graphics app from the ground up.  The two feasible options I see are forking Inkscape or adopting Embroidermodder.  In either case, the primary programming language will be C++.  I do have some experience with C but next to none in C++.

Programming in C++ is an entirely different beast from Python, and the idea nauseates me.  So much more code is required to do anything than in Python, and the vast majority of it is far away from our core competency: embroidery code.

It also requires that the GUI be written in C++, which is the exact opposite direction I'm hoping to go.  I am not particularly good at GUI programming and I'd rather not do it.  I much prefer writing interesting "stitch engine" code.

Bottom line: I have neither the interest, inclination, nor available time to go this route.

### Depending on other projects ###

A couple of the points above are concern about depending on other projects (Inkscape, Electron, etc).

As of now, we depend on a large number of other projects:
* PyInstaller
* Shapely (Python shape library)
* Geos (C shape library that Shapely is based on)
* wxPython (based on wxGTK)
* wxGTK
* networkx (python graph theory library)

And a ton of others.  The value of Ink/Stitch is precisely that we _do_ depend on other projects.  It means that we don't have to spend the time writing code to do what those projects do.  Instead, we can concentrate on our core competency: embroidery-related code.  This is very similar to what I said in the previous section.

Electron is a lively project with a huge amount of community support.  Inkscape is healthy as well.  And remember, even if these projects dry up overnight, that doesn't make them go away!  They're open source, and that means they will at minimum exist in their current form forever.

### Microsoft/Google ###

I'll admit, I forgot that Electron is a GitHub invention, and GitHub is now owned by Microsoft.  And of course, Chromium is the open source base for Chrome, which is Google's thing.

That said, these projects are open source, and we can depend on the thriving communities around them to weed out any nonsense from Google or Microsoft.  If either company tried to pull any shenanigans, the community would simply fork the projects.  Example: MySQL was purchased by Oracle, and the developers promptly jumped ship and formed MariaDB.

### Resource Usage and Speed ###

@kaalleen, these are definitely concerns we should keep forefront in our minds.  I hear where you're coming from, and I wouldn't want to make Ink/Stitch even slower than it is.

The thing is, the time it takes to open Print PDF has nothing to do with the fact that we're invoking a browser.  All that waiting is because Ink/Stitch has to calculate the full stitch plan.  I'm hoping the revamped fill stitch algorithm will help with that, but it's a concern.  Switching to Electron is unlikely to change that, especially if we keep Electron open between invocations.

Indeed, one idea I had in the back of my mind is popping up a little spinner that says "calculating stitch plan..." or something like that.  We could of course do that with wxPython, but I haven't had a chance.  I was thinking that this is one of the many things other folks could work on if we make UI development more approachable by switching to Electron.

I'm not worried about memory usage.  There are plenty of laptops available here in the US for $200 USD or less that have 4GB of RAM or even more.  (Is that not representative of other countries?)

### Other Concerns ###

@kaalleen, you mentioned security concerns, but I don't know what you mean by that?  What kind of attack are you thinking of?

Usability: I really think that Electron would open a whole new world of possibilities for making Ink/Stitch more usable and easy to understand.

> If we can reach an acceptable speed while saving system resources, I am all in.

I have seen quite fast/responsive Electron apps.  I think we'll be able to do just as well as wxPython, and quite possibly better.


I hope these clarifications help.  Sorry for writing an entire novel! :)

**Comment by jandetlefsen** [comment] 2019-04-09 03:13
As someone who has just found your project and tried to have a quick look how the program feels: Please go for Electron. The installation process still looks like it's something for experts. i.e. "In Inkscape, go to Edit > Preferences > System and check where your User Extensions folder is.", i've done that and that folder displayed does not exist in my file system. I'm sure that's a solvable problem but that just changed a quick 5 minute install into an (at least) hour long problem solving exercise. Do i bother that much for something i don't even know how good it is? "Well, i'll do it later", then forgot about it. How may of those who run into this issue will bother even trying further? You won't know if they won't ask. If you could package your project into a single install, i bet you could grow your user base significantly. I don't care how big the installed package is to be honest. These days software is just bigger than you think it should be, i've accepted this.
In the end you are making software for users don't you?

**Comment by kaalleen** [comment] 2019-04-09 16:19
Well, we can give it try and see how it suits us (if nobody is completely against it). I am willing to help the development.

**Comment by kaalleen** [comment] 2019-04-09 17:03
@jandetlefsen thank you for telling us your concerns. We once discussed this issue over here: #382 Maybe you are interested in reading it.

**Comment by lexelby** [comment] 2019-04-10 03:20
@jandetlefsen Thanks for your input, and thanks for trying to install Ink/Stitch!  The installation is something that's bugged me for quite awhile.  It's tons better than it was before we packaged all of the Python dependencies, but it's still much more difficult than I want it to be.

**Comment by jandetlefsen** [comment] 2019-04-10 09:08
That AppImage idea seem like a big step forward. Appreciate that this projects want to make the install process easier. How about making everything browser based? Removing the need to even install anything. Projects like [MXGraph](https://jgraph.github.io/mxgraph/javascript/examples/grapheditor/www/index.html) are probably a little off scope but it quite impressive what they can do with the browser. Honestly even installing Inkscape is hard (i.e. latest version on the mac) and it still seems to be a little buggy.

**Comment by lexelby** [comment] 2019-04-29 00:19
@kaalleen Have you ever used [Vue.js](https://vuejs.org)?  I haven't, but so far I like what I see in the tutorials.  Do we want to use it?  Or maybe you have a favorite framework?

**Comment by kaalleen** [comment] 2019-05-01 08:31
Hm, no I haven't, but it looks good to be used with electron. I have no other favorite framework which I would prefer instead.

To save me some time... Could you update the manual install for the electron build?

**Comment by lexelby** [comment] 2019-05-02 00:57
> Hm, no I haven't, but it looks good to be used with electron. I have no other favorite framework which I would prefer instead.

Cool!  It looks to me like Vue would fit pretty well with our UI, and I noticed that the template syntax is very similar to Jinja2.

> To save me some time... Could you update the manual install for the electron build?

Sure!  It'll be my first documentation update... probably about time I learned how to do that :)

**Comment by MatsIBengtsson** [comment] 2019-07-26 14:10
> @jandetlefsen Thanks for your input, and thanks for trying to install Ink/Stitch! The installation is something that's bugged me for quite awhile. It's tons better than it was before we packaged all of the Python dependencies, but it's still much more difficult than I want it to be.

I am also a new user. Commenting on this only since it got referenced in a discussion I was involved in. So first, for Ink/Stitch: It is good. I am grateful. The install worked well enough. Ink/Stitch also works well. What is the hard point is to find the functionality and understand how to use it. The web contains a lot of the needed documentation, and is helpful. 

I might have misread, but one of my biggest issues to find my way is with one of the things that I believe is discussed as the advantage of moving to Electron. The print preview, which fooled me, as per below history:

I was looking for a "trueview" functionality, and could not find it. I went through all the menues and options and settings in Ink/Stitch. Nothing there. I went through the preview print out file, nothing there either. So I concluded it did not exist. And used Premiers free version for trueview. Then I found a web page which explained how to do it in Ink/Stitch: Go into the print preview, and select the "trueview" checkbox, whatever it was called. Nice! Now I knew, I thought.

Next time I used Ink/Stitch, I tried it. No such option available in print preview options. No such command in the print preview menues. I turned on all pages through the options to find it. No such page or command in any print preview page. But I had seen the web page describing it. I had to go and find the video showing how to use it. With the video up, I went back into print preview. And lo and behold. If I rest my cursor close to the end of the page, probably any page, there is an otherwise invisible menue, where I can select a checkbox. And then it works. 

So now I have "trueview" in Ink/Stitch. And it will work as long as I remember that I have to start a command first, and then scroll past the menues displayed in the output of that command, and invoke an invisible drop down menue after the output I hoped would contain my "trueview". 

If that is an example of the Electron workflow, then I think it is harder for beginners than a checkbox in the Ink/Stitch command selection when invoking the print command, and risk being a step in the direction away from beginners. Too many levels away from the Ink/Stitch commands that are natural to look for.

**Comment by wwderw** [comment] 2019-07-26 14:40
To get realistic view, I've only had to have the cursor within the design viewport on the 1st page.  It's always come up immediately.

I'm not to sure that you mean with the commands and all that.  It's just been run Print, hover over design viewport, click realistic.

I think it's done as a hover menu to print those options from carrying over to the actual print out.

**Comment by MatsIBengtsson** [comment] 2019-07-26 17:09
> To get realistic view, I've only had to have the cursor within the design viewport on the 1st page. It's always come up immediately.
> 
> I'm not to sure that you mean with the commands and all that. It's just been run Print, hover over design viewport, click realistic.
> 
> I think it's done as a hover menu to print those options from carrying over to the actual print out.

I think there can be good programming reasons that the menu is hidden. I am only saying that when hidden, you do not see it unless you know how to get it visible. So even if there is a good programming reason to hide it, it does not change the fact that it is hidden. And the fact that if it was in the top menu, it would be visible. The other alternatives are in that menu, so it cannot hurt to have an alternative there. Likewise, if it was an option to tick in the print menu, it would be visible. As you state, it is not visible as an option in the print menu. So currently it is only visible if you do some certain maneuvers. Which is not a good GUI.

I normally scroll my documents. Meaning I have the mouse out right, not in the view-port. I have plenty of space to move the mouse left before it hits the view-port. I would not put the mouse there to try to get a menu option visible, unless I saw a video telling me that I have to put it there in order to see the menu I am trying to find.

![Capture lack of menue](https://user-images.githubusercontent.com/15014932/61968255-d0f41f80-afd7-11e9-8bb4-d778ea5de264.PNG)

**Comment by lexelby** [comment] 2019-07-26 22:52
Thanks for explaining your user experience, it really helps!  We chose to implement it this way for no reason other than that it made sense to us.  It's not caused by election and it's not about hiding it from the print-out.  It's definitely possible to keep the checkbox always visible and you make a very good argument for doing so.

Since this is unrelated to our choice of Electron, could you please open a separate issue requesting that the checkbox be always visible?

**Comment by MatsIBengtsson** [comment] 2019-07-27 05:37
>...
> Since this is unrelated to our choice of Electron, could you please open a separate issue requesting that the checkbox be always visible?

Done, see #500

**Comment by lexelby** [comment] 2019-08-11 12:55
While discussing #505, an interesting idea occurred to me.  What if Ink/Stitch was just _one_ Inkscape extension?  It would open one single unified window that contains its own menus and buttons for all the Ink/Stitch functionality like Params, Simulate, etc.   

That would allow us to have much more control over the user interface to make everything more discoverable.  The user would spend much more time interacting with Ink/Stitch and only drop back to Inkscape when they need to do vector graphics manipulation.

Chrome has a great built-in SVG editor, and you can manipulate SVG elements with JavaScript just as if they were HTML elements.  We could make it so you can select objects and add visual commands, and you'd see them displayed right away.

Anyway, just an idea.  This is probably a long way off, but it would really help make Ink/Stitch feel more like a "real" application.

**Comment by wwderw** [comment] 2019-08-11 13:28
Along those lines, wouldn't it also be possible to actually have it as an independent application using Electron?

I've been trying to get back into coding (as the only 2 languages I knew before were HTML and CSS (this was back during the CSS1 and CSS2 transition years)), so I'm only now starting to do javascript for the first time (just did some basic unit conversion and stitch run time (able to use with or without trim and trim speed variables) and a couple of games), so I'm still in the very much newbie stage.

I would think as well, being able to do this, would also mean that a greater chance of having something for ARM users as well (I know at least 1 other was asking about ARM development recently).

Am I just way off base here?

I would thin

**Comment by lexelby** [comment] 2019-08-11 13:32
No, you're not off-base.  Today would be possible, but again, we start to get into the thing where I don't want to spend my time writing a new vector graphics editor.  Think about the node tool, the pen tool, Boolean geometry (Union, difference, break path, etc).  That's a ton of work that Inkscape already excels at.  That's what's holding me back from doing as you suggest.  Find a good open source JavaScript-based SVG editor and we can get rid of Inkscape :)

**Comment by tyrosinase** [comment] 2019-08-11 13:50
It would have to be a *really* good one, because otherwise some of us would be stuck bouncing back and forth between Ink/Stitch and Inkscape. Some days I am using Inkscape to build graphics to be custom printed on fabric which then gets embroidered (or more accurately: "computer-aided-sewn"), other days I am using Inkscape to cut an applique on ye olde Silhouette Cameo which then gets embroidered, etc.

There's reasons beyond "free" to use Ink/Stitch over a different stitch editor.

(I would really like an ARM version though. My laptop is Pi-based.)

**Comment by MatsIBengtsson** [comment] 2019-08-11 14:16
> While discussing #505, an interesting idea occurred to me. What if Ink/Stitch was just _one_ Inkscape extension? It would open one single unified window that contains its own menus and buttons for all the Ink/Stitch functionality like Params, Simulate, etc.
> 
> That would allow us to have much more control over the user interface to make everything more discoverable. The user would spend much more time interacting with Ink/Stitch and only drop back to Inkscape when they need to do vector graphics manipulation.

I believe that is a very good thought. Also from integration point of view. the inx-templates are limitations, at least I have not found how to do them dynamic without sort of leaving them altogether.

It would likely make it easier to focus on Ink/Stitch as a structure and function part, and a separate presentation part. And it would make it easier to do dynamic menues. 

Side note (my standard disclaimer on this one): I do not see that having a connection to electron, more to the structure and workflow thinking.

Learned for example today that vp3writer has a loop "get_as_colorblocks" similar to the one in "read_file" and the one in "input". It is fine if they are different, but it should be visible they are different implementation of a similar theme. So in my mind, they should have a common base they override, so it is visible they work on similar objects, what is the default, and what differs. 

Should be easier to achieve if Ink/Stitch is one extension, rather than separate running programs. Threading and common process control would also be easier to implement.

**Comment by kaalleen** [comment] 2019-08-12 18:45
> While discussing #505, an interesting idea occurred to me. What if Ink/Stitch was just one Inkscape extension? It would open one single unified window that contains its own menus and buttons for all the Ink/Stitch functionality like Params, Simulate, etc.

That's how I imagined it to be :)
But we still will need the menu in Inkscape, for the shortcuts being able to work and call special functions directly. It would be otherwise sad to lose them.

**Closed** 2020-05-16 12:21 UTC
Labels: not issue
