### ISSUE TITLE
Error during autofill!

### ISSUE THREAD

**Issue by HoodPharmacist** [inkstitch/inkstitch#1145] opened 2021-04-11 05:56 UTC
path4945: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 225, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 149, in build_fill_stitch_graph
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

**Comment by kaalleen** [comment] 2021-04-11 15:14
Hey there, thanks for reporting your issue. We heard about this one often and it will be fixed in the next release.
It is caused by very small fill shapes. They are too small to embroider and cause issues. You can clean up your document by running `Extensions > Ink/Stitch > Troubleshoot > Cleanup document...`

**Comment by HoodPharmacist** [comment] 2021-04-12 01:55
I appreciate it, thank you!

**Closed** 2021-04-18 17:25 UTC
