### ISSUE TITLE
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

### ISSUE THREAD

**Issue by 3ezat** [inkstitch/inkstitch#2084] opened 2023-02-21 17:01 UTC
Ink/Stitch Version: v2.2.0 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 231, in run
  File "lib/extensions/object_commands.py", line 37, in effect
  File "lib/elements/fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'
![cross](https://user-images.githubusercontent.com/126004614/220411362-20800c83-7aba-44ad-b3f7-3308cd45f7e8.svg)

**Comment by kaalleen** [comment] 2023-02-21 19:01
Try to find very small elements in your document and remove them. Your design is a bit of a challenge for embroidery though. It will need a lot of work to look good.

**Comment by kaalleen** [comment] 2023-02-25 12:48
Duplicate of #1742

**Closed by kaalleen** 2023-02-25 12:48 UTC
