### ISSUE TITLE
Unable to save as a PES but able to save in other formats

### ISSUE THREAD

**Issue by SNuffy929** [inkstitch/inkstitch#2617] opened 2023-11-22 01:07 UTC
Able to save file as embroidery files (example COL) but unable to save as a PES or PEC

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\output.py", line 65, in effect
  File "lib\output.py", line 109, in write_embroidery_file
  File "pyembroidery\EmbPattern.py", line 1727, in static_write
  File "pyembroidery\EmbPattern.py", line 1644, in write_embroidery
  File "pyembroidery\PesWriter.py", line 50, in write
  File "pyembroidery\PesWriter.py", line 110, in write_version_1
  File "pyembroidery\PecWriter.py", line 40, in write_pec
  File "pyembroidery\PecWriter.py", line 64, in write_pec_header
AssertionError: too many color changes, (358) out of bounds (0, 255)

**Comment by tyrosinase** [comment] 2023-11-22 01:55
I thought the raw error was being caught, but apparently that's not fixed yet.

The last line does give you the problem though: the PES format is not capable of saving more than 255 color changes. It should give you a prettier message about it, but it still isn't going to be able to save the format. Other formats may be able to, but you probably don't want to physically change the thread 358 times anyway, so you need to fix the underlying problem.

This is usually caused by an auto-traced design, and you'll probably need to do a lot more work on it: clean up all the tiny bits that aren't big enough to stitch, change skinny pieces to satins, and then group all the things that will get stitched in each color run.

**Comment by kaalleen** [comment] 2023-12-15 11:24
Closing in favor of #2574

**Closed by kaalleen** 2023-12-15 11:24 UTC
