### ISSUE TITLE
path3049

### ISSUE THREAD

**Issue by slobster7** [inkstitch/inkstitch#2126] opened 2023-03-08 18:45 UTC
path3049: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 556, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 590, in do_underlay
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 62, in auto_fill
  File "lib\stitches\fill.py", line 163, in intersect_region_with_grating
ZeroDivisionError: float division by zero

Someone said that I should try and remove small elements from my project, and I did and it's still not loading params.

**Comment by kaalleen** [comment] 2023-03-08 18:48
If you want you can send your svg and I'll have a look at it.

**Comment by slobster7** [comment] 2023-03-08 22:04
![micheals duck](https://user-images.githubusercontent.com/102551338/223861027-89993d06-b991-4b2f-b2e6-031c61d01bfc.svg)
 
does this work?

**Comment by kaalleen** [comment] 2023-03-09 16:53
Try to avoid very thin areas for fills. If you make the edges of it a little less pointy it will work.

Just some suggestions...
Fills: You could also consider using a satin stitch instead of these fills, they are small enough. Your fill shapes do have a zigzag line around them. Delete the zigzags by removing the stroke color.
Strokes: Set your stroke style for the outlines to a dashed line (to use running stitch). You can make them thicker with the bean stitch or repeat param. Use Autoroute for running stitch with all the outlines selected to reduce jump stitches.

**Comment by kaalleen** [comment] 2023-05-15 21:33
Duplicate of https://github.com/inkstitch/inkstitch/issues/1829

**Closed by kaalleen** 2023-05-15 21:33 UTC
