### ISSUE TITLE
script problem

### ISSUE THREAD

**Issue by isa18120** [inkstitch/inkstitch#972] opened 2021-01-08 22:16 UTC
I'm trying to convert my svg daten in jef . I don't habe problem with the paths or parameters, anythink is allwright, but impossible to register under JEF. this message appears : what can I do?
Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "D:\a\inkstitch\inkstitch\inkscape\share\extensions\inkex.py", line 283, in affect
  File "D:\a\inkstitch\inkstitch\lib\extensions\output.py", line 48, in effect
  File "D:\a\inkstitch\inkstitch\lib\extensions\base.py", line 194, in elements_to_patches
  File "D:\a\inkstitch\inkstitch\lib\elements\element.py", line 329, in embroider
  File "D:\a\inkstitch\inkstitch\lib\elements\stroke.py", line 197, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\elements\stroke.py", line 139, in is_running_stitch
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 1: ordinal not in range(128)

**Comment by kaalleen** [comment] 2021-01-10 10:03
Duplicate of #973

**Closed by kaalleen** 2021-01-10 10:03 UTC
