### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by HarbingerOfChaos890** [inkstitch/inkstitch#837] opened 2020-10-02 17:44 UTC
Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 212, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 149, in build_fill_stitch_graph
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

**Comment by kaalleen** [comment] 2020-10-04 12:15
Thanks for reporting your issue. It is already known to us will we will look into it.

Duplicate of #734

**Closed by kaalleen** 2020-10-04 12:15 UTC
