### ISSUE TITLE
AutoFill: NetworkXNoPath

### ISSUE THREAD

**Issue by stitchwitch786** [inkstitch/inkstitch#1765] opened 2022-08-03 02:55 UTC
Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 556, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 590, in do_underlay
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 75, in auto_fill
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 630, in path_to_stitches
  File "lib\stitches\auto_fill.py", line 591, in travel
  File "networkx\algorithms\shortest_paths\generic.py", line 167, in shortest_path
  File "networkx\algorithms\shortest_paths\weighted.py", line 2377, in bidirectional_dijkstra
networkx.exception.NetworkXNoPath: No path between (98.59595410032392, 108.01989205705569) and (99.77952755905514, 112.9815190245931).

**Comment by tyrosinase** [comment] 2022-08-03 17:32
That's a bug the devs have been chasing for awhile: #1562 and some other bugs. Check that report for info on sending them a file, if you can.

**Comment by kaalleen** [comment] 2023-03-04 13:56
Duplicate of #2056

**Closed by kaalleen** 2023-03-04 13:56 UTC
Labels: needs steps to reproduce
