### ISSUE TITLE
Troubleshoot readability

### ISSUE THREAD

**Issue by AaronHdzRdz** [inkstitch/inkstitch#3061] opened 2024-07-06 20:04 UTC
Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\troubleshoot.py", line 33, in effect
  File "lib\elements\satin_column.py", line 652, in validation_errors
  File "lib\elements\satin_column.py", line 1262, in to_stitch_groups
  File "lib\elements\satin_column.py", line 1090, in do_satin
  File "lib\debug.py", line 231, in decorated
  File "lib\elements\satin_column.py", line 898, in plot_points_on_rails
  File "lib\elements\satin_column.py", line 629, in flattened_sections
  File "lib\elements\satin_column.py", line 629, in <listcomp>
IndexError: tuple index out of range
![grupo gramosa](https://github.com/inkstitch/inkstitch/assets/166132804/5df6b202-7d93-4804-95cb-3c6888dd3fcc)

**Comment by tyrosinase** [comment] 2024-07-07 19:45
The smallest shapes are too small to fit a stitch into. If you install the beta version, it will not throw this error but it will also just skip those pieces. You will probably want to consider enlarging the design overall if you can - you're going to just get a couple stitches in each dot in places.

![image](https://github.com/inkstitch/inkstitch/assets/9473609/794d343b-6809-4ddf-91c8-8eb9a984917a)

(Note to @kaalleen & co: is it just my old eyes/monitor or are the Troubleshooting colors almost unreadable now?)

**Comment by kaalleen** [comment] 2024-07-07 21:03
Warnings always have had a yellow color in the headlines and therefore harder to read. Errors are red and easier to read.
Earlier in the beginning we had more errors. Now we almost don't have any errors in troubleshoot. Most of them are warnings. Maybe that's why you just notice it at all. But it may need some attention.

**Comment by kaalleen** [comment] 2024-07-07 21:05
@AaronHdzRdz the error you are seeing is usually caused by a running stitch marked as a satin.
We are running a beta version test at the moment. Maybe you want to take part. It is supposed to fix the issue:
https://inkstitch.org/en/2024-07-04-3.1.0beta

**Closed** 2024-12-22 05:17 UTC
Labels: feature: improve
