### ISSUE TITLE
 auto_fill: ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by gleslie788** [inkstitch/inkstitch#926] opened 2020-12-20 06:45 UTC
Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 225, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 149, in build_fill_stitch_graph
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

**Comment by kaalleen** [comment] 2020-12-20 19:07
Thanks for reporting your issue. Have a look at this issue: #924
I try there to explain how to solve it for your document.

**Comment by kaalleen** [comment] 2021-01-17 11:50
Duplicate of #734

**Closed** 2021-01-18 17:47 UTC
