### ISSUE TITLE
Error when opening the Lettering Tool

### ISSUE THREAD

**Issue by tjbk23** [inkstitch/inkstitch#1971] opened 2022-12-21 02:02 UTC
Ink/Stitch Version: v2.2.0 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 231, in run
  File "lib/extensions/lettering.py", line 432, in effect
  File "lib/extensions/lettering.py", line 55, in __init__
  File "lib/extensions/lettering.py", line 147, in update_font_list
  File "lib/lettering/font.py", line 85, in __init__
  File "lib/lettering/font.py", line 91, in _load_metadata
  File "json/__init__.py", line 293, in load
  File "json/__init__.py", line 357, in loads
  File "json/decoder.py", line 337, in decode
  File "json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

I have InkStitch installed on my Windows 11 laptop and it works great. I tried installing on my new Mac and get the above error as soon as I click on the Lettering Tool. Please advise on how I can fix this. Thank you so much.
Janice Kelly
jkmccnh@yahoo.com

**Comment by kaalleen** [comment] 2022-12-21 07:18
Is that the standard install (no custom fonts?)
If so, it looks like your fonts haven't been copied over properly.
What is your macOS version?

**Comment by tjbk23** [comment] 2022-12-22 04:53
Thank you for responding so quickly. I'm running Monterey version 12.6.2. I do have one custom font that I digitized on my Windows computer, I removed it from the custom font folder after you asked about custom fonts, and the Lettering Tool worked as expected. Do I need to maintain two custom font folders (one for Windows and one for Mac) and digitize a font twice (once on Windows and once on Mac) in order to use the Lettering Tool? How can I do this more efficiently?

**Comment by kaalleen** [comment] 2022-12-22 06:12
Usually this should not be a problem to use a font on d the various operating systems.
If you did manual edits in that file in Windows it's possibly not saved in utf8 encoding.

**Comment by tjbk23** [comment] 2022-12-22 15:48
What is utf8 encoding and how do I save in that format? Thank you.

**Comment by kaalleen** [comment] 2022-12-25 07:07
What is the name of your text editor?

**Comment by tjbk23** [comment] 2022-12-26 06:33
On Windows it is Notepad. On the Mac it is TextEdit.

I'm having a lot of other issues with InkScape/InkStitch on the Mac as I try to transition over. I can't open any files directly in the program. I need to use Finder to locate the file I want to work with, use Ctrl + Click then Get Info, change Open With from Dropbox (keeps changing back to this even though I change it to Inkscape and select the Change All option) to Inkscape. Finally I double click the .svg file which then opens in Inkscape. If I try to open another .svg file I have to go through the same process or I get the following error:
 Failed to open (file path/name). 

Trying to open a .pes file, which I can open in Inkscape on my windows machine with no problems, I get this error:
nk/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v2.2.0 (osx)


Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "lib/extensions/input.py", line 22, in run
  File "lib/stitch_plan/generate_stitch_plan.py", line 22, in generate_stitch_plan
  File "pyembroidery/EmbPattern.py", line 1560, in static_read
  File "pyembroidery/EmbPattern.py", line 1493, in read_embroidery
  File "pyembroidery/PesReader.py", line 66, in read
TypeError: 'NoneType' object cannot be interpreted as an integer

Here's one of the files I'm trying to work with:
![BCH Team](https://user-images.githubusercontent.com/116860352/209511735-563d0830-9392-4eb6-972a-36b421bcf88d.svg)

I thought maybe my Inkscape install was the problem so I uninstalled and then reinstalled but that didn't fix the issues I'm having. This is very frustrating as I need to be able to work reliably on both windows and Mac.

**Comment by kaalleen** [comment] 2024-01-01 10:09
Uh, sorry, you never got any reply on your last message. Ink/Stitch had an update in the meantime. Could you fix your issue?

**Comment by kaalleen** [comment] 2024-05-13 15:19
Closing since this is pretty old now. Please open a new issue if the problem is still showing up.

**Closed by kaalleen** 2024-05-13 15:19 UTC
