### ISSUE TITLE
Error al usar extension Ink/Stitch - Letras

### ISSUE THREAD

**Issue by Jolucoma** [inkstitch/inkstitch#2390] opened 2023-06-27 15:30 UTC
Dear All,
Since I installed this version of Ink/Stitch, I can't use the Letters in the Ink/Stich extension.
I start with a blank document and then I go to the extensions menu, then I click on Ink/Stitch and then on Letters, and I get the message shown below.

The versions of the programs I use are:

Inkscape Version: Inkscape 1.2.2 (732a01da63, 2022-12-09) (windows 10)
Ink/Stitch Version: v3.0.0 (windows 10)

Error message:

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\lettering.py", line 499, in effect
  File "lib\extensions\lettering.py", line 62, in __init__
  File "lib\extensions\lettering.py", line 187, in set_font_list
wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(0, 0), "C") == 0" failed at ..\..\src\common\intl.cpp(1694) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!

I will appreciate your help.
Sincerely,
Jorge Costa

**Comment by kaalleen** [comment] 2023-06-27 20:51
Thanks for reporting!
We will very soon release a bugfix version which is going to fix the error.
If you can't wait, just pick a recent development version.

**Comment by kaalleen** [comment] 2023-06-27 20:56
I'm going to close this as a duplicate of #2345
Please open a new issue if you see this with any future version again.

**Closed by kaalleen** 2023-06-27 20:56 UTC
