### ISSUE TITLE
Inkstitch/inkscape

### ISSUE THREAD

**Issue by gregdial68** [inkstitch/inkstitch#2103] opened 2023-03-01 04:07 UTC
path902: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 556, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 590, in do_underlay
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 75, in auto_fill
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 630, in path_to_stitches
  File "lib\stitches\auto_fill.py", line 591, in travel
  File "networkx\algorithms\shortest_paths\generic.py", line 167, in shortest_path
  File "networkx\algorithms\shortest_paths\weighted.py", line 2377, in bidirectional_dijkstra
networkx.exception.NetworkXNoPath: No path between (241.70406095871246, 374.92390919175) and (244.91338582677167, 380.1852270749796).

**Comment by kaalleen** [comment] 2023-03-04 13:40
Thank you for your error report. We haven't come to analyse this issue yet, so I don't have a good advice at this point. Maybe you want to avoid small edges in your shapes, but I could be wrong about the cause.

Duplicate of #2056

**Comment by kaalleen** [comment] 2023-03-04 14:09
Closing in favor of #2056 which contains a file to reproduce the error. In that file a duplicated node caused the trouble.

**Closed by kaalleen** 2023-03-04 14:09 UTC
