### ISSUE TITLE
comments in SVG XML break Print PDF

### ISSUE THREAD

**Issue by lexelby** [inkstitch/inkstitch#908] opened 2020-12-06 14:55 UTC
```Traceback (most recent call last):
  File "inkstitch.py", line 39, in <module>
    extension.affect(args=remaining_args)
  File "/usr/share/inkscape/extensions/inkex.py", line 283, in affect
    self.effect()
  File "/home/lex/repos/inkstitch/lib/extensions/print_pdf.py", line 281, in effect
    overview_svg, color_block_svgs = self.render_svgs(stitch_plan, realistic=False)
  File "/home/lex/repos/inkstitch/lib/extensions/print_pdf.py", line 204, in render_svgs
    self.strip_namespaces(svg)
  File "/home/lex/repos/inkstitch/lib/extensions/print_pdf.py", line 197, in strip_namespaces
    if element.tag[0] == '{':
TypeError: 'cython_function_or_method' object has no attribute '__getitem__'
```

The problem is that an XML comment (`<!-- stuff -->`) doesn't behave like a normal element.  Workaround: remove the comment.

**Comment by kaalleen** [comment] 2020-12-20 20:09
I just saw this is a duplicate of #855
Also I wrote up a fix within the Inkscape 1.0 issue.
I hope it is ok if I close it, since we have the duplicate still open.

**Closed by kaalleen** 2020-12-20 20:09 UTC
Labels: bug
