### ISSUE TITLE
This is the error I received when trying to export to embroidery

### ISSUE THREAD

**Issue by mominbiz1** [inkstitch/inkstitch#969] opened 2021-01-04 23:12 UTC
path1612: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 212, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 149, in build_fill_stitch_graph
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

**Comment by kaalleen** [comment] 2021-01-07 19:28
Oh yes, we have seen this one before. It is caused by very small shapes in your document. Try to run troubleshoot > cleanup document in order to remove them.

**Comment by kaalleen** [comment] 2021-01-17 11:52
Duplicate of #734

**Closed by kaalleen** 2021-01-17 11:52 UTC
