### ISSUE TITLE
Inkstitch error code

### ISSUE THREAD

**Issue by polonag** [inkstitch/inkstitch#2286] opened 2023-05-10 19:14 UTC
Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\troubleshoot.py", line 29, in effect
  File "lib\elements\fill_stitch.py", line 321, in validation_errors
  File "lib\elements\fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'

**Comment by kaalleen** [comment] 2023-05-11 15:23
Try to remove small elements from your document.

**Comment by kaalleen** [comment] 2023-05-15 21:31
Duplicate of https://github.com/inkstitch/inkstitch/issues/1742

**Closed by kaalleen** 2023-05-15 21:31 UTC
