### ISSUE TITLE
Lettering not working at all....

### ISSUE THREAD

**Issue by roninrabbit** [inkstitch/inkstitch#1351] opened 2021-09-22 18:32 UTC
I recently updated Inkstitch to the new 2.0.
Followed the video about updating it (deleting all old files and replacing them with the new ones).
Unfortunately, LETTERING never works. 
I keep getting the error: "This font has no available font variant. Please update or remove the font."
I've uninstalled and reinstalled Inkscape with the Inkstitch extension.
Have loaded the font folder into the font extension and that has not worked either.
Have tried adding → and ← into the .svg file (because I see some weird glyph as the name for the font) and it didn't work either.

Pretty much exhausted all troubleshooting that I know how to do. Any information would be helpful, thanks!

**Comment by roninrabbit** [comment] 2021-09-23 16:34
OS is Win7 Pro (64bit). 
![Issue_1](https://user-images.githubusercontent.com/91218404/134547363-e50ab3a6-5830-4b03-bf93-7e74900db15f.JPG)

The way that this was unzipped was directly in the extensions section under preferences. 
I looked in the font extension and have tried to also cut and paste the folder in that section to see if that works and that just brings up another error. 

The picture will show the name I manually typed in to see if that would work (restarted program afterwards as well), and it didn't.
I have also typed in →.svg and this didn't work either.

**Comment by kaalleen** [comment] 2021-09-23 18:32
Thanks for the quick response. I was hoping to see the arrow named file... but I will ask then a little more ;)
Did you type in `→.svg` as a name (including `.svg`)? Try to only use `→` as the name. The .svg ending is already there but hidden.

Unzipping. I am not sure which program you used. Maybe you want to try unzipping with 7-zip? It possibly won't mess up the font file names in the first place.

**Comment by shananah** [comment] 2021-10-19 02:51
I am having this same problem, did you ever get a solution?

**Comment by Augusa** [comment] 2021-10-19 13:32
We already have this issue. It happens when you unzip inkstitch. We find it was just necessary to change the way for unzipping. Use another software for that.

**Comment by kaalleen** [comment] 2021-12-08 10:23
We hope that with the a new installation routine for the next release this will not happen as much as before. I'll close this issue, because there isn't much we can do about it (unless changing the way our font files are named) and a possible solution has been posted.
Please reopen if there are further questions about it.

**Closed by kaalleen** 2021-12-08 10:23 UTC

**Comment by ArthurMargerit** [comment] 2022-04-25 07:33
This problem is related to the name of the .svg file. this one is caused by a wrong support of UTF-8 encoding in your system.
On linux : a Solution is to set your locale to.
"
LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE=en_US.UTF-8
LC_MONETARY=en_US.UTF-8
LC_MESSAGES=en_US.UTF-8
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=
"
and not to "c"
