### ISSUE TITLE
TopologyException in clamp_path_to_polygon

### ISSUE THREAD

**Issue by ASW902** [inkstitch/inkstitch#3259] opened 2024-10-29 15:30 UTC
Include the error description and also (if possible) the svg file.

Windows 10 version: 10.0.22631

Ink/Stitch Version: v3.1.0 (windows) 2024-07-27 09:04

Traceback (most recent call last):
  File "lib\elements\element.py", line 641, in handle_unexpected_exceptions
  File "lib\elements\element.py", line 605, in embroider
  File "lib\elements\fill_stitch.py", line 942, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 1020, in do_underlay
  File "lib\debug\debug.py", line 166, in decorated
  File "lib\stitches\auto_fill.py", line 116, in auto_fill
  File "lib\debug\debug.py", line 166, in decorated
  File "lib\stitches\auto_fill.py", line 929, in path_to_stitches
  File "lib\stitches\auto_fill.py", line 885, in travel
  File "lib\utils\clamp_path.py", line 118, in clamp_path_to_polygon
  File "shapely\geometry\base.py", line 545, in buffer
  File "shapely\decorators.py", line 77, in wrapped
  File "shapely\constructive.py", line 180, in buffer
shapely.errors.GEOSException: TopologyException: depth mismatch at  at -250465.65272374905 -238217.0625887498

**Comment by kaalleen** [comment] 2024-10-29 20:14
Thank you for the error report. In order to fix the issue it would be very helpful to see the svg file and get a description of the steps you did right before the error showed up.

**Comment by kaalleen** [comment] 2024-11-27 16:31
Closing, duplicate of #3193 (which has a file)

**Closed by kaalleen** 2024-11-27 16:31 UTC
Labels: svg file missing
