### ISSUE TITLE
list of machines which can trim jump stiches

### ISSUE THREAD

**Issue by ARKopp** [inkstitch/inkstitch#407] opened 2019-03-11 23:35 UTC
Is there a list of machines that can trim jump stiches automatically? 

- Janome Memory Craft 500E

**Comment by lexelby** [comment] 2019-03-12 00:52
I wasn't able to find such a list, but I got fairly good at looking up whether a given machine could trim.  Janome 400e can trim, as can many brother innovis and Husqvarna machines.

**Comment by lexelby** [comment] 2019-03-12 00:53
The cheapest machine that can trim is the Eversewn Sparrow X.  Do not fall for it.  I bought one, and yes, it was quite capable of trimming the thread, but it unthreaded itself in the process at least 50% of the time.  I sent it back.

**Comment by ARKopp** [comment] 2019-03-12 08:23
this one also can do it ---> HUSQVARNA VIKING Topaz 25
Is the Janome Craft 500E the cheapest machine after the Eversewn. Also I am interested to select different objects of the design on the machine.

**Comment by lexelby** [comment] 2019-03-12 12:45
The 400e is generally cheaper than the 500e.  I'm pretty sure it is the next cheapest one other than the Sparrow X.  Not sure what you mean by individual objects, but you can load multiple designs and move them around.

**Comment by ARKopp** [comment] 2019-03-12 13:03
there are great deals for the 500 E here in Germany. i have the innovis nv800E and payed the same amount. It has a smaller frame and you cannot connect a pc.
<img width="1092" alt="Screenshot 2019-03-12 14 02 08" src="https://user-images.githubusercontent.com/4289157/54202074-83b35d80-44cf-11e9-8c27-03c83cd4c9a9.png">

**Comment by lexelby** [comment] 2019-03-12 14:08
Oh my, that's cheaper than the 400e here in the states! I'm jealous! :)

For machines like the 400/500e, it's possible to rig up a raspberry pi to simulate a USB

**Comment by jameskolme** [comment] 2019-03-12 17:30
@ARKopp If you are looking Janome 500E and want to save lets say 270€, look no further and go to Estonian shop https://shop.kl24.ee/embroidery-machine-tikkimis-masin-kirjonta-kone/&lng=14/ To me this is very trust forty shop, unfortunately only half of items are listed and they are currently changing embroidery thread brand. I should make visit soon, but it takes full day using ferry over gulf of Finland.

**Comment by tyrosinase** [comment] 2019-03-26 01:38
The Brother PE-800 doesn't seem to honor either trim commands or stop commands; I put some in some patterns and now it behaves interestingly with those: leaves a black space in the selection screen. I'm guessing it recognizes it's a PES file (possibly just by the extension) but there's something that makes it think it's corrupt.

Still trying to nail down the details, because I'm pretty sure I had put commands in other files and this didn't happen (it ran the PES just, you know, didn't stop where the command was). Might be that I updated Inkstitch in between (I'm on whatever the current version was on Feb 16).

**Comment by wwderw** [comment] 2019-03-26 10:25
I don't know of a Brother machine now (I have 2 PRs along with my Barudan) that recognizes stop commands.

I know on my PRs, if a PES file has a stop command (doesn't matter the software that generated the file) it will actually cause a reboot of the machine when one tries to open it up on screen.

"You" can get around this on a single needle by just creating a color change at the area that you want a stop to happen, not change out the thread and continue on when ready.

**Comment by tyrosinase** [comment] 2019-03-26 15:57
Yeah, I just deleted the stops, generated the PES, and then didn't save the deleted-stops SVG version.

The problem is, I kind of want to be able to put stops in the svg, so they're there for machines that do honor them (because I don't want it to blow through the stop on a multi-thread machine when it's a point where you should be trimming an applique or something). But if single-thread Brothers crash on PES-with-stop but there are multi-thread machines that are using PES files, then yeah, that's a whole different (non-Inkstitch) problem.

I guess I'll just build files without stops, and let the multi-thread folks deal with setting stops on their own. SERVES THEM RIGHT FOR HAVING FANCIER MACHINES THAN ME ANYWAY

**Comment by wwderw** [comment] 2019-03-26 17:03
>  But if single-thread Brothers crash on PES-with-stop but there are multi-thread machines that are using PES files, then yeah, that's a whole different (non-Inkstitch) problem.

My PRs are multi-needle machines that don't accept stop codes from 3rd party software.  The close that they have is the applique stop codes (placement, tack down etc) in PE-Designs.  PE-Designs (at least with ver. 7 (long time I know)) didn't have individual stop codes for like puff etc.  Unless there is another home brand machine (Bernina, Pfaff etc) that accepts PES files that does allow for stops in that file format (I doubt it as PES is Brother's own format), I would actually use the DST format.  I'm actually unsure if the way that Brother acknowledges the applique "stop" code from PE-Designs is using "STOP" as the function, it could be another function that translate to the same thing that's unique to the Brother format.

Typically what I do for applique stop designs is a create them with color changes for the appropriate places and in the "print out" in the notes, I'll mention to apply "stop" at the machine for this color block or that color block etc.

That way if someone bought your designs that can't handle them won't have the "bad taste" of your design causing their machine to crash and reboot if the "STOP" code is hard coded into the design.

**Comment by kaalleen** [comment] 2020-04-12 12:30
Closing the issue now. The same topic is discussed in #599

**Closed by kaalleen** 2020-04-12 12:30 UTC
