### ISSUE TITLE
XMLSyntaxError: xmlns:i: '&#38;#38;ns_ai;' 

### ISSUE THREAD

**Issue by DefiningNatali** [inkstitch/inkstitch#772] opened 2020-07-23 23:01 UTC
just a few hours before i was able to use the plug in with no issues now I only receive this message

File "d:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "d:\a\inkstitch\inkstitch\inkscape\share\extensions\inkex.py", line 279, in affect
  File "d:\a\inkstitch\inkstitch\lib\extensions\base.py", line 210, in parse
  File "d:\a\inkstitch\inkstitch\inkscape\share\extensions\inkex.py", line 202, in parse
  File "src\lxml\etree.pyx", line 3519, in lxml.etree.parse
  File "src\lxml\parser.pxi", line 1860, in lxml.etree._parseDocument
  File "src\lxml\parser.pxi", line 1880, in lxml.etree._parseFilelikeDocument
  File "src\lxml\parser.pxi", line 1775, in lxml.etree._parseDocFromFilelike
  File "src\lxml\parser.pxi", line 1187, in lxml.etree._BaseParser._parseDocFromFilelike
  File "src\lxml\parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src\lxml\parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src\lxml\parser.pxi", line 640, in lxml.etree._raiseParseError
XMLSyntaxError: xmlns:i: '&#38;#38;#38;ns_ai;' is not a valid URI, line 3, column 37 (line 3)

**Comment by kaalleen** [comment] 2020-08-30 08:59
I will close the issue, because it is a duplicate of #726

**Closed by kaalleen** 2020-08-30 08:59 UTC
