### ISSUE TITLE
Problem saving as .pes file

### ISSUE THREAD

**Issue by scottr50** [inkstitch/inkstitch#1871] opened 2022-10-22 17:27 UTC
path10553: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 556, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 590, in do_underlay
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 62, in auto_fill
  File "lib\stitches\fill.py", line 163, in intersect_region_with_grating
ZeroDivisionError: float division by zero

**Comment by tyrosinase** [comment] 2022-10-22 17:36
There is a dev release that will fix this error (https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-thisandthat01, pr https://github.com/inkstitch/inkstitch/pull/1727) but it's being triggered by a too-small or too-thin piece in your SVG - often a traced bitmap in need of cleanup. You can use Extensions > Ink/Stitch > Troubleshoot > Cleanup Document and that will generally find them for you.

**Comment by scottr50** [comment] 2022-10-22 17:45
Tyrosinase,

Thank you for the information.

Rosie

**Comment by nesta-embori** [comment] 2022-10-22 21:34
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v2.2.0 (windows)


Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\extensions\base.py", line 200, in elements_to_stitch_groups
  File "lib\elements\element.py", line 329, in embroider
  File "lib\elements\element.py", line 387, in validate
  File "lib\elements\fill_stitch.py", line 321, in validation_errors
  File "lib\elements\fill_stitch.py", line 274, in shape
AttributeError: 'Point' object has no attribute 'geoms'

**Comment by kaalleen** [comment] 2023-02-25 13:51
First issue: duplicate of #1829 
Second issue duplicate of #1816

**Closed by kaalleen** 2023-02-25 13:51 UTC
Labels: duplicate
