### ISSUE TITLE
Ink/Stitch Trojan Alert - Wacatac

### ISSUE THREAD

**Issue by LizFLL** [inkstitch/inkstitch#710] opened 2020-05-18 21:34 UTC
Hi everyone, I'm an end user that just downloaded the 1.28.0 version zipfile of Windows for the US. As I attempted to install it, my machine alerted me that a Trojan was identified and quarantined the file. I immediately aborted the rest of the unzipping and have since deleted everything, but wanted to alert the group here that there is a virus inside the package. I'm attaching screenshots for review. Thanks so much. 

![Trojan Alert](https://user-images.githubusercontent.com/65570394/82261862-d25b5380-992d-11ea-868e-85c6a33b4924.png)

![Inkstitch file downloaded](https://user-images.githubusercontent.com/65570394/82261876-d5eeda80-992d-11ea-9547-b1f30032391b.png)

**Comment by lexelby** [comment] 2020-05-23 11:43
Hi, folks.  Thanks for trying Ink/Stitch!  I'm sorry antivirus is giving you trouble.

We use a tool called PyInstaller to package up our Python code and all of its dependencies. Unfortunately, it seems to be fairly common that antivirus software incorrectly detects a virus in programs created with PyInstaller.  As far as we can tell, there is no actual virus, and Ink/Stitch is safe.  It's a false positive.

If anyone has any ideas for how we can avoid this problem, I'd love to hear them.

**Comment by geonom** [comment] 2020-05-23 22:38
Hey there, thank you for the explanation!

I searched upstream and indeed, this issue can apparently only be fixed by the antivirus software vendors, see for example:

https://github.com/pyinstaller/pyinstaller/issues/4633

**Comment by lexelby** [comment] 2020-05-24 02:45
I suspect the problem is that the executables that PyInstaller produces contain compressed files.  That's essentially random(ish) data and I guess it's not surprising it matches a virus...

**Comment by lexelby** [comment] 2020-05-27 03:22
I have an update!  This release might be considered clean by antivirus: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-lexeby-build-pyinstaller-bootloader

I checked it on virustotal and it got a clean bill of health.  If this works I can make a v1.28.1 release in the same manner.

**Comment by lexelby** [comment] 2020-05-27 03:41
Aw damn, I might have done the virustotal test wrong.  Well, let me know what results you end up with.

**Comment by maskedman5** [comment] 2021-02-26 03:46
HI all,
I'm having the same issue with my windows machine. Unfortunately, McAfee is soooooo locked down that I can't override it - the minute the inkstitch.exe is accessed, its deleted by my antivirus. Is there anyway I can manually install Python, and then compile a binary that doesn't have the PyInstaller code?

**Comment by SteadyQuad** [comment] 2021-03-26 14:37
Another virus alert for inkstitch.exe in a dev build:

https://github.com/inkstitch/inkstitch/releases/download/dev-build-kaalleen-thread-palette-fix/inkstitch-kaalleen-thread-palette-fix-windows-nl_NL.zip

Windows defender says:
![Screenshot 2021-03-26 153515](https://user-images.githubusercontent.com/11686811/112647658-0a360000-8e49-11eb-9630-79b185d7cd10.png)

https://www.virustotal.com/gui/file/a328bcbdbfd4818b8b973ce06a8fbf008f68b0248c3e2964ebac33b38ecd0a9e/detection

25 out of 68 scanners flag this as suspicious or malicious, but mainly based on heuristics/AI. 

Very likely due to pyinstaller again, is probably safe.

**Comment by elibroftw** [comment] 2021-08-31 17:59
Let me know what the solution is if someone finds out because I have the same issue for my project, Music Caster.
I updated pyinstaller to the latest and built the bootloader myself and got these issues for my program too. I have to restore my program twice a week! I might decide to rollback pyinstaller because of how annoying this is...

**Closed** 2023-07-04 17:13 UTC
