### ISSUE TITLE
trying to save svg as a pes

### ISSUE THREAD

**Issue by vlynromano** [inkstitch/inkstitch#2097] opened 2023-02-27 15:04 UTC
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v2.2.0 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 231, in run
  File "lib/extensions/output.py", line 56, in effect
  File "lib/extensions/base.py", line 200, in elements_to_stitch_groups
  File "lib/elements/element.py", line 329, in embroider
  File "lib/elements/element.py", line 387, in validate
  File "lib/elements/fill_stitch.py", line 321, in validation_errors
  File "lib/elements/fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'

[](url)
![beast logo](https://user-images.githubusercontent.com/126492748/221599658-e82d8436-3ef0-449a-82ba-e13b990ae9a4.svg)

**Comment by kaalleen** [comment] 2023-02-27 17:48
Thank you for reporting your error. You have a lot of small elements in your document that prevent it from rendering. The next Ink/Stitch version will not fail on them, but it still would be better to work with a clean document. Ink/Stitch has an extension for that (Extensions > Ink/Stitch > Troubleshoot > Cleanup document). But in the current release it will fail on these elements too. So I ran it on your file with a current development branch and it removed 144 elements from your file.

I also noticed, that you will need to remove the duplicated shapes otherwise you may run into very high density. But I didn't know how you wanted to proceed from there, so I just removed those small elements so it won't error out.

![2097_modified](https://user-images.githubusercontent.com/36401965/221641725-43d8ec9c-5fc3-4e0d-b644-206994fe76c8.svg)

**Comment by kaalleen** [comment] 2023-03-04 14:22
Duplicate of #1742

**Closed by kaalleen** 2023-03-04 14:22 UTC
