### ISSUE TITLE
stitch_plan.py: ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by igenyar** [inkstitch/inkstitch#801] opened 2020-08-25 02:41 UTC
I am using SewArt to convert an image to pes file. Then I try to open pes in Inkscape and encounter the following error. Thank you for the help!

Platform: Windows 10
Inkscape version: 1.0
Inkstitch version: 1.29.1 

Error

Ink/Stitch experienced an unexpected error.
If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below: 

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "D:\a\inkstitch\inkstitch\lib\extensions\input.py", line 40, in affect
  File "D:\a\inkstitch\inkstitch\lib\stitch_plan\stitch_plan.py", line 147, in extents
  File "D:\a\inkstitch\inkstitch\lib\stitch_plan\stitch_plan.py", line 133, in bounding_box
ValueError: min() arg is an empty sequence

**Comment by kaalleen** [comment] 2020-08-29 10:06
Thank you for reporting your issue. This is not a problem of your installation, but an error in Ink/Stitch.
We will have a look into it as soon as possible. It would be very helpful if you could provide a SVG file which is causing the error.

**Comment by kaalleen** [comment] 2021-02-06 17:10
Duplicate of #734

**Comment by kaalleen** [comment] 2021-04-04 09:33
See #1099

**Closed by kaalleen** 2021-04-04 09:33 UTC
Labels: bug
