### ISSUE TITLE
Fixes for 2.2.0 - Error reports

### ISSUE THREAD

**Issue by danielkschneider** [inkstitch/inkstitch#1704] opened 2022-06-24 13:54 UTC
Hi. Don't know if this is the right place to report. This dev release seems to work fine on windows 10. Under Ubuntu I got this error when opening the Param Panel or anything else I tried.
Traceback (most recent call last):
  File "inkstitch.py", line 28, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "lib/extensions/__init__.py", line 18, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "lib/extensions/density_map.py", line 7, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "scipy/spatial/__init__.py", line 107, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "scipy/spatial/_procrustes.py", line 9, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "scipy/linalg/__init__.py", line 198, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "scipy/linalg/_misc.py", line 4, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "scipy/linalg/lapack.py", line 818, in <module>
ImportError: /opt/inkstitch/bin/scipy/linalg/_flapack.cpython-38-x86_64-linux-gnu.so: ELF load command address/offset not properly aligned
[243347] Failed to execute script 'inkstitch' due to unhandled exception!

I installed this package like this:
 sudo dpkg -i inkstitch_0.0.1.kaalleen.fixes.for.220_amd64.deb
 
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal

**Comment by kaalleen** [comment] 2022-06-24 14:59
Thank you for your report. We are actually close to a test phase before we release the next official version. So this is a good place to report all upcoming bugs in the test release. This particular bug is a duplicate of #1688.

**Comment by kaalleen** [comment] 2022-06-30 17:26
I'll close the issue now. The fixes branch has been merged. This bug shouldn't show up in the release :)

**Closed by kaalleen** 2022-06-30 17:26 UTC
Labels: bug
