### ISSUE TITLE
Bi-color random satin

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#2806] opened 2024-03-29 13:05 UTC
I've got two identical-but-for-color satins, with the same random seed, and one `100 0` and the other `0 100` for random width increase. Alas, they don't match up. Is there a setting in which they would, or does the code not allow it?

![image](https://github.com/inkstitch/inkstitch/assets/9473609/10628622-4dce-4a8b-9c8e-eb973a897c88)

**Comment by lexelby** [comment] 2024-03-30 01:20
Ooh, interesting idea!  I'm afraid the code indeed won't allow this.  Setting the seed the same does ensure that the random numbers used are the same in both cases.

However, there are effectively two entirely different sequences of random numbers here: one for the left rail and one for the right.  In the left satin, only the first sequence of random numbers has any effect (because you set 0 as the increase for the right rail).  In the right satin, only the second sequence of random numbers is used (because you set 0 as the increase for the first rail).  Sorry!

**Comment by lexelby** [comment] 2024-03-30 01:34
Oh, but check this out!  You can set the satin decrease on one satin 50 `50 0`.  Then set the satin decrease on the other to `-50 0` (turns out negatives work!) and check the "swap rails" option.  Here's the result:

![image](https://github.com/inkstitch/inkstitch/assets/4446653/8e8933d7-d6d9-4811-98fd-1aacdf5b6e04)

Tweak as needed.  For example, you can make the left satin narrower to make the result appear roughly equal between the two colors.

Interesting thing I Just saw: if you set the random satin decrease and increase to the same percentage, they cancel out.  That's ... not exactly what I would expect.  They apparently use the same random sequences!  That seems like a bug, although perhaps you could take advantage of it in this case.

**Comment by tyrosinase** [comment] 2024-03-31 15:37
Ahhhhh, I *thought* there might be a sneaky way to pull it off. Thank you so much!

**Comment by lexelby** [comment] 2024-04-01 16:03
Glad to help!  I'm gonna close this now, but let me know if that doesn't work out.

**Comment by kaalleen** [comment] 2024-04-02 17:06
But that's a cool feature. Not sure if we should call it a bug. If we keep it, we should make a short tutorial for bi-color satins on the website ... ?

**Comment by tyrosinase** [comment] 2024-04-03 14:24
Oh, definitely a feature and not a bug.

**Comment by george-steel** [comment] 2024-04-07 23:09
> Interesting thing I Just saw: if you set the random satin decrease and increase to the same percentage, they cancel out. That's ... not exactly what I would expect. They apparently use the same random sequences! That seems like a bug, although perhaps you could take advantage of it in this case.

It's not a bug, just a way to input a range that is sampled from randomly. Sometimes it is easier to draw a minimum, sometimes a maximum, or sometimes an average.

**Comment by claudinepeyrat06** [comment] 2024-04-17 05:14
Great!!  easy way to tweak widths is to use the pull compensation percentage :
<img width="500" alt="image" src="https://github.com/inkstitch/inkstitch/assets/88194877/24834205-e4ae-4c59-9dea-b3dba41eecea">
<img width="564" alt="image" src="https://github.com/inkstitch/inkstitch/assets/88194877/7c362706-056f-4c3b-8418-4c1b69aedb59">

**Comment by claudinepeyrat06** [comment] 2024-04-17 10:42
but why stop at two colors : 
<img width="599" alt="image" src="https://github.com/inkstitch/inkstitch/assets/88194877/a3cfe8e4-6af8-432a-bed3-442c0ce568d7">
![tricolore](https://github.com/inkstitch/inkstitch/assets/88194877/cc364e01-398a-4ea1-9a2d-af1b298d8a7b)

**Comment by lexelby** [comment] 2024-04-17 17:32
So cool!  That's brilliant!

**Comment by tyrosinase** [comment] 2024-04-18 14:02
Now I'm wondering if that can be chained for infinite blends. Probably have to be straight shapes to keep things identical even with the same seed, but I bet it would work.

**Comment by claudinepeyrat06** [comment] 2024-04-18 16:25
very doable
![arcenciel](https://github.com/inkstitch/inkstitch/assets/88194877/24311471-9683-4955-943a-f0106dfd1223)

**Comment by tyrosinase** [comment] 2024-04-19 18:26
Oh, wow, I was thinking multiple satins that just used the same seed. It does repeat the "random" distribution, but not in adjacent borders, so that's probably acceptable in almost any situation. Genius!

**Closed** 2024-05-01 04:59 UTC
Labels: documentation
