### ISSUE TITLE
autofill TopologyException

### ISSUE THREAD

**Issue by jawsfree** [inkstitch/inkstitch#1449] opened 2021-11-19 14:30 UTC
use844: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "lib\elements\auto_fill.py", line 223, in to_patches
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 63, in auto_fill
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 144, in build_fill_stitch_graph
  File "lib\stitches\fill.py", line 146, in intersect_region_with_grating
  File "shapely\geometry\base.py", line 676, in intersection
  File "shapely\topology.py", line 70, in __call__
  File "shapely\topology.py", line 35, in _check_topology
shapely.errors.TopologicalError: The operation 'GEOSIntersection_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.multipolygon.MultiPolygon object at 0x0B2E20E8>

shapely.geos - ERROR - TopologyException: Input geom 1 is invalid: Hole lies outside shell at or near point 430.8669479056 378.98411980536002 at 430.8669479056 378.98411980536002
shapely.geos - INFO - Hole lies outside shell at or near point 430.8669479056 378.98411980536002

**Comment by tyrosinase** [comment] 2021-11-19 14:40
That sounds like the same thing as #216 but that should have been fixed in this version of Ink/Stitch.

It should have told you to do `Fill Tools > Break Apart Fill Objects` rather than throwing the messy error text.

**Comment by kaalleen** [comment] 2021-12-08 09:13
I cannot reproduce the error with the file given in #216
Would you mind to send yours (if still exists)?

**Comment by kaalleen** [comment] 2024-06-13 09:35
Since we use shapelys make_valid this is unlikely to happen again (hopefully).
Therefore I'll close the issue. If this or a smiliar (or any other) issue shows up again... please open a new issue.

**Closed by kaalleen** 2024-06-13 09:35 UTC
Labels: bug, needs steps to reproduce
