### ISSUE TITLE
Crash with hatched files

### ISSUE THREAD

**Issue by danielkschneider** [inkstitch/inkstitch#241] opened 2018-07-23 18:04 UTC
Hi I encountered a crash
system: Ubuntu 18 / Inkscape 0.92 / Inkstitch 1.13
![hatch-bug](https://user-images.githubusercontent.com/2872643/43094535-866220f2-8eb3-11e8-9aa8-407542cdfeab.png)

Attached a zip with the SVG.
[pentagram-6.zip](https://github.com/inkstitch/inkstitch/files/2220471/pentagram-6.zip)

The two stars to the left work ok. The star on bottom right makes the Inkscape crash. The one on top right does not fill right which is a separate issue I can report after playing some more.
![pentagram-6 svg](https://user-images.githubusercontent.com/2872643/43094070-3cfdb792-8eb2-11e8-9c40-a8bafe843889.png)

The hatches were made with EggBot
https://github.com/evil-mad/EggBot/releases/tag/2.7.1

I am trying to figure out how to create "non-tatami" fills using Inkscape extensions. I will think about this a bit more and then maybe make a suggestion on how to use an InkScape "layer" for generating some types of embroidery patterns.
- greetings ! Daniel

**Comment by lexelby** [comment] 2018-07-24 01:09
Oh neat, that's an Inkscape crash!  Unfortunately, it doesn't crash inkscape for me. :(  Which version of Inkscape are you using?

I've seen mysterious Inkscape crashes a couple of times, but I haven't been able to reliably reproduce them.  Does this one reproduce for you?

There's one thing that I know reliably crashes Inkscape: if the extension emits invalid SVG XML.  That can happen if there's an errant print statement in Ink/Stitch.  I don't _think_ that's what's happening here...

**Comment by danielkschneider** [comment] 2018-07-24 07:41
Inkscape 0.92 (dont know which subversion, I am at home right now)
I can reproduce this error on Windows 10, Inkscape 0.92. I am using embroidery -> embroider...

However, there is some extra twist.
- the program crashes after I select all objects on the screen
- it does not crash if I do no select anything
I did open the file and clean out unused stuff (i.e. pattern definitions), but this did not help. I don't think that any hidden "bad" objects remains, but maybe I am blind.

Each hatch is a huge path and they are a bit weird as you can see in the generated stitch plan.

![eggbot-hatches-bug](https://user-images.githubusercontent.com/2872643/43123722-581e3cc2-8f25-11e8-9c8f-96b10dc2bb39.png)

Attached a cleaned up version of the file.
[pentagram-6.zip](https://github.com/inkstitch/inkstitch/files/2222517/pentagram-6.zip)

**Comment by danielkschneider** [comment] 2018-07-24 12:21
I do have 0.92.3 and I rarely get crashes, but I do get some and all of these crashes are very difficult to reproduce consistently. Often, just changing the order in which I parametrize or the way I select objects can cause or not a crash.

The model in zip file crashes **IFF I "select all" with "rectangle selection" on the desktop**. It does not crash if I do the "stars" one by one or if I do not select anything. The weird thing is that I cannot see any strange invisible "intruder" object in the SVG.

**Comment by AkiraNorthstar** [comment] 2018-07-24 12:38
Can you please answer these questions? :
- Are the crashes under Windows or under Linux? Or with both systems?
- Are all systems x64, or are they mixed?

If it also happens under a linux, then I would still need the installed kernel version (uname -a in a terminal is enough for me).

**Comment by danielkschneider** [comment] 2018-07-24 14:17
Hi.
(1)  It happens under both Linux and Windows. 
(2) Both are x64

Linux: 
- Linux tecfalx 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- 6.63.2 "Intel(R) Xeon(R) CPU E5-1620 v3 @ 3.50GHz
- "nVidia GM204GL [Quadro M4000]"

Windows:
- One machine is a Dell xps 15, windows pro, with i7-7700HQ and a GTX 1050
- The other is a Dell precision, windows pro, with a Quadro P4000

On both systems, the crash is not systematic. E.g. changing a tiny detail in the way and/or order I define params or select objects can make it either work or crash. All my machines have non standard graphic cards, in case this could make a difference.

**Comment by danielkschneider** [comment] 2018-07-24 16:15
Sorry, this gets confusing. I also wanted to test this on my small xps15 laptop. I noticed that I had an old 0.92.2 Inkscape and replaced it with a 0.92.3 and now I cannot reproduce the error anymore :( But I did triple check under Ubuntu (I got  Inkscape 0.92.3 (2405546, 2018-03-11)) and can reliably reproduce the crash with the svg files I posted. I will double check on my other Windows machine I have at home.

**Comment by AkiraNorthstar** [comment] 2018-07-24 17:00
Have you ever run inkscape via terminal? Eventually there is more information about it. I have run your two files (pentagram-6) on all my machines - without any problems.
Well, that's really weird ...

**Comment by lexelby** [comment] 2018-07-25 00:13
> If you do not have version 0.92.3, you should try it.
> Changelog: * Invalid output generated from extensions no longer makes Inkscape crash.
> Most crashes can be found in the gcode extensions.

I was so excited for this change when you mentioned a week or two ago, but unfortunately, it doesn't seem like they fixed all such crashes.  I've been running 0.92.3 for awhile, as it turns out, and invalid output still crashes Inkscape. :(

**Comment by lexelby** [comment] 2018-07-25 00:17
> Sorry, this gets confusing.  [...]

Eek, heisenbug. :(

Does Inkscape crash before or after the Embroider extension runs?

**Comment by danielkschneider** [comment] 2018-07-25 08:45
Indeed it is a bug and not a bug. If I launch it from the terminal I get this: 
 ** (inkscape:6655): WARNING **: 10:10:17.267: Incompatible units
If I launch it "normally" it crashes doing the same operations, either
* select all objects with the mouse (rectangle select)
* Embroidery->Param->Tick TRIM
* Click on Apply and quit

or:
* select all with mouse
* Embroidery -> Embroider
so it crashes during or after the use of the extension.

The whole terminal output is in this file:
[inkscape.txt](https://github.com/inkstitch/inkstitch/files/2227102/inkscape.txt)

Conclusion (IMHO, of course)
- It's an Inkscape bug
- It's also an Eggbot problem, because it seems to generate strange paths. Btw. on their [web site](https://wiki.evilmadscientist.com/Installing_software) they say that it is not certified to work with Inksapce 0.92 (but I did not read that before). 

Sorry for the trouble, but the good news is that with the Eggbot extension one can fill polygons with line-based fills such as some kind of cross stitches.

![753px-eggbot-hatches-1](https://user-images.githubusercontent.com/2872643/43189368-b2fdf412-8ff6-11e8-9c1e-7d1fdfb33fda.jpg)

Finally, I will be quiet over the next 2 1/2 weeks (going on vacation to La Palma who claims to be the steepest island in the world. I wonder how they can claim that, mathematically speaking).

**Comment by lexelby** [comment] 2023-07-08 23:34
It's been 5 years, so I'm gonna close this, but if it happens again, feel free to reopen.

**Closed** 2023-07-08 23:33 UTC
Labels: bug
