### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by 357Lisa357** [inkstitch/inkstitch#2210] opened 2023-04-09 19:25 UTC
path4578: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 556, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 590, in do_underlay
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 62, in auto_fill
  File "lib\stitches\fill.py", line 163, in intersect_region_with_grating
ZeroDivisionError: float division by zero

![image](https://user-images.githubusercontent.com/120815036/230792517-407bd459-faa3-4334-8381-1d46397f248f.png)

**Comment by kaalleen** [comment] 2023-04-10 21:55
Watch out for small fills or fill areas that are very small in stitch direction. This also could be a very pointy corner.
The next Ink/Stitch release will be more forgiving. But it is always a good advice to keep your svgs as clean as possible.

If you want us to track down the problematic spot, you can also upload your svg.

**Comment by kaalleen** [comment] 2023-05-15 21:13
Duplicate of #1829

**Closed** 2023-05-15 21:23 UTC
