### ISSUE TITLE
ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by Fastlaneest** [inkstitch/inkstitch#949] opened 2020-12-28 21:57 UTC
path1468: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 212, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 149, in build_fill_stitch_graph
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

**Comment by kaalleen** [comment] 2020-12-29 14:22
Thanks for reporting your issue. We have recently (hoepfully) fixed the bug and it should be fine in the next release.

For now watch out for very small objects in your document. They seem to cause the error.

**Comment by Fastlaneest** [comment] 2020-12-29 18:39
Thanks so much for the reply. I am a novice and all this can be somewhat overwhelming. Do you have any idea when this patch will be released. Thanks,Paul LaneOn Dec 29, 2020 8:22 AM, Kaalleen <notifications@github.com> wrote:
Thanks for reporting your issue. We have recently (hoepfully) fixed the bug and it should be fine in the next release.
For now watch out for very small objects in your document. They seem to cause the error.

**Comment by kaalleen** [comment] 2021-01-17 11:52
Duplicate of #734

**Closed by kaalleen** 2021-01-17 11:52 UTC
