### ISSUE TITLE
ValueError: min() arg is an empty sequence in auto_fill.py

### ISSUE THREAD

**Issue by belkira** [inkstitch/inkstitch#734] opened 2020-06-03 20:04 UTC
path53: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/elements/auto_fill.py", line 212, in to_patches
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 55, in auto_fill
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 149, in build_fill_stitch_graph
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

**Comment by kaalleen** [comment] 2020-06-04 05:24
Thanks for reporting this bug. This is really helpful.

**Comment by lexelby** [comment] 2020-08-18 20:20
@belkira Yes, thank you for reporting this!  Is there any way you can share the SVG file that you were working on when you saw this problem?  I'm having a hard time understanding what might have been going on.

**Comment by kaalleen** [comment] 2020-08-29 09:47
https://github.com/inkstitch/inkstitch/issues/804#issuecomment-683060941
Provides a file to this issue.

**Comment by maskedman5** [comment] 2020-11-22 18:25
Hi all, it appears this bug (#734) is still open? Any workarounds with respect to a file I have that is causing this?

**Comment by kaalleen** [comment] 2020-12-03 19:46
Yes, it is still open. We haven't come to release a bugfix yet.

The problem is caused by little tiny objects from your document. They will be dificult to find, because they are left over shapes from some operations (like image tracing) that you have performed previously. Ink/Stitch comes with two functions which could help you to remove them:

1. Option:
Select everything (Ctrl + A) and run: Extensions > Ink/Stitch > Fill Tools > Break apart fill objects ...

2. Option:
Run Extensions > Ink/Stitch > Troubleshoot > Cleanup Document

Hope that helps.

**Comment by kaalleen** [comment] 2021-04-04 09:05
This error will be fixed with the next version.

**Closed by kaalleen** 2021-04-04 09:05 UTC
Labels: bug
