### ISSUE TITLE
auto_fill: ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by fatboxwarm** [inkstitch/inkstitch#1023] opened 2021-02-06 19:08 UTC
raceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 212, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 149, in build_fill_stitch_graph
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

**Comment by kaalleen** [comment] 2021-02-06 21:20
Try to run Extensions > Ink/Stitch > Troubleshoot > Cleanup documents...

This will remove small fill objects from your document. They are causing this type of error in the current Ink/Stitch version. We hope to release a fix soon. Thank you for your report.

**Comment by kaalleen** [comment] 2021-03-06 13:10
This is a duplicate of #734, so I will close this issue now.
Please reopen, if you still need it.

**Closed by kaalleen** 2021-03-06 13:10 UTC
