### ISSUE TITLE
trying to convert to pes dst

### ISSUE THREAD

**Issue by nesta-embori** [inkstitch/inkstitch#1873] opened 2022-10-22 21:33 UTC
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\extensions\base.py", line 200, in elements_to_stitch_groups
  File "lib\elements\element.py", line 329, in embroider
  File "lib\elements\element.py", line 387, in validate
  File "lib\elements\fill_stitch.py", line 321, in validation_errors
  File "lib\elements\fill_stitch.py", line 274, in shape
AttributeError: 'Point' object has no attribute 'geoms'

**Comment by tyrosinase** [comment] 2022-10-22 21:44
There is a dev release that should fix this error (https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-thisandthat01, pr https://github.com/inkstitch/inkstitch/pull/1727) but it's being triggered by a zero-radius circle in your SVG (at least, if it's the same as #1816) - if you find and delete that, it should work around it for the release you have installed.

**Comment by kaalleen** [comment] 2023-03-04 14:30
Duplicate of #1816 

I'm closing this issue as a duplicate. If you have more questions it is still possible to post your message here or in a new issue.

**Closed by kaalleen** 2023-03-04 14:30 UTC
