### ISSUE TITLE
Simple color swaps in .pes file seen on es600 brother

### ISSUE THREAD

**Issue by bigredfrog** [inkstitch/inkstitch#1286] opened 2021-07-25 16:05 UTC
Hi all,

Quick context.

Brand new to embroidery and sewing.
Long time user of inkscape
Long history in 3D printing
Career in SW development, though herding cats mostly now.

Scanned the issues list but didnt find an obvious match.

Been iterating through a design in inkstitch, from original artwork and been through enough cycles now to get from working at all, to impressive ( to me ) finish on a polo shirt knit.

Using brother embroidery pallet in inkstitch and hand enforced colors from that pallet into all fills and strokes as necessary.

Pdf export is great, everything as it should be and my seven colors listed with matching 3 digit codes as expected in order as can be observed from watching the simulation view ( am I missing a mouse over for color codes there? )

So I know the design is good and consistent within the inkstitch ecosystem.

However I have now confirmed something I only suspected before.

When running the .pes at the machine the color codes are out of order sometimes with a pair swapped.

If I followed the prompting from the se600 machine for the 1st color, it would be wrong. The color reference has been swapped with another from the full order. So I am not getting repeats or random, just straight up swaps.

The stitch order is good, in that as long as I ignore the color ref on the machine and follow that captured in the pdf or by observing simulation, everything is fine.

I cannot yet state if it is always the same swapped or pseudo random.

I am windows or ubuntu based.

What independent pes viewer would you recommend so I can isolate to pre or post pes file generation?

And PS just blown away by how much I can wield this open source. Well done!

**Comment by bigredfrog** [comment] 2021-07-25 17:34
Just loaded into Bernina Artlink 8, I can see in the simulated view, that the colors are indeed swapped in the PES file.

So it does appear to be an error specific to the .pes export pipeline within inkstitch

Here is the output in the pdf export, which is correct. Note that I have underlined the first 4 colors, as in the .pes 3 of these 4 are swapped around.

![goodpdfout](https://user-images.githubusercontent.com/7328740/126908012-4ac29c5f-3d62-4ace-8650-f59062ef0487.png)

Here is an image from the brother se600 panel, and I have marked up what order they should of been in. Note the white (3) is in the correct place, the other 3 of 4 are swapped.

![se600](https://user-images.githubusercontent.com/7328740/126908049-57c84b45-98b3-43e6-832f-f64c64b40f03.png)

Noting the last 3 colors off screen are correct.

**Comment by kaalleen** [comment] 2021-07-29 17:04
Thank you for your report and the images. This is really weird. There has been more about colors in the PES format here: #1105

**Comment by bigredfrog** [comment] 2021-07-29 17:54
Note I am trying to spin up a dev environment so I can start pulling apart the code.

Will take me a while to get to a running build, but once I have hello world, I am pretty good at forensics and post mortem, so I will try and binary chop further.

**Comment by bigredfrog** [comment] 2021-08-04 22:35
I have started to debug this workflow now that I have a decent build on head of main.

First thing I notice when looking at the calls into the ThreadColor __init__ is that we get some very weird rgb values.

Note this is on .PES save as. Exporting to pdf works fine, and all color references are good.

Adding shotgun debug into the __init__ call and I see some very suspicious "almost" values

Colors are sometimes just wrong as well. so lots going on.

08-04 18:26 root         INFO     ThreadColor __init__
08-04 18:26 root         INFO     name: Beige
08-04 18:26 root         INFO     numb: 47
08-04 18:26 root         INFO     manu: Brother
08-04 18:26 root         INFO     rgb : (239.0, 227.0, 184.99999999999997)
08-04 18:26 root         INFO     hex : #EFE3B8

08-04 18:26 root         INFO     ThreadColor __init__
08-04 18:26 root         INFO     name: Flesh Pink
08-04 18:26 root         INFO     numb: 42
08-04 18:26 root         INFO     manu: Brother
08-04 18:26 root         INFO     rgb : (251.17500000000004, 182.32499999999993, 191.8874999999999)
08-04 18:26 root         INFO     hex : #FBB6BF

08-04 18:26 root         INFO     ThreadColor __init__
08-04 18:26 root         INFO     name: White
08-04 18:26 root         INFO     numb: 29
08-04 18:26 root         INFO     manu: Brother
08-04 18:26 root         INFO     rgb : (216.75, 216.75, 216.75)
08-04 18:26 root         INFO     hex : #D8D8D8

08-04 18:26 root         INFO     ThreadColor __init__
08-04 18:26 root         INFO     name: Flesh Pink
08-04 18:26 root         INFO     numb: 57
08-04 18:26 root         INFO     manu: Brother
08-04 18:26 root         INFO     rgb : (255.0, 178.5, 178.5)
08-04 18:26 root         INFO     hex : #FFB2B2

08-04 18:26 root         INFO     ThreadColor __init__
08-04 18:26 root         INFO     name: Black
08-04 18:26 root         INFO     numb: 20
08-04 18:26 root         INFO     manu: Brother
08-04 18:26 root         INFO     rgb : (0.0, 0.0, 0.0)
08-04 18:26 root         INFO     hex : #000000

08-04 18:26 root         INFO     ThreadColor __init__
08-04 18:26 root         INFO     name: Deep Gold
08-04 18:26 root         INFO     numb: 11
08-04 18:26 root         INFO     manu: Brother
08-04 18:26 root         INFO     rgb : (232.0, 169.0, 0.0)
08-04 18:26 root         INFO     hex : #E8A900

08-04 18:26 root         INFO     ThreadColor __init__
08-04 18:26 root         INFO     name: Sky Blue
08-04 18:26 root         INFO     numb: 32
08-04 18:26 root         INFO     manu: Brother
08-04 18:26 root         INFO     rgb : (36.99999999999998, 132.00000000000006, 187.00000000000003)
08-04 18:26 root         INFO     hex : #2484BB

**Comment by lexelby** [comment] 2021-08-05 16:59
Thanks for digging into this!  This might be one of a couple things.

First off, I'll be honest, I never use the brother thread color palette.  I just don't care what the machine says.  On my SE400 I think I disabled the option of showing color names.  So I don't have much experience with this and I'm not surprised at all that we got it wrong.

I have a couple theories on what's going wrong here.  First is that the inkscape palette file for brother thread colors (.gpl extension) that we ship with Ink/Stitch may simply be wrong!  I think this is probably not the case though, since the color numbers and shades seem to match on your se600's screen.

Second possibility: the thread color matching algorithm in Ink/Stitch is wrong.  I still don't think this is it, because again, the colors look about right on your device's screen.

Third possibility, and one I think is likely: we're screwing up in actually writing the PES file.  Here's what's going on.  The thread color names you see in the PDF view actually hasn't no bearing on what gets written to the PES file.  That's just for show.  Ink/Stitch guesses which manufacturer palette you used and assigns color names accordingly.

When it comes down to writing the PES file, pyembroidery does its own, completely separate color matching.  I think this is where the problem is.  Either the PES color palette hardcoded in pyembroidery is wrong, or the color matching algorithm is wrong.  

Without looking at the code, I'm leaning toward the algorithm.  I already found one bug with it that hasn't been fixed yet.

**Comment by bigredfrog** [comment] 2021-08-05 20:14
Yep, only scratched the surface so far, and indeed ,pes export seems to have its own specific failure mode, if pyembroidery workflow is unique to the ,pes export ( vs stitch preview, pdf, simulation ) then the problem is indeed likely there.

**Comment by bigredfrog** [comment] 2021-08-06 01:03
Well thats a rabbit hole.
It looks like pyembroidery does a  color match against a table of thread colors that does not seem to match what current pallet active in inkscape is. I have not yet worked out if that color table with thread names etc is loaded from inkscape in some manner, or hard coded on the pyembroidery side.

There are then some very suspect nearest color changes, though does not fully explain what I see in the final file either.

I also strongly suspect that the brother sewing machine is doing its own color matching and and mapping to 3 digit color numbers, as I don't see those 3 digits code passing through the pes write at all, so I think that is machine side!

I want to work out next where that thread color table actually comes from. See if that is supposed to be the current inkscape active pallet.

**Comment by bigredfrog** [comment] 2021-08-06 01:23
The color table used is indeed hard coded in pyembroidery

EmbThreadPec.py

Its quite a limited set, naming convention does not match the inkstitch Brother Coutry or Brother Embroidery but I am beginning to think this bug hunt is a dead end.

I believe there are maybe three issues.

1) Color set in pyembroidery is hard coded for .pes, rather than taken from the live pallet in inkscape, that would be a hard one to address.
2) Nearest color and color order in pyembroidery may be questionable, I have a Linen being matched to Beige, which ok, is kind of close, but then on the final file its Flesh Pink so I think that pyembroidery has indexing problems on its final color table.
3) The Brother SE600 is doing its best to guess at intended 3 Digit color codes, and its wrong, maybe because the data is already mangled

**Comment by bigredfrog** [comment] 2021-08-06 02:00
Now it concerns me that all the pes output is limited what is coded in EmbThreadPec.py as it mashes colors together which will then look odd if looking at them with a pes viewer, be it back into inkstitch or third party.

The bit I don't know is if pyembroidery decides that two sets of stitches are the same color, due to the enforced nearest color if there is a risk of it removing the thread stop and cut commands inbetween.

**Comment by bigredfrog** [comment] 2021-08-06 02:21
ugg, I did some further chopping, there is somethign wrong with the color indexes in pyembroidery. And it has me perplexed, I will keep scratching another time.

If I have 4 colors in my test set
Beige, Linen, Flesh Pink, Black

What ever they match to nearest color, that should stay the same if I turn sections on and off. They don't

![image](https://user-images.githubusercontent.com/7328740/128446111-ad598cbb-68ca-4b78-b1b2-f571823a0e26.png)

![image](https://user-images.githubusercontent.com/7328740/128446141-05f35ece-c604-47bb-8139-34017bc73dfb.png)

So the common patch in both those images is changing what color it maps to!

I would of thought that should be a constant.

however with added debug, I can see the inputs are the same, but the output is different from the find nearest color

**Comment by bigredfrog** [comment] 2021-08-06 02:46
agghhh, I added debug and the return of find_nearest_color_index is different again! That should not be possible. But it proves the response of find_nearest_color_index is not consistant.

I am officially confused and unplugging for the night.

![image](https://user-images.githubusercontent.com/7328740/128448279-380ce470-c834-435c-98a1-b121ca437970.png)

**Comment by bigredfrog** [comment] 2021-08-06 20:38
OK, this is why color mapping is not deterministic depending on what is active in your export.

In PecWriter.py which is responisble for a lot of the .pes file generation, it uses 

write_pec_header(...)

Which makes a color_index_list in a few steps which is the list of thread colors present in the design.

These are boiled down against the content of EmbThreadPec.py

Which is a hard coded relatively limited set of colors supported by brand / chart Brother. I am pretty sure it is much shorter than modern machines can cope with. It does not contain for example "Linen"

While making the short list ( chart ), once a color has been matched from the full thread_set, the entry in the look up table is set to None

    for thread in set(threadlist):
        index = thread.find_nearest_color_index(thread_set)
        thread_set[index] = None
        chart[index] = thread

This is I am assumind done to prevent different colors in a design from ending up with the same color in the export. To ensure that they are seen as distinct.

Unfortunately this means that a color being matched to true closest is dependant on order of submission. So a perfect color match can be pre-empted by a prior nearest match, and then end up with a poor match to what is left.

This is why sometimes, Beige gets matched to flesh pink, as Linen has already taken the real beige.

And why I have various different mappings above, as order of submission mutates.

A better mechanism would be to work out closest match by distance for all colors in design, then sort the list, then resubmit sorted by distance so the true closest matches get processed first!

This would still not be consistant between exports, depending on number of colors competing. but would preserve true color matches.

**Comment by lexelby** [comment] 2021-08-07 23:12
Oh my, you sure have been busy!

Yes, I think you're into something.  This is a greedy algorithm, and that pre-empting that you describe is a huge weakness.

I think you may also be right that modern machines have a much bigger palette than that PEC color table.  And of course it's still possible that that hardcoded table is wrong...

I do seem to remember that certain versions of the PES format can actually encode arbitrary RGB colors.  I'm on my phone now and can't look at the code, but I want to say maybe it was PES version 6?  I wonder if your machine can read PES v6.

And yeah, my head hurts every time I have to look into PyEmbroidery...

**Comment by bigredfrog** [comment] 2021-08-08 00:49
Looks like there is a reasonable description in 

https://edutechwiki.unige.ch/en/Embroidery_format_PES

I will maybe try to work out exactly what the PES writer is doing for color. If it is saving RGB then it might be worth getting pyembroidery to read in the active pallet from inkstitch and build from that...

Problem I have is lack of general familiarity, so I could implement something that appears to be ok for me, but a disaster for anyone else...

**Comment by lexelby** [comment] 2021-08-08 01:01
Just as a note, that page was written by the person that also wrote most of pyembroidery.

I don't think there's a way for an extension to find out the currently active palette.  In any case, nothing stops the user from selecting colors for multiple different palettes, modifying colors, etc.

**Comment by bigredfrog** [comment] 2021-08-08 01:22
yeah, I feel like this may be a journey to no where with limitations in the PES format and black box behaviour in the specific machine, in this case the SE600

At a minimum, I want to know exactly what the color table looks like that gets written at the end.

I suspect that the final table is mangled closest fit, not the original RGB, which means that the closest matching loses information that could of been embedded in the v6 file. Maybe a v6 PES can hold all the color data at full resolution?

Even as an experiment I might learn something, but my expectation of something useful outside of education is low.

**Comment by bigredfrog** [comment] 2021-08-08 02:02
So it looks like it is running pes version 1 only
Support is in place for pes 6, and may be more capable of carrying color data, but rigth now, the only settings passed in are

ettings: {'translate': Point(-403.27199976012935,-551.7352194121586), 'scale': (2.645833333333333, 2.645833333333333), 'full_jump': True, 'max_jump': 2047, 'max_stitch': 2047, 'sequin_contingency': 246}

and my suspisiion is without a version tag it defaults to version 1

Next hack will be to see if I can stimulatie version 6

**Comment by bigredfrog** [comment] 2021-08-08 02:11
So now I feel a littel dumb, I should of wondered why it was VERSION_1 in the first place.

An initial hack to VERSION_6 makes the result look saner, there are color shifts from matching still, but not so weird. will see what my SE600 thinks next.

**Comment by bigredfrog** [comment] 2021-08-08 02:26
Still haven't tested on machine but all other tests locally reloading the PES look like mapping to the ccolor indexs are much better.

Version 6 does write the original RGB value of the color of the element into the header file, as custom, with no name / brand

It still seems it does color matching later, but need to look at what happens on my SE600 on loading this V6

**Comment by bigredfrog** [comment] 2021-08-08 02:44
viewing PES in belinda looks exactly what it should be...

![image](https://user-images.githubusercontent.com/7328740/128619023-ebf8fef7-5702-4bd9-8054-6915d3a66cff.png)

**Comment by bigredfrog** [comment] 2021-08-08 03:02
Well, thats annoyting, the SE600 is still wrong, I will have to assume that neigher SE600 or Bernina can read custom colors :-( and they fall back to the nearest algorithm, where as pyembroidery can likely read version 6 custom

So the quetion reamins, shuold inkstitch look to call VERSION 6 anyway?....

**Comment by kaalleen** [comment] 2024-01-01 13:36
Closing in favor of #2668

**Closed by kaalleen** 2024-01-01 13:36 UTC
Labels: file format
