### ISSUE TITLE
auto_fill: ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by maliquesonyae** [inkstitch/inkstitch#996] opened 2021-01-26 04:29 UTC
path1365: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 225, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 149, in build_fill_stitch_graph
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

**Comment by kaalleen** [comment] 2021-01-29 17:26
Thank you for reporting your issue. It seems like this error is caused by very small fill shapes in your document. You can easily remove them by running the extension cleanup document (Extensions > Ink/Stitch > Troubleshoot > Cleanup document...). Sorry for your trouble. We hope this error will not show up anymore in the next release.

**Comment by kaalleen** [comment] 2021-02-06 17:06
Duplicate of #734

**Closed by kaalleen** 2021-02-06 17:06 UTC
