### ISSUE TITLE
Bounding box in stitch_plan: ValueError

### ISSUE THREAD

**Issue by simontfs** [inkstitch/inkstitch#2630] opened 2023-12-10 15:52 UTC
This happens when I open an EXP file 

Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "lib\extensions\input.py", line 22, in run
  File "lib\stitch_plan\generate_stitch_plan.py", line 50, in generate_stitch_plan
  File "lib\stitch_plan\stitch_plan.py", line 195, in extents
  File "lib\stitch_plan\stitch_plan.py", line 176, in bounding_box
ValueError: min() arg is an empty sequence

**Comment by kaalleen** [comment] 2023-12-13 05:45
Thank you for reporting this Ink/Stitch bug. In order to solve the issue, we would need to see the exp file. If you cannot upload it publicly to GitHub for copyright reasons, you can upload it here https://lexneva.name/owncloud/index.php/s/NCcJbJqnKmL7nES

**Comment by kaalleen** [comment] 2024-06-02 08:03
I tried to reproduce this error by opening all kinds of exp files. I created one with an empty stitch plan even. But I cannot reproduce the issue. I'm afraid that without more information we won't be able to solve the issue. Therefore I'll close it. If this shows up again, please open a new issue and attach the exp file for inspection.

**Closed by kaalleen** 2024-06-02 08:03 UTC
Labels: bug, needs steps to reproduce
