### ISSUE TITLE
Inkstitch will only param lettering and not shapes above...?

### ISSUE THREAD

**Issue by madmoney21** [inkstitch/inkstitch#2077] opened 2023-02-19 17:26 UTC
I got the following message when trouble shooting:

ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\cleanup.py", line 41, in effect
  File "lib\elements\fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'

![new pm](https://user-images.githubusercontent.com/125821710/219964282-52f8847a-9bb2-42b2-ac24-c7233f9f80cf.svg)

It would only show the lettering being made, not the birds above

Ca

**Comment by kaalleen** [comment] 2023-02-20 16:13
This path here is causing the issue. You can just delete it and it would run through. Maybe you can consider to use various stitch types. It looks whole a lot nicer if not everything is just a plain simple fill.

![2079](https://user-images.githubusercontent.com/36401965/220156081-81ee589c-c06f-40f5-b9a2-b5261f83e968.png)

**Comment by kaalleen** [comment] 2023-02-25 12:52
Duplicate of #1742

**Closed by kaalleen** 2023-02-25 12:52 UTC
