### ISSUE TITLE
fill (geometry) NotImplementedError: Multi-part geometries do not provide a coordinate sequence

### ISSUE THREAD

**Issue by elnonoche** [inkstitch/inkstitch#877] opened 2020-11-06 09:07 UTC
Hello,
here is a new issue: 

File with 3 pathes in one as you can see in the picture joined to this message.
![issue](https://user-images.githubusercontent.com/74045625/98346889-f105f180-2016-11eb-8592-b1adbfe75e56.png)
No gap between the head and page's borders.

NOTE : problem solved doing a 1mm gap on page border

path2357: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 212, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 60, in auto_fill
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 286, in build_travel_graph
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 426, in build_travel_edges
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 375, in travel_grating
  File "D:\a\inkstitch\inkstitch\lib\stitches\fill.py", line 145, in intersect_region_with_grating
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\shapely\geometry\base.py", line 808, in coords
NotImplementedError: Multi-part geometries do not provide a coordinate sequence

Thank you !

**Comment by lexelby** [comment] 2020-11-07 01:09
Oooh, that's interesting.  I hadn't made the connection between this error message and the page border.  Thank you!

**Comment by kaalleen** [comment] 2020-12-03 20:15
This is a duplicate of #804 
Therefore I will close this issue. Please reopen if necessary.

**Comment by elnonoche** [comment] 2020-12-03 21:26
Hello,ok Thankselnonoche

    Le jeudi 3 décembre 2020 à 21:15:19 UTC+1, Kaalleen <notifications@github.com> a écrit :  
 
 


Closed #877.

**Comment by kaalleen** [comment] 2021-05-04 16:23
@elnonoche Could you run a test if this is still an issue with the newest version (v2.0.0)?
That'd be great!

**Comment by elnonoche** [comment] 2021-05-04 21:00
Hello, never had the problem again, sorry 😕

**Comment by kaalleen** [comment] 2021-05-14 17:07
Maybe that is a good thing?!?
Well then, let's finally close this issue for now and wait for someone to report it again (if it is still out there).

**Closed by kaalleen** 2021-05-14 17:07 UTC
Labels: bug
