### ISSUE TITLE
fill: ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by alloutgraphix** [inkstitch/inkstitch#975] opened 2021-01-14 15:43 UTC
path28632: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 225, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 149, in build_fill_stitch_graph
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

**Comment by kaalleen** [comment] 2021-01-16 21:58
This is caused by very small fill areas. It is causing a lot of trouble lately and will be fixed in the next release.
You could try to remove small fill areas with the extension under Extensions > Ink/Stich > Troubleshoot > Cleanup Document ...

**Comment by kaalleen** [comment] 2021-02-06 17:07
Duplicate of #734

**Closed by kaalleen** 2021-02-06 17:07 UTC
