### ISSUE TITLE
Error during Params usage

### ISSUE THREAD

**Issue by blind-newb** [inkstitch/inkstitch#3284] opened 2024-11-10 17:06 UTC
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues/new

Include the error description and also (if possible) the svg file.

Windows 10 version: 10.0.19045

Ink/Stitch Version: v3.1.0 (windows) 2024-07-27 09:04

Traceback (most recent call last):
  File "lib\elements\element.py", line 641, in handle_unexpected_exceptions
  File "lib\elements\element.py", line 605, in embroider
  File "lib\elements\fill_stitch.py", line 961, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 1044, in do_auto_fill
  File "lib\debug\debug.py", line 166, in decorated
  File "lib\stitches\auto_fill.py", line 116, in auto_fill
  File "lib\debug\debug.py", line 166, in decorated
  File "lib\stitches\auto_fill.py", line 929, in path_to_stitches
TypeError: 'NoneType' object is not iterable

**Comment by blind-newb** [comment] 2024-11-14 01:15
Yes, I still have the file, I have modified it to get it to work, it turns
out it was an issue with the Path > Trace Bitmap function where it was
putting duplicate path points into the image, thus it was causing
overlapping issues.

For instance, when I traced the image, it would get anywhere between 3 and
8 duplicates of the same item.
The original PNG file which I was digitizing, is attached.

Steps to reproduce the error:
1. Document Properties > Set frame size as 7"x5" / 177.800mm x 127.000mm
2. Drag and Drop PNG file into InkScape
3. Press Ctrl key while resizing to fit frame size (uniform resizing)
4. Selected Image
5. Path > Trace Bitmap
*Single Scan*
    • Detection Mode = Brightness Cutoff
    • Threshold = 0.450
    • Speckle = 2 (Checked)
    • Smooth Corners = 1.00 (Checked)
    • Optimize = 0.200 (Checked)
    • User-Assisted Trace (UNCHECKED)
6. Added Fill Layer
7. Moved bitmap path to fill layer
8. Selected path within fill layer
9. Ran params received errors

Deleted Path and tried repeating Step 5 using *MultiColor*
    • Detection Mode = Colors
    • Scans = 8 (1 for each color)
    • Speckle = 2 (Checked)
    • Smooth Corners = 1.00 (Checked)
    • Optimize = 0.200 (Checked)
    • User-Assisted Trace (UNCHECKED)

Repeated Steps 7, 8, 9
Same Error

**Comment by kaalleen** [comment] 2024-11-16 21:32
Thank you for the detailed report. GitHub doesn't take mail attachments. Can you upload the file directly to GitHub? It would be very helpful to be able to have a look at it.

**Comment by kaalleen** [comment] 2024-11-27 16:35
Closing as duplicate of #3223

**Closed by kaalleen** 2024-11-27 16:35 UTC
Labels: svg file missing

**Comment by blind-newb** [comment] 2024-11-27 17:01
I do not know how to upload directly to GitHub, this is why I sent it
via email
