### ISSUE TITLE
not sure what happed on here but the app said to copy the error message 

### ISSUE THREAD

**Issue by jaygar1999** [inkstitch/inkstitch#2019] opened 2023-01-19 05:00 UTC
nk/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v2.2.0 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 231, in run
  File "lib/extensions/stitch_plan_preview.py", line 39, in effect
  File "lib/extensions/base.py", line 200, in elements_to_stitch_groups
  File "lib/elements/element.py", line 329, in embroider
  File "lib/elements/element.py", line 387, in validate
  File "lib/elements/fill_stitch.py", line 321, in validation_errors
  File "lib/elements/fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'

**Comment by kaalleen** [comment] 2023-01-19 16:10
There are little tiny objects in your document which are too small to be filled with a fill stitch. Please remove them.
In a next version of Ink/Stitch this error won't show up, but it is still recommended to work with a clean document.

**Comment by kaalleen** [comment] 2023-02-25 13:27
Duplicate of #1742

**Closed by kaalleen** 2023-02-25 13:27 UTC
