### ISSUE TITLE
auto_fill: ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by boblyns** [inkstitch/inkstitch#1045] opened 2021-02-18 20:27 UTC
id_111901746d6a774148800bb6ef6f3a98_e0: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 225, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 149, in build_fill_stitch_graph
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

**Comment by kaalleen** [comment] 2021-02-20 20:32
Thanks for reporting your issue. We think this issue will not be present in the next release. Until then you will have to remove very small fill objects (which are too small to be stitched anyway). In order to do that you can use a function which can be found here: Extensions > Ink/Stitch > Troubleshoot > Cleanup document...

Hope this will be of help.

**Comment by kaalleen** [comment] 2021-03-06 13:11
This is a duplicate of #734. I will close this issue now. Please reopen if it is still needed.

**Closed by kaalleen** 2021-03-06 13:11 UTC
