### ISSUE TITLE
No export, pdf, electron.... with actual dev versions

### ISSUE THREAD

**Issue by bianchifan** [inkstitch/inkstitch#2741] opened 2024-02-25 11:05 UTC
Last year I opened an issue with electron problems [https://github.com/inkstitch/inkstitch/issues/2539]
Still same behavior with my new(old) Dell XPS 13/15, no PDF export possible with Inkstitch v 3.01!

Today I tried the two most actual dev versions.
No PDF export, no more Simulator,  no more SAve as..

For this issue I used my current XPS 13 Ultrabook with Linux Mint installed
(Ubuntu does run but its toooo snappy)

System:
![i7-8550-Cinnamon_21 3](https://github.com/inkstitch/inkstitch/assets/17491743/883b341b-25fd-46ba-9248-7463f1ca1dee)

actual dev version:
![InkStitch Version](https://github.com/inkstitch/inkstitch/assets/17491743/d2913bc5-2880-4c6e-b041-230a4eb6fb1d)

CPU usage when trying to export a PDF for my Burning Swan SVG:
![cpu_Burning Swan](https://github.com/inkstitch/inkstitch/assets/17491743/8160aa94-b1da-40d9-bf90-a42db0d8196f)

CPU usage same Proc for My Gecko SVG, a tiny one
![CPU Gecko](https://github.com/inkstitch/inkstitch/assets/17491743/0847e949-5228-45da-8098-2e4c2ad2f143)

InkStich failure when trying to simulate - every SVG, every format
![Simulator](https://github.com/inkstitch/inkstitch/assets/17491743/eafb2b24-dec1-4f14-ab2c-0d2baa843697)

InkStich failure when trying to save as.. - every SVG, every format
![Save as](https://github.com/inkstitch/inkstitch/assets/17491743/94198ad6-a660-42df-8df9-3d31cde2acdc)

And here is my Gecko..
![gecko](https://github.com/inkstitch/inkstitch/assets/17491743/9d1bc69a-e542-48a2-8c56-847fc2558b30)

**Comment by bianchifan** [comment] 2024-02-25 13:56
I just spent my system a separate partition with a freshly installed Ubuntu 23.10 + current Inkscape

Most SVG are working fine, i.e. my Gecko above

But some do not, i.e. my Burning Swan.
Sometimes not responding.. (PDF/Simulator)
![Bildschirmfoto vom 2024-02-25 14-24-58](https://github.com/inkstitch/inkstitch/assets/17491743/a2d9cad1-7669-403e-8ff3-15d3f5ef9f7f)

sometimes crashing (Simulator)
![Bildschirmfoto vom 2024-02-25 14-14-48](https://github.com/inkstitch/inkstitch/assets/17491743/5a722872-9492-43e2-ac1c-95f66b1e7ddb)

or when trying to save as
![Bildschirmfoto vom 2024-02-25 14-26-26](https://github.com/inkstitch/inkstitch/assets/17491743/4b45d38b-c1ea-4085-b027-b74fb7d43a3d)

**Comment by kaalleen** [comment] 2024-03-03 19:15
I'm still not able to reproduce the error with your swan.
Can you try to narrow the issue down on specific elements in the document (#2538)?

**Comment by bianchifan** [comment] 2024-04-09 18:26
I wiped out the SSD of my XPS 13 from scratch with the UEFI Firmware in UEFI mode.., at least 13 partitons.

1. Trisquel could be installed easily but does not run due to lack of "free" WLAN drivers (closed firmware is nneded)
2. Ubuntu fresh install works so far, Inkscape runs perfect, InkStitch not :(
3. Same with Linux Mint 21.3
4. Same with Suse Tumbleweed

The tools section (Fills, Strike, Satin) seems to work, but when when stitches should be generated/simlated a database error occurs.
![Bildschirmfoto vom 2024-04-09 20-18-59](https://github.com/inkstitch/inkstitch/assets/17491743/9a04a58e-a73c-4094-a073-40463c5188c6)

Maybe caused by the GPU driver... on my old Dell Studio XPS 1340 InkStitch works fine!
( My XPS 15 is still disassembled)

**Comment by kaalleen** [comment] 2024-04-29 08:01
Closing as electron is not going to be included in the next release anymore.

**Closed by kaalleen** 2024-04-29 08:01 UTC
