### ISSUE TITLE
Inkstitch

### ISSUE THREAD

**Issue by dominiquewilliams01** [inkstitch/inkstitch#2267] opened 2023-05-03 07:19 UTC
Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\cleanup.py", line 41, in effect
  File "lib\elements\fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'
![Sunset Bay 10cm](https://user-images.githubusercontent.com/132435614/235853606-f836ab24-4672-4c83-9f8a-3b36a4e00db9.svg)

**Comment by kaalleen** [comment] 2023-05-06 16:50
Remove path3098 from your document.
For the fonts you'll possibly have a nicer stitch out, if you put some more work into it and use a satin column for them (or the smaller parts could even go as a running stitch).

**Comment by kaalleen** [comment] 2023-05-15 21:30
Duplicate of https://github.com/inkstitch/inkstitch/issues/1742

**Closed by kaalleen** 2023-05-15 21:30 UTC
