### ISSUE TITLE
Cant export To embroidery file

### ISSUE THREAD

**Issue by bigblakzach** [inkstitch/inkstitch#810] opened 2020-09-04 01:38 UTC
Hello, ive look an many tutorial to finish my design and i did it!! Thank you guys. But my only problem is that when i finish up and get ready to export i get the “ error writing to ./drawing .dst :Read-only file system! 

Please help, 
Appreciate all you guys do. 
Zach

**Comment by ecc521** [comment] 2020-09-08 02:34
I'm encountering this issue too, however it is technically a duplicate of #773, although the issue name could have been a bit cleaner. The bug here is not related to the file type, and can be reproduced with multiple export options. 

I'm not seeing a clear development setup for this project, however if I'm able to get it working, I'll look at trying to make a fix. It's pretty clearly a filesystem write issue, and I suspect it has something to do with new Catalina restrictions (I'm assuming MacOS, not enough info in bug report), and a dependency attempting to access restricted folders.

**Comment by ecc521** [comment] 2020-09-08 03:26
Ok. I've diagnosed the issue. 
<img width="388" alt="Screen Shot 2020-09-07 at 11 25 31 PM" src="https://user-images.githubusercontent.com/42424091/92429931-6d886b00-f161-11ea-894a-fdabfd7cbfa9.png">
There is clearly a bug related to the usage of relative paths. Specifying a directory in this field fixed the issue.

**Comment by annoyingproblem** [comment] 2020-11-03 19:05
yes this worked perfectly, a little hard to see where the file will end up,  but worked! thanks so much

**Closed** 2021-05-04 18:26 UTC
