### ISSUE TITLE
WindowsError [Error 2]

### ISSUE THREAD

**Issue by frveres** [inkstitch/inkstitch#559] opened 2019-10-22 18:08 UTC
Finally managed to get inkstitch to work once and now this error comes up everytime. Made a few different .ai files to try, can't get embroider to work. This keeps coming up. Uninstalled/reinstalled inkscape once. Also saw there was a previous question with a similar error but didn't see a solution in the thread. Please Advise! Thank you!

> Tried to launch: inkstitch\bin\inkstitch
> Arguments: ['inkstitch\\bin\\inkstitch', '--collapse_len_mm=3', '--hide_layers=true', '--output_format=pes', '--extension=embroider', 'C:\\Users\\19518\\AppData\\Local\\Temp\\ink_ext_XXXXXX.svg2DCP9Z']
> Debugging information:
> 
> Traceback (most recent call last):
>   File "inkstitch.py", line 35, in <module>
>     extension = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
>   File "C:\Program Files\WindowsApps\25415Inkscape.Inkscape_0.92.4.0_x64__9waqn51p1ttv2\VFS\ProgramFilesX64\Inkscape\lib\python2.7/subprocess.py", line 325, in __init__
>     errread, errwrite)
>   File "C:\Program Files\WindowsApps\25415Inkscape.Inkscape_0.92.4.0_x64__9waqn51p1ttv2\VFS\ProgramFilesX64\Inkscape\lib\python2.7/subprocess.py", line 575, in _execute_child
>     startupinfo)
> WindowsError: [Error 2] The system cannot find the file specified

**Comment by frveres** [comment] 2019-11-03 22:08
someone? please help

**Comment by iampen** [comment] 2019-11-09 01:46
Hi! I have just encountered this error after having successfully saved an embroidery files a number of times in the last few days.

**Comment by kaalleen** [comment] 2020-03-31 16:46
This problem is most commonly caused by your virus software. It somehow likes to delete Ink/Stitch files. Could you try to white list the Ink/Stitch folder to prevent it from being deleted?

**Comment by kaalleen** [comment] 2020-04-10 07:47
Duplicate of #613 
Closing the issue now. Please report further issues on this matter there.

**Closed by kaalleen** 2020-04-10 07:47 UTC
