### ISSUE TITLE
ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by Deanna1010** [inkstitch/inkstitch#1014] opened 2021-02-02 11:24 UTC
Hi so I'm trying to save my file as a PES and this message keeps coming up. What do I do? 
HELPPPPPP

path2254: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/auto_fill.py", line 212, in to_patches
  File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 55, in auto_fill
  File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 149, in build_fill_stitch_graph
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

**Comment by kaalleen** [comment] 2021-02-03 17:25
This error is caused by very small fill shapes. Try to run `Extensions > Ink/Stitch > Troubleshoot > Cleanup document...`

**Comment by kaalleen** [comment] 2021-02-06 17:05
Duplicate of #734

**Closed by kaalleen** 2021-02-06 17:05 UTC
