### ISSUE TITLE
auto_fill: ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by stitchbitxh** [inkstitch/inkstitch#944] opened 2020-12-26 20:19 UTC
path2843_2: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/auto_fill.py", line 212, in to_patches
  File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 55, in auto_fill
  File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 149, in build_fill_stitch_graph
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/SocketServer.py", line 599, in process_request_thread
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/SocketServer.py", line 334, in finish_request
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/SocketServer.py", line 655, in __init__
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/werkzeug/serving.py", line 329, in handle
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/BaseHTTPServer.py", line 340, in handle
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/werkzeug/serving.py", line 364, in handle_one_request
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/werkzeug/serving.py", line 306, in run_wsgi
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/werkzeug/serving.py", line 294, in execute
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
  File "/Users/runner/work/inkstitch/inkstitch/lib/api/stitch_plan.py", line 14, in get_stitch_plan
  File "/Users/runner/work/inkstitch/inkstitch/lib/extensions/base.py", line 194, in elements_to_patches
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/element.py", line 329, in embroider
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/auto_fill.py", line 240, in to_patches
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/element.py", line 353, in fatal
SystemExit: 1

**Comment by kaalleen** [comment] 2020-12-29 14:26
Thanks for reporting your issue. We have recently (hoepfully) fixed the bug and it should be fine in the next release.

For now watch out for very small objects in your document. They seem to cause the error.

**Comment by kaalleen** [comment] 2021-01-17 11:51
Duplicate of #734

**Closed by kaalleen** 2021-01-17 11:51 UTC
