### ISSUE TITLE
stitch_plan: IndexError: list index out of range

### ISSUE THREAD

**Issue by Examann** [inkstitch/inkstitch#1226] opened 2021-05-30 06:09 UTC
I am using Windows 10, 64 bit, and I just installed Inkscape/inkstich. I was able to save the first file that I made as the default .svg file but when I tried to save as a .pes file I got this error message:

Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\stitch_plan\stitch_plan.py", line 26, in patches_to_stitch_plan
IndexError: list index out of range

I encountered another error when trying to use "params"

tspan961: error: Object tspan961 has an empty 'd' attribute.  Please delete this object from your document.

Please help. 
Thanks
Examann

**Comment by kaalleen** [comment] 2021-05-30 06:55
Thanks for reporting your issue. We hear about it often since the new version, but we haven't been able to receive a svg file which is causing the issue. If you would be able to send us your file, we would pretty much appreciate it. You will need to put your file into a zip-archive to upload it here. svg files are sadly not excepted as a direct upload.

Our recent guess for this error would be, that there is no embroiderable object in the file (e.g only images or text). Can you check your file if that is true (in case you cannot or don't want to upload your svg file)?

**Comment by Examann** [comment] 2021-05-30 13:41
Yes,  I believe that you're right. I tried making my first ambroidery image and I thought that just starting with text would be the easiest way to do it. I did not prepare the text using the steps outlined in your instructional video initially,  with the separation of letters,  then union. Once I did,  I was able to save the .pes file. Initially I followed the instructions for an image file and got the error that I submitted. I can send you all the files,  if you want. 
David

Sent from Yahoo Mail on Android 
 
  On Sun., 30 May 2021 at 2:55, ***@***.***> wrote:   


Thanks for reporting your issue. We hear about it often since the new version, but we haven't been able to receive a svg file which is causing the issue. If you would be able to send us your file, we would pretty much appreciate it. You will need to put your file into a zip-archive to upload it here. svg files are sadly not excepted as a direct upload.

Our recent guess for this error would be, that there is no embroiderable object in the file (e.g only images or text). Can you check your file if that is true (in case you cannot or don't want to upload your svg file)?

**Comment by Examann** [comment] 2021-05-30 19:28
[Ardman.zip](https://github.com/inkstitch/inkstitch/files/6566798/Ardman.zip)
here is the .svg file
Thanks for helping.

**Comment by kaalleen** [comment] 2021-05-30 19:34
Great thanks for your detailed answer and the file. In the next version we will need to give a proper warning if there is no embroiderable objects in the file. You just confirmed my guess for what is going wrong when this error message occurs.

If you need to know anything else to get started with Ink/Stitch please don't hesitate asking. We are happy to help ;)

**Comment by kaalleen** [comment] 2021-06-01 09:30
Closing this in favor of #1199

**Closed by kaalleen** 2021-06-01 09:30 UTC
