### ISSUE TITLE
stitch_plan: ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by kasquaredesign** [inkstitch/inkstitch#1099] opened 2021-03-23 09:40 UTC
Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "D:\a\inkstitch\inkstitch\lib\extensions\input.py", line 40, in affect
  File "D:\a\inkstitch\inkstitch\lib\stitch_plan\stitch_plan.py", line 147, in extents
  File "D:\a\inkstitch\inkstitch\lib\stitch_plan\stitch_plan.py", line 133, in bounding_box
ValueError: min() arg is an empty sequence

I installed Python on Windows 10:
C:\Users\a>python --version
Python 3.9.2

C:\Users\a>python -m pip --version
pip 20.2.3 from C:\Users\a\AppData\Local\Programs\Python\Python39\lib\site-packages\pip (python 3.9)

**Comment by kaalleen** [comment] 2021-03-23 16:32
Thanks for reporting your error and sorry you are having trouble with Ink/Stitch.
It would be very interesting to have a look at your svg file.
Is it possibe for you to upload it here?

**Comment by kaalleen** [comment] 2021-05-18 16:10
Duplicate of #1217

**Closed by kaalleen** 2021-05-18 16:10 UTC
Labels: bug
