### ISSUE TITLE
file will not save as pes 

### ISSUE THREAD

**Issue by ktowens** [inkstitch/inkstitch#2203] opened 2023-04-07 17:33 UTC
I am new to inkscape and ink/stitch. My svg file will not save as a pes file. I took out the small details I had and I did the cleanup from the ink/stitch extension and I still got this error message.

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 231, in run
  File "lib/extensions/output.py", line 56, in effect
  File "lib/extensions/base.py", line 200, in elements_to_stitch_groups
  File "lib/elements/element.py", line 329, in embroider
  File "lib/elements/element.py", line 387, in validate
  File "lib/elements/fill_stitch.py", line 321, in validation_errors
  File "lib/elements/fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'

![daisy](https://user-images.githubusercontent.com/130175110/230651939-ec616abe-d16c-434d-8044-70397c26eaa9.svg)

**Comment by tyrosinase** [comment] 2023-04-07 18:06
You've still got at least one oddball object: if you select Layer 13 and tab through the objects, you'll see the lower bar pop up with a 2-node item, a B-spline that has both fill and outline. If you delete that, it'll export (though you've still got a lot of cleanup to do, including more objects with extraneous outlines, shapes that need converted to satins, fill angle tweaking, etc. so don't stitch it out yet).

**Comment by kaalleen** [comment] 2023-05-15 21:29
Duplicate of https://github.com/inkstitch/inkstitch/issues/1742

**Closed by kaalleen** 2023-05-15 21:29 UTC
