### ISSUE TITLE
Satin Stitch: NetworkXUnfeasible

### ISSUE THREAD

**Issue by jayjaychan** [inkstitch/inkstitch#876] opened 2020-11-05 19:38 UTC
Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\inkstitch.py", line 44, in <module>
  File "D:\a\inkstitch\inkstitch\inkscape\share\extensions\inkex.py", line 283, in affect
  File "D:\a\inkstitch\inkstitch\lib\extensions\auto_satin.py", line 54, in effect
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_satin.py", line 316, in auto_satin
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_satin.py", line 456, in add_jumps
  File "C:\hostedtoolcache\windows\Python\2.7.18\x86\lib\site-packages\networkx\algorithms\connectivity\edge_augmentation.py", line 264, in k_edge_augmentation
NetworkXUnfeasible: impossible to 1 connect in graph with less than 2 nodes

Thats the pop up that showed up to add here

**Comment by kaalleen** [comment] 2020-12-20 20:30
Sorry for the late answer and for you having trouble using Ink/Stitch.
I know it's a while ago and you might not have the SVG file which is causing the error. If you still have it - it would be great if we could have a look at it (if there are no copyright restrictions).

**Comment by kaalleen** [comment] 2021-04-08 15:52
Duplicate of #1056

**Closed by kaalleen** 2021-04-08 15:52 UTC
