### ISSUE TITLE
Params working, export not

### ISSUE THREAD

**Issue by c0ati** [inkstitch/inkstitch#840] opened 2020-10-02 22:44 UTC
EDIT
I somehow fixed it since I was able to export to .pes
not sure if this is needed anymore

path21514: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 212, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 149, in build_fill_stitch_graph
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

I got this error while trying to export/save as a .pes file. The Params option was able to run the simulation fine, but it cannot be exported?

**Comment by kaalleen** [comment] 2020-10-04 12:01
> not sure if this is needed anymore

We still appreciate any bug report ;)

This one, is a duplicate and I will close the issue. We will be working on it.

Duplicate of #734

**Closed by kaalleen** 2020-10-04 12:01 UTC
