### ISSUE TITLE
Path4824 error; error during autofill!

### ISSUE THREAD

**Issue by nicki4564** [inkstitch/inkstitch#982] opened 2021-01-17 12:30 UTC
path4824: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 212, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 149, in build_fill_stitch_graph
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

**Comment by kaalleen** [comment] 2021-01-18 17:49
Have a look at this comment. I hope it will help you to avoid this issue for now: [#734](https://github.com/inkstitch/inkstitch/issues/734#issuecomment-738258066)

I will close this issue since it is a duplicate of #734
The issue will be fixed in the next release. Thank you for reporting it back to us.

**Closed by kaalleen** 2021-01-18 17:49 UTC
