### ISSUE TITLE
PDF output does not work in all cases

### ISSUE THREAD

**Issue by bianchifan** [inkstitch/inkstitch#2993] opened 2024-06-14 08:35 UTC
I checked the new PDF output with a couple of my SVGs, in most cases it runs fine, but sometimes not.
I.e. my old problem cases black and white burning swans do not produce any output, the CPU runs some seconds, than nothing...
![no PDF output](https://github.com/inkstitch/inkstitch/assets/17491743/2bac5eda-72f7-49ba-8c0f-0659338318bf)
[Burning Black Swan.svg.zip](https://github.com/user-attachments/files/15835158/Burning.Black.Swan.svg.zip)

In several cases no realistic preview is possible, the connection to InkStitch will brake
![no realistic pdf](https://github.com/inkstitch/inkstitch/assets/17491743/c7139029-d6c4-478a-b66e-93d59ca375b8)
[Burning Swan.svg.zip](https://github.com/user-attachments/files/15835159/Burning.Swan.svg.zip)

**Comment by kaalleen** [comment] 2024-06-14 20:21
Oh no. I cannot replicate the case that it doesn't start up at all. But I can very well brake the connection when I click on realistic preview. I wonder what makes it crash though.

**Comment by capellancitizen** [comment] 2024-06-17 01:29
```2024-06-16 21:24:27,042 (+0:00:01.335742) got a ping
2024-06-16 21:24:32,653 (+0:00:05.610778) got a ping
2024-06-16 21:24:33,679 (+0:00:01.026040) got a ping
```

Looks like if you tick on realistic it can sometimes take a while to get the next ping, and currently the timeout is just 3s. Quick and dirty solution might be to just bump the timeout, 3s is a very strict deadline. I'll take a stab at dxing it further.

**Comment by kaalleen** [comment] 2024-06-17 05:07
Yes right, I already made a branch to increase the time for the timeout. It sets it to 10, but that's still not enough. I don't see any problem when I raise it further up anymore. So that can be fixed.
I still don't know why it would crash though and couldn't reproduce neither. Can you?

**Comment by capellancitizen** [comment] 2024-06-17 05:10
More detail: Issue is basically client-side, when we render the realistic stitch preview to a raster image in-browser (`image.onload` in `inkstitch.js`) that can take longer than the three second timeout, and because that blocks the main thread it can't send pings and the server times out and closes. Some options:
- Change the realistic overview and color block methods to return rasterized versions, given we have a way to do that now in the realistic preview code.
- Move the rasterization on the browser into a web worker to free up the main thread to keep pinging
- Increase the timeout or suspend it for a bit when the realistic overview is fetched, which is hacky but arguably okay when the timeout is really just there to catch when the PDF preview tab has been closed...

**Comment by capellancitizen** [comment] 2024-06-17 05:27
A timeout of 15s was suitable on my (virtual) machine, with the time between pings going up to 5s. Slower machines might take longer of course, though 10s seems like a lot of time between pings. If you'd like to provide some info, if you could turn on your browser's javascript profiler, then tick the 'realistic' box, then finish profiling after the realistic stitch renders out, that should tell us why it didn't ping during that time. If you have Firefox you can click on "upload local profile" to download the profiler information to attach it to the thread if you want.

 If we go the route of serving up rasterized realistic images it might still be a good idea to make the timeout more lenient anyway. Maybe making sure that the timeout doesn't run while there are any active requests...

**Comment by kaalleen** [comment] 2024-06-17 15:04
I wouldn't do too much about it. The print pdf as it is now won't stay like that forever. Plans are to open it in an other inkscape instance. So it will need a complete rewrite anyway. I only want to prevent it from crashing and breaking the connection before it should. So lengthen the time would be just fine. If you want to dig deeper you are welcome though... that'd be the robust way to do it.

**Comment by kaalleen** [comment] 2024-06-17 15:06
But from your answer I think, that it won't crash on you neither... @bianchifan can you discover some rules about when it crashes and doesn't load at all?

**Comment by capellancitizen** [comment] 2024-06-18 01:44
(I wasn't able to replicate the extension crashing either.)

**Comment by kaalleen** [comment] 2024-06-20 16:01
I'm going to close the issue. Since @capellancitizen merged a fix.

@bianchifan can you test one of the most recent release versions and see if your issue has been fixed?

**Closed by kaalleen** 2024-06-20 16:01 UTC
Labels: bug, print

**Comment by bianchifan** [comment] 2024-06-20 19:15
> @bianchifan can you test one of the most recent release versions and see if your issue has been fixed?

Partially..
A Q&D test yesterday evening did not show any message but I couldn't change anything..
no realistic, no color palette, no printing
The communication"??" window was shown for only 2 or 3 seconds.
Nevertheless Printing possible via browser function

**Comment by kaalleen** [comment] 2024-06-21 14:48
Sounds as if you caught the branch in the bad stage where an update was still missing.
Keep us updated. Since this has been merged, you can also try newer dev branches. The fix should be in there.

**Comment by bianchifan** [comment] 2024-06-25 09:39
I've tested with pdf-ping-worker;)
Last night I checked two more branches..
update-pyembroidery: works ~10s, no result
visible-on-background: seems to work :), but I have to test it with more svgs
