### ISSUE TITLE
Inkscape - Adding pre-digitized fonts to inkstitch lettering tool.

### ISSUE THREAD

**Issue by Macey2000** [inkstitch/inkstitch#2816] opened 2024-03-31 17:56 UTC
I have followed the tutorial on how to add a pre digitised font to inkstitch lettering tool. The font is showing on the lettering tool but is not showing a preview and showing the following Traceback error:

Inkscape has received additional data from the script executed. The script did not return an error but the results may not be as expected. 

Traceback (most recent call last):
  File "lib\extensions\lettering.py", line 328, in apply
  File "lib\extensions\lettering.py", line 273, in update_lettering
  File "lib\lettering\font.py", line 184, in render_text
  File "lib\lettering\font.py", line 106, in _load_variants
  File "lib\lettering\font_variant.py", line 60, in __init__
  File "lib\lettering\font_variant.py", line 72, in _load_glyphs
  File "lib\lettering\glyph.py", line 40, in __init__
  File "lib\lettering\glyph.py", line 86, in _process_bbox
ValueError: min() arg is an empty sequence

My custom font directory is 2024\Embroidery\Inkscape Fonts
My JSON file is named the same as my font and picked up the arrow file in the same font directory. 

![Screenshot 2024-03-31 185404](https://github.com/inkstitch/inkstitch/assets/165584397/0803e982-69e2-48ff-b70d-7acec0ec201e)
![Screenshot 2024-03-31 185114](https://github.com/inkstitch/inkstitch/assets/165584397/7172c005-13a0-4675-8448-d076c7d7a807)

**Comment by tyrosinase** [comment] 2024-03-31 20:42
Oh, I know this one! It's the same thing I reported in #2550, which is fixed in #2551 (but not yet in a current release). It's caused by an empty layer; if you want to upgrade to a release with the fix it'll be able to detect it for you, but if you don't I'm going to guess the problem is `Layer1` based on the screenshot.

**Closed by tyrosinase** 2024-03-31 20:42 UTC
