### ISSUE TITLE
ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by RhyssM** [inkstitch/inkstitch#974] opened 2021-01-10 01:46 UTC
path159: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/auto_fill.py", line 225, in to_patches
  File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 55, in auto_fill
  File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 149, in build_fill_stitch_graph
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

**Comment by kaalleen** [comment] 2021-01-10 09:59
Thanks for your report. We have seen it a lot. We hope this will be fixed in the net release.
Until then try to trace down very small fill objects and remove them from your document.
Maybe the extension under Extensions > Ink/Stitch > Troubleshoot > Cleanup Document ... will be of help.

**Comment by kaalleen** [comment] 2021-01-17 11:53
Duplicate of #734

**Closed by kaalleen** 2021-01-17 11:53 UTC
