### ISSUE TITLE
inkscape

### ISSUE THREAD

**Issue by arnoldzack** [inkstitch/inkstitch#1276] opened 2021-07-16 03:11 UTC

**Comment by arnoldzack** [comment] 2021-07-16 03:11
Ink/Stitch Version: v2.0.0 (windows) Traceback (most recent call last): File "inkstitch.py", line 52, in <module> File "inkex\base.py", line 141, in run File "lib\extensions\params.py", line 626, in effect File "lib\extensions\params.py", line 340, in __init__ File "lib\extensions\params.py", line 606, in create_tabs File "lib\extensions\params.py", line 69, in __init__ wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(0, 0), "C") == 0" failed at ..\..\src\common\intl.cpp(1694) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale. Things are going to break, please only change locale by creating wxLocale objects to avoid this!

**Comment by kaalleen** [comment] 2021-07-17 07:13
Thank you for your error report! We really appreciate any kind of bug report since it helps us to make Ink/Stitch better.
Your issue has been reported earlier to us. Have a look at this issue here: #1242

**Comment by kaalleen** [comment] 2021-07-19 07:08
Duplicate of #1232

**Closed by kaalleen** 2021-07-19 07:08 UTC
