### ISSUE TITLE
AutoFill: ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by suehle** [inkstitch/inkstitch#889] opened 2020-11-15 22:01 UTC
Saving a basic blend test failed:

path5315: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "/home/runner/work/inkstitch/inkstitch/lib/elements/auto_fill.py", line 225, in to_patches
  File "/home/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/home/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 55, in auto_fill
  File "/home/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/home/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 149, in build_fill_stitch_graph
  File "/home/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

**Comment by suehle** [comment] 2020-11-15 22:05
Resolved problem by deleting guides on the page and moving the image over a bit.

**Comment by kaalleen** [comment] 2020-12-03 20:03
Huh, interesting this would solve the error. We think this error is usually caused by tiny elements in the document.
Do you still have a copy of the corrupted file? If there are no copyright restrictions it could be useful for us to have a look at it.

**Comment by kaalleen** [comment] 2020-12-03 20:04
Just as a note to myself:
Duplicate of #734

**Closed** 2021-01-17 11:49 UTC
