### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by danielkschneider** [inkstitch/inkstitch#167] opened 2018-05-24 15:44 UTC
Hi (sorry, not a real issue)

I made some tutorial. If you like it, you can add it to your help page. SVG files are also there for download.

https://edutechwiki.unige.ch/en/InkStitch

Plans: I will improve this in the future and then probably split into several smaller pages.

Attached a snapshot of the page
[InkStitch.pdf](https://github.com/lexelby/inkstitch/files/2036060/InkStitch.pdf)

Thanx for this extension. It is the first open source embroidery program I like :)

- greetings Daniel

PS: I do describe some glitches in the page (tested with version 1.7). In particular: PES files are sometimes wrong (workaround is to use DST). Sometimes some extra stitch sections appear (not harmful). It would be nice to be able to create satin stitches from fat strokes. Finally, the wiki is open for writing, but signing up is difficult (because of vandalism).

**Comment by lexelby** [comment] 2018-05-24 16:27
Wow, this is incredible!! Thank you so much for all the time and effort you've put into this!  If it's okay with you, we may want to integrate some or all of your documentation into the project's official docs.  We're currently actively involved in (re)writing and organizing our docs.  cc @kaalleen @X3msnake 

> sorry, not a real issue

No problem!  We use issues for discussion too.  I've added the `ideas` tag on this one.

> Thanx for this extension. It is the first open source embroidery program I like :)

Sounds like you understand why we're so interested in working on it ;)

> PS: I do describe some glitches in the page (tested with version 1.7).

Awesome!  I like glitches, especially (but not exclusively) ones that you know how to reproduce.  Well, I don't _like_ them, but I like hearing about them so that we can fix them.

If you'd be willing to document the problems you see as Issues, that would really help us.  I understand that this takes time and/or you may not be able to document all of them, but any little bit helps.

> PES files are sometimes wrong (workaround is to use DST).

There was a bug with PES files a few versions back, but it should have been fixed by 1.7.  Can you share (in a separate issue please) more about what's wrong?

> Sometimes some extra stitch sections appear (not harmful).
I saw that in your screenshots.  I think this may have to do with a lack of understanding on my part of how the DST format works (especially trims).  Can you share (in a separate issue please) a .SVG and the corresponding .DST that show this problem?

> It would be nice to be able to create satin stitches from fat strokes.
Do you mean a simple satin with a wide stroke?  Or do you mean something like a "bean stitch"?



I noticed that in your Rocket example, you mention getting error messages and having to switch back to a previous version of your SVG.  My goal is that error messages should be descriptive (and translated!), explaining what's wrong and how to fix it.  If you got an error message that's not like that, please feel free to file a bug.

Please especially file a bug if you get a Python exception / traceback!  That's always considered a bug no matter what weird thing the user may have done.

**Comment by lexelby** [comment] 2018-05-24 16:31
BTW, I noticed your mention of "point surgery" to get the number of points to match for a satin column.  That's such a pain, isn't it?  I somewhat-recently added an alternate method that allows the number of points in the two subpaths to be unequal.

Instead of using matching points to determine the direction of the satin stitches, you can add short lines that cross both of the main subpaths.  Each line acts as a "checkpoint" telling Ink/Stitch which direction the satin stitches should go at that point.

Check out the examples directory for some sample SVGs that use this technique.  I hope it helps reduce any hairpulling you might have been doing.  We're hoping to document this better soon.

**Comment by lexelby** [comment] 2018-05-24 16:47
Ignore that last -- I hadn'tv read down far enough in your tutorial!

I tend to use rungs in all satin columns now, not just complicated ones.

**Comment by lexelby** [comment] 2018-05-24 16:54
> In order to tell InkStitch how to orient satin stitches you now can add "rungs" (or direction lines) into each stitchable path. I do not really know how to do this efficiently, i.e. add the lines directly into the path. I used the following method:

Here's how I do it:

1. Make sure the existing satin column path (with the two subpaths) is selected with the Node Editor tool.
2. Press P or select the Pencil tool.
3. Hold shift.
4. Click once at the start of the rung.
5. Click a second time at the end of the rung.

Shift adds the pencil stroke as a new subpath in the existing shape.  It doesn't wipe out the embroidery parameters like ctrl-K does.

Clearly we should document this :)

**Comment by danielkschneider** [comment] 2018-05-24 16:57
Hi. good to hear that you like it. When I wrote the message I just felt that I completed a first draft (in the meantime I even fixed some typos and inconsistencies).

Yes, in the future I will open issues here for each problem I encounter and deposit the SVG file. I also installed the new 1.8 version now. But over the next few days I probably will have to work on other stuff :(

Also, I did not understand that using rungs allows to have unequal N points. I will try.

**Comment by lexelby** [comment] 2018-05-24 16:59
I totally understand the lack of time thing.  I go days or weeks in a row with no time to work on Ink/Stitch.  We slowly but surely make progress :)

Welcome to the community!

**Comment by danielkschneider** [comment] 2018-05-24 17:01
Yes slowly and surely :)

Ah and thanx for help with editing path ! My Inkscape skills are low (but already did greatly improve in the last two days because of using InkStitch). See, my argument for doing embroidery is that it can help people how to learn computer drawing. https://twitter.com/hashtag/embroideryforchange?src=hash

**Comment by lexelby** [comment] 2018-05-24 19:21
Thank you!! That's an awesome license :D

If you're interested, I can also add you as a collaborator which would allow you to contribute to our documentation directly.

And yeah, I've learned a ton about inkscape as I've worked on Ink/Stitch.  I added the rungs feature because satins were taking tons of time to design.  Now I can create them quite quickly.

**Comment by danielkschneider** [comment] 2018-05-25 14:03
Yes I can help a bit with documentation and examples. I'd also be interested in contributing something that could help newbies understand basic embroidery concepts. So yes, you can add me and tell me where and how you finally plan to do the documentation. I have seen https://github.com/lexelby/inkstitch/issues/121

I will open feature request issues. 

Over the next weeks I'll be fairly busy with other things, though.

**Comment by lexelby** [comment] 2018-05-25 14:10
Collaborator invitation sent.  At the moment, @kaalleen and @X3msnake are handling the documentation stuff, so I'll leave this to them.  #121 is the place to be. :)

**Comment by kaalleen** [comment] 2018-05-26 06:18
Wow, so much going on here!!!

@danielkschneider Welcome to the project and thank you for your help. Your website is really a great source for our documentation - at this point we are just at the beginning!

If you find time for our documentation project, go to the [gh-pages branch](https://github.com/lexelby/inkstitch/tree/gh-pages). The Ink/Stitch homepage is directly build from these files. Have a look at the README.md file, which hopefully explains everything you need. I'll be happy to help if questions remain. When you find things to improve, don't be shy to change anything to your taste (even structure or style). Nice to have you in!!!

**Comment by wwderw** [comment] 2018-05-26 12:31
Welcome to the group.  It's great to always get help, especially on a growing project.

>Thanx for this extension. It is the first open source embroidery program I like :)

I have to wholeheartedly agree.  

Up until I saw this project, the only open source program that I had liked (and it had it's limitation, some due to the times, some due to self imposed (like the 65k stitch limit)) was Thred.  Unfortunately, it's dated and hasn't seen any updates at all since 2006.

Again, welcome to the project.

**Comment by danielkschneider** [comment] 2018-05-28 08:19
Hi,
I will learn Jekyll and learn how to use Githup again :)
The docs in the README.md look fine for now.
I will probably start doing something in 1 or 2 weeks. I also will explore how to create stitch files from hand drawings (I am not familiar with the Inkcape tracer), and  lettering

**Comment by wwderw** [comment] 2018-05-28 13:38
> I also will explore how to create stitch files from hand drawings

Typically, I'll do a drawing in Krita (I use a Cintiq, so it's really just a digital version of hand drawing on paper, which is what I used to do before I got my first Cintiq) and bring that into Inkscape and just use the pen tool to digitize.

It works really, really well using that combination of programs/tools.

**Comment by X3msnake** [comment] 2018-05-28 13:56
@danielkschneider Very very nice indeed Master :)

I like your organization and method. Congrats and welcome to the team :)

**Comment by danielkschneider** [comment] 2018-06-15 16:52
I found some time to advance a bit in using InkStitch and also stitch for real. You might like this one:
![inkstitch-logo-patch-glued](https://user-images.githubusercontent.com/2872643/41479900-041fd5ac-70cd-11e8-996c-62d4d307b45a.jpg)
![inkstitch-logo-patch-80mm-v1b](https://user-images.githubusercontent.com/2872643/41479970-279eef72-70cd-11e8-86c0-6c39512eb70b.jpg)

[inkstitch-patches.zip](https://github.com/lexelby/inkstitch/files/2106869/inkstitch-patches.zip)

**Comment by danielkschneider** [comment] 2018-06-16 11:33
I used that magic fabric yes. https://www.gunold.de/en/products/effect-fabrics/step-fabrics-in-embroidery/

You can stitch QR code yes. Yours is attached in the zip :)

![inkstitch-qrcode-9cm-simple-5](https://user-images.githubusercontent.com/2872643/41498263-632f1db8-7169-11e8-9594-86b383de19f3.jpg)

[qr-code.zip](https://github.com/lexelby/inkstitch/files/2108067/qr-code.zip)

However, I did not stitch it. My embroidery machine sits in my office. That being said I got students who did stitch QR codes (smaller than the ones attached) and it worked. 
[documentation ](https://edutechwiki.unige.ch/en/InkStitch_-_QR_code_embroidery)

**Comment by lexelby** [comment] 2018-06-16 11:44
Wow!! :D that is so cool!

**Comment by X3msnake** [comment] 2018-06-17 19:58
@danielkschneider Awsome works

@kaalleen put those patches on the website gallery wen you find the time :)

https://inkstitch.org/tutorials/inspiration/lexelby/

**Comment by X3msnake** [comment] 2018-06-17 20:02
@danielkschneider  can you do a QR code with inkstitch.org to have in the example folder?

**Comment by danielkschneider** [comment] 2018-06-17 23:50
@X3msnake yes, in a few days/by the end of next week. Next three days are too busy and then I need some time to learn github again. Do you happen to have a pointer to a short summary on how to commit files, by chance ?

**Comment by X3msnake** [comment] 2018-06-18 00:46
something like this? 
https://github.com/WGBH/pbucore/wiki/Contributing-to-the-project-through-Github-web-interface

**Comment by danielkschneider** [comment] 2018-06-18 13:38
perfect, thanx

**Comment by kaalleen** [comment] 2018-06-18 17:54
@X3msnake I added the logos to the gallery and changed the URL to be https://inkstitch.org/tutorials/inspiration/

I did not mention any creators. If you (@wwderw, @danielkschneider) want to be mentioned, please add it in or ask me to do it!! (https://github.com/lexelby/inkstitch/blob/gh-pages/_tutorials/001-001-galleries.md)

**Comment by kaalleen** [comment] 2018-06-18 18:07
@X3msnake thank you for adding the post about v1.10.0 :) I was just about doing it, when I saw it was already done.

**Comment by danielkschneider** [comment] 2018-06-20 22:29
I took some time tonight to pursue QR code. Good news: it seems to be very robust. The following is a 8cm path / 5cm QR tag. Using an already hooped wobbly tear-off stabilizer (I patched the hole), a standard needle and  thread, at speed 700/min. And it works, you can try scanning the picture just below with your cell phone. I just removed some jump stitches but it even did work before.
![inkstitch-qrcode-8cm-patch](https://user-images.githubusercontent.com/2872643/41687583-95f84fb2-74e8-11e8-9fb8-be85033700a3.jpg)
I forgot the underlay for the text and was too lazy to make it satin.

Now question: what should be included in the tutorials of this site (I promised to do that) to make it a bit more end-user friendly ? I am a total amateur and since this concerns InkStitch itself you may have some advice on style and design.

I'll submit the tutorial later this week or early next week. So do you think that the three examples below are good enough ?

![square-5cm-lettering](https://user-images.githubusercontent.com/2872643/41687653-d0375b8c-74e8-11e8-9c6f-9c4b324fa289.jpg) 

![patch-8cm](https://user-images.githubusercontent.com/2872643/41687655-d05c7430-74e8-11e8-9c65-1f5cb2ee3f30.jpg)

![patch-square-8cm](https://user-images.githubusercontent.com/2872643/41687656-d0818c8e-74e8-11e8-92c5-5a69e6e5f693.jpg)

zip with the svg's:
[qr-code.zip](https://github.com/lexelby/inkstitch/files/2121325/qr-code.zip)

**Comment by X3msnake** [comment] 2018-06-20 23:49
@danielkschneider awsomness :heart: 

These are serious candidates for the example folder that ships with the releases :D 

@wwderw is the most experienced of us and can give you some tips on were to better focus the tutorials

My only remark and request is that when you do the tweaks please keep the text all the same size like the circular patch, it works and looks better and we can commit that as a special cases use of the brand :) :)

Thanks for the coolness

**Comment by lexelby** [comment] 2018-06-21 01:01
Wow, neato!!  I'm totally going to put one of those on my bag.

I wonder, can we add trims for each of the pixels to the design?  @wwderw does the machine have to pause to trim?  Would a design like this take forever to sew out with that many trims? :)

I also wonder if it would look good with the pixels being done as satins instead of fills.  I realize that would take a fair bit of work to do (great use case for auto-satin...).  I might take a crack at it if that's okay, @danielkschneider.

**Comment by wwderw** [comment] 2018-06-21 01:16
There is no pause to trim (at least not on the machines that I have experience with), the biggest thing is that depending on the machine, it could take anywhere from 6 to 15 seconds to get back up to speed.  With small objects and a lot of trims, the machine could take longer as it would more then likely not get back up to speed (700 spm in this case and my typical speed as well) while it stitches out the next one etc.

The best thing to do is to path and tie as many of these as "you" can to lessen the need for trims and to mitigate their impact on time at the machine.

**Comment by danielkschneider** [comment] 2018-06-21 08:33
Choosing a standard font for InkStitch is tricky IMHO. I believe that I had 
- better results digitizing simple true type fonts for small letters (< 8)
- better results for larger letters (> 12) with artistic fonts (i.e. already digitized ones) for bigger ones.
- in the "middle" it does not matter.

Another problem is that true type SVG fonts are not the same on all machines. For the lettering I did in the round patch, I just used a random Ubuntu font BOLD, the default "sans-serif I believe.

Then there is the "message" a font will convey.....

I suggest you should ask an expert for lettering here :)

**Comment by X3msnake** [comment] 2018-06-21 09:02
There is a file in the closed issues with the branding font brand files and branding guidelines that we should try to follow as close asbpossible to keep all inkstitch related image cohesive ;)

I already posted a todo issue to make these guidelines more visible namely in the website

**Comment by X3msnake** [comment] 2018-06-21 09:04
Also there is a predigitized small font @lexelby did

**Comment by wwderw** [comment] 2018-06-21 10:44
>For my multi-needle Brother I would use trimming and it does not stop, just slow down. However too many trims can create nodes underneath I noticed. I will test the QR with trims later this week or early next week. With my commercial software, trims seem to work with DST files but not PES, but I did not test yet your trims :)

@danielkschneider  The extra nodes I believe you are talking about are due to the style of tie on/tie off stitches that are used.  Some commercial software allow you to change which style.  Again, pathing would help mitigate that

I've never known an issue with PES and trims coming for a commercial program (at least coming from Wilcom, Pulse, Wings and home software like Embrilliance and Brother's own PE-Designs) unless you are using an older version of the PES format that doesn't actually support trims, that's the key thing.

I don't know what version of PES that libembroidery uses, but it is one that does support trims for that format.  It's in the right time frame for v. 6, but I don't know if it is that version or not.

Now, stops on the other hand.  My PRs don't like stops from anywhere but PE-Designs (and those are only from the applique module in the PE Designs software, I have to use the Reserve Stop for the color blocks that I want for puff and everything else).  It's been awhile since I tried, so I can't remember which format with stops does what, but one would format would cause the machine to reboot  and the other would just cause it to go back to the last edit screen after "you" tried to finalize the file to start stitching.

**Comment by danielkschneider** [comment] 2018-06-21 11:06
@wwderw sorry today I am in a messy shape. Indeed trims do work with PES files, but stops do not (I am using Stitch Era). 

Also: I noticed that I posted above a wrong version with the logo :( I somehow managed to delete too much. I'll post a new one. That being said: (a) using upper case does reduce squares and (b) one can overlay the InkStitch logo. However, it is difficult to make it look good. One has to be very careful deleting squares and/or changing color. Designing this during meetings doesn't help ;)

**Comment by wwderw** [comment] 2018-06-21 11:08
> sorry today I am in a messy shape. Indeed trims do work with PES files, but stops do not (I am using Stitch Era).

I've known a lot of people happy with that package.  From what I've hear, it's a good one.

**Comment by tatarize** [comment] 2018-06-21 13:14
There's a bug in libembroidery with PES files. They don't actually trim right. I modified the java version to do them like Wilcom does. I think libembroidery did something odd like set the trim and jump bits for the command then did jumps after that. And I think wilcom did only an overt inplace trim then a bunch of jumps. Apparently trim and jump isn't actually a proper command. You flag one or the other but not both. And in PES trim to dx dy is a valid command.

I think there's also something about converting from loaded DSTs into PES where it never bothers to make overt the interpolated trim command from the series of jumps. That can also be at issue.

**Comment by danielkschneider** [comment] 2018-06-21 16:30
This works, but it's ugly ... much easier to separate QR code and other stuff  (at least at my skill level).

The following was stitched with trims (in DST format... I'll try PES sometimes in the future). I did not remove anything, it came out like this.
![inkstitch-patch-qr-code-logo-8cm-trim-2](https://user-images.githubusercontent.com/2872643/41731958-0efede98-7580-11e8-85d6-b054813c907e.jpg)
Also, I tried to remove the squares inside the blue frame, but that breaks it.

Archive with the SVG file, including simpler versions 
[qr-code3.zip](https://github.com/lexelby/inkstitch/files/2124495/qr-code3.zip)

**Comment by danielkschneider** [comment] 2018-06-21 16:42
@tatarize It looks like there is a PES bug, according to the simulation.

Same file as the one stitched (just above)
PES
![square-7cm-embedded-pes](https://user-images.githubusercontent.com/2872643/41732792-57452156-7582-11e8-8546-abe52aadab2b.jpg)


DST : You can see more "stitch packs" and cut symbols
![square-7cm-embedded-dst](https://user-images.githubusercontent.com/2872643/41732906-a0688102-7582-11e8-9229-c341c805c325.jpg)




.... but I did not try the PES for real.

**Comment by danielkschneider** [comment] 2018-06-21 16:54
@wwderw yes Stitch Era is the only  "cheap" professional software I am aware of (they do it Adobe style now, i.e. with rentals: $192 full version/year) and I can get it for *free* for my students. It takes about 4 hours to teach the basics (from raster images or vector drawings to embroidery). On the negative side, it can crash, in particular when manipulating large freaky vectors and/or when the Internet connection is flaky  (frequent saving is recommended).
In general education (I am talking about teaching and using "making"), InkStich will have more mileage because (1) folks also will use InkScape for cutting (e.g. laser or vinyl) and (b) may have to create technical drawings. Finally, they won't go far anyhow. Students who get really hooked on embroidery always can get more expensive software later. Same principle as for many other multimedia and "making" software. This logic does probably not apply to schools of design.

**Comment by wwderw** [comment] 2018-06-21 17:22
> (they do it Adobe style now, i.e. with rentals: $192 full version/year)

That's not a model I've been particular fond of.  Stopped with CS6 due to that very reason.  But I digress on that.

>InkStich will have more mileage because (1) folks also will use InkScape for cutting (e.g. laser or vinyl)

I heard that.  I use a cutter for applique shapes and I've cut directly from Inkscape and I've used the InkCut extension if I need more control over the cutters versus just the raw data being sent to the plotter

>Finally, they won't go far anyhow. Students who get really hooked on embroidery always can get more expensive software later. Same principle as for many other multimedia and "making" software.

As I've gotten more and more of my workflow to open source, they may not actually have to do that and still be able to do all the stuff that the commercial packages do.  Not always the case, but it's far better now in the open source arena then it used to be.

Until I found InkStitch, embroidery was my only hold out in that regard.  There are a lot of things that this extension is doing that for me as more of a semi-manual to manual digitizer anyway, even using Wilcom software is able to handle my workflow.  So I really can't wait to see what else this extension is able to do down the road.

**Comment by lexelby** [comment] 2018-06-30 02:56
Not quite done yet, but here's what I have so far:

![inkstitch_qr_lex](https://user-images.githubusercontent.com/4446653/42120786-46e04a3e-7bef-11e8-9964-86bfe2614b62.png)

For the big squares, I got creative and set the max stitch length to the width of a "pixel" and the number of staggers to 1, giving a pseudo-satin pixellated appearance.  I'll have to see if it sews out how I'm thinking it will.

[inkstitch-qr-code-lex.svg.zip](https://github.com/inkstitch/inkstitch/files/2151363/inkstitch-qr-code-lex.svg.zip)

**Comment by lexelby** [comment] 2018-06-30 16:55
Added trims and converted the brackets to satins:

![inkstitch_qr_lex](https://user-images.githubusercontent.com/4446653/42127349-cee58046-7c64-11e8-96c7-48ff2c2a097d.png)

[inkstitch-qr-code-lex.svg.zip](https://github.com/inkstitch/inkstitch/files/2152023/inkstitch-qr-code-lex.svg.zip)

Gonna test-sew tomorrow :)

**Closed** 2023-07-08 22:07 UTC
Labels: ideas
