### ISSUE TITLE
image not converted to embroidery

### ISSUE THREAD

**Issue by framboise314** [inkstitch/inkstitch#805] opened 2020-08-29 09:04 UTC
the message tells to send it here..
thank tou

====================
path925: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "d:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 225, in to_patches
  File "d:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "d:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "d:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "d:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 149, in build_fill_stitch_graph
  File "d:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

**Comment by kaalleen** [comment] 2020-08-29 09:40
Thank you for reporting your issue. We have seen it a lot lately and will be looking into it.
I will close this issue now, because it is a duplicate of #734, the issue can be discussed there.

**Closed by kaalleen** 2020-08-29 09:40 UTC
