### ISSUE TITLE
ink stitch cannot run on this pc? win 11

### ISSUE THREAD

**Issue by dgriffin51** [inkstitch/inkstitch#2394] opened 2023-06-28 16:27 UTC

**Comment by kaalleen** [comment] 2023-06-29 20:27
There has been an issue for some people with specific processors on windows who couldn't run version v3.0.0.
Today we release v3.0.1 most probably will fix your issue.

**Comment by dgriffin51** [comment] 2023-06-29 20:39
![Screenshot 2023-06-28 115216](https://github.com/inkstitch/inkstitch/assets/103147171/90a28d25-2a7b-4b4a-a9a7-f81dd47ad194)
![Screenshot 2023-06-29 163501](https://github.com/inkstitch/inkstitch/assets/103147171/c179728d-257c-4167-8af9-e55b1c24716d)

**Comment by dgriffin51** [comment] 2023-06-29 20:53
> There has been an issue for some people with specific processors on Windows who couldn't run version v3.0.0. Today we release v3.0.1 most probably will fix your issue.



> There has been an issue for some people with specific processors on windows who couldn't run version v3.0.0. Today we release v3.0.1 most probably will fix your issue.

![Screenshot 2023-06-29 163501](https://github.com/inkstitch/inkstitch/assets/103147171/07f25c01-4017-46e8-80a6-245084003271)


> There has been an issue for some people with specific processors on windows who couldn't run version v3.0.0. Today we release v3.0.1 most probably will fix your issue.

![Screenshot 2023-06-29 163501](https://github.com/inkstitch/inkstitch/assets/103147171/1b7e0687-d1a0-4f27-86b1-0c63455d6086)

**Comment by dgriffin51** [comment] 2023-06-29 20:55
see the error pic

**Comment by kaalleen** [comment] 2023-07-02 06:04
Closing this as a duplicate of #2399
If this doesn't solve your issue you can still continue the discussion over there.

**Closed by kaalleen** 2023-07-02 06:04 UTC
