### ISSUE TITLE
MacOS Big Sur "Error writing to" Issue

### ISSUE THREAD

**Issue by mxwoodson** [inkstitch/inkstitch#955] opened 2020-12-30 21:00 UTC
My operating system is Big Sur. When I try to run Inkstitch I get an error as follows:

"Inkscape has received additional data from the script excuted. The script did not return an error, but this may indicate the results will not be expected.  "Error writing to ./cityjpg.vp3: Read-only  file system."

What do I need to do to fix this? Please help!

**Comment by kaalleen** [comment] 2020-12-31 10:33
Duplicate of #956

**Closed by kaalleen** 2020-12-31 10:33 UTC
