### ISSUE TITLE
stitch_plan: IndexError: list index out of range

### ISSUE THREAD

**Issue by tbbucsfan78** [inkstitch/inkstitch#1244] opened 2021-06-11 10:08 UTC
Unable to save design from a hi-res jpg.  Received the below error.

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\stitch_plan\stitch_plan.py", line 26, in patches_to_stitch_plan
IndexError: list index out of range

**Comment by tyrosinase** [comment] 2021-06-11 11:29
On Fri, Jun 11, 2021, at 6:08 AM, tbbucsfan78 wrote:
> 

> Unable to save design from a hi-res jpg. Received the below error.


> Traceback (most recent call last):
> File "inkstitch.py", line 52, in 
> File "inkex\base.py", line 141, in run
> File "lib\extensions\output.py", line 56, in effect
> File "lib\stitch_plan\stitch_plan.py", line 26, in patches_to_stitch_plan
> IndexError: list index out of range


That's the error that Ink/Stitch gives when there's nothing embroiderable. It's a bug in that it's not giving you the more informative message, but otherwise that's how Ink/Stitch behaves: you have to at minimum trace a bitmap into vectors. If you want more than a basic fill you then tell Ink/Stitch what to do with the resulting shapes: edit narrow shapes into satin, change angles and pull compensation on others, etc.

**Comment by kaalleen** [comment] 2021-07-19 07:01
Duplicate of #1199

**Closed by kaalleen** 2021-07-19 07:01 UTC
