### ISSUE TITLE
Inkscape has received additional data from the script executed

### ISSUE THREAD

**Issue by GrumpyMonkeyy** [inkstitch/inkstitch#2062] opened 2023-02-10 16:25 UTC
Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\extensions\base.py", line 200, in elements_to_stitch_groups
  File "lib\elements\element.py", line 329, in embroider
  File "lib\elements\element.py", line 387, in validate
  File "lib\elements\fill_stitch.py", line 321, in validation_errors
  File "lib\elements\fill_stitch.py", line 274, in shape
AttributeError: 'Point' object has no attribute 'geoms'

**Comment by kaalleen** [comment] 2023-02-12 11:59
Try to remove tiny little objects from your svg. In the next version Ink/Stitch is going to just ignore those, but for now you'll have to track them down. If you have only bigger shapes do embroider, it may be faster to select them and then invert your selection and remove whatever is in that inverted selection.

**Comment by kaalleen** [comment] 2023-02-25 13:06
Duplicate of #1816

**Closed by kaalleen** 2023-02-25 13:06 UTC
