### ISSUE TITLE
Didn't install - seems Macafee thinks its a virus - 

### ISSUE THREAD

**Issue by Hardshell0202** [inkstitch/inkstitch#654] opened 2020-04-08 22:26 UTC
I followed the YouTube tutorial to install the add on (well done by the way) and then started the next video on basics where you install the add on.   That went fine - but when I restarted the program a few min later as I was going through the steps to draw 2 circles and do the simulation - it got a notice from McCaffee that it had removed / blocked / fixed a virus.    I have a photo of my screen - but basically the root directory referenced was the  Instich files.

After that - nothing worked - wont run a simulation and wont' save a file as a .pes (or any other embroidery extension). 

The firs set of text below is the error message I got when I tried to run the simulation.  The second set of text is the error message when I tried to save the file (was trying to just do a file conversion from svg to pes of a simple outline. 

Tried to launch: inkstitch\bin\inkstitch
Arguments: ['inkstitch\\bin\\inkstitch', '--extension=simulate', 'C:\\Users\\tammi\\AppData\\Local\\Temp\\ink_ext_XXXXXX.svgMEWII0']
Debugging information:

Traceback (most recent call last):
  File "inkstitch.py", line 34, in <module>
    extension = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Program Files\Inkscape\lib\python2.7/subprocess.py", line 325, in __init__
    errread, errwrite)
  File "C:\Program Files\Inkscape\lib\python2.7/subprocess.py", line 575, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

Tried to launch: inkstitch\bin\inkstitch
Arguments: ['inkstitch\\bin\\inkstitch', '--extension=output', '--format=pes', 'C:\\Users\\tammi\\AppData\\Local\\Temp\\ink_ext_XXXXXX.svg3BB9H0']
Debugging information:

Traceback (most recent call last):
  File "inkstitch.py", line 34, in <module>
    extension = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Program Files\Inkscape\lib\python2.7/subprocess.py", line 325, in __init__
    errread, errwrite)
  File "C:\Program Files\Inkscape\lib\python2.7/subprocess.py", line 575, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by kaalleen** [comment] 2020-04-10 07:15
Oh, sorry for this one. We have seen it a lot and have no idea how to change the behavior of antivirus software. They really don't seem to like Ink/Stitch a lot. The only thing you could do about it, would be to whitelist (add an exception) for the Ink/Stitch extension folder to your antivirus software.

**Comment by kaalleen** [comment] 2020-04-19 08:29
Closing the issue now. Duplicate of #613 
When you have more questions about this topic, you can discuss it there - or reopen your issue - just as you like.

**Closed by kaalleen** 2020-04-19 08:29 UTC
