### ISSUE TITLE
ValueError: A LinearRing must have at least 3 coordinate tuples

### ISSUE THREAD

**Issue by yeilows** [inkstitch/inkstitch#788] opened 2020-08-17 04:58 UTC
this is the message i got

Traceback (most recent call last):
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/inkstitch.py", line 44, in <module>
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/inkscape/share/extensions/inkex.py", line 283, in affect
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/extensions/embroider.py", line 84, in effect
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/extensions/base.py", line 185, in elements_to_patches
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/elements/element.py", line 307, in embroider
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/elements/element.py", line 364, in validate
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/elements/fill.py", line 147, in validation_errors
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/backports/functools_lru_cache.py", line 124, in wrapper
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/elements/fill.py", line 135, in shape
  File "/Users/runner/runners/2.169.1/work/inkstitch/inkstitch/lib/elements/fill.py", line 135, in <lambda>
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/geometry/polygon.py", line 243, in __init__
  File "/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/shapely/geometry/polygon.py", line 509, in geos_polygon_from_py
  File "shapely/speedups/_speedups.pyx", line 340, in shapely.speedups._speedups.geos_linearring_from_py
ValueError: A LinearRing must have at least 3 coordinate tuples

**Comment by kaalleen** [comment] 2020-08-30 08:33
I am closing this issue now, because it is a duplicate of #786 
We would be still interested, if the new version would work for you.
If not, it'd be nice if you could send us a file which is causing the error.

**Closed by kaalleen** 2020-08-30 08:33 UTC
