### ISSUE TITLE
Ink/Stitch only renders one object

### ISSUE THREAD

**Issue by libbyboss** [inkstitch/inkstitch#2083] opened 2023-02-21 04:47 UTC
Here's the error commentary:

Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\extensions\base.py", line 200, in elements_to_stitch
![Bunny face](https://user-images.githubusercontent.com/125945801/220249964-43e0e7c9-c3b6-4356-9c58-33c859f4e7fc.svg)
_groups
  File "lib\elements\element.py", line 329, in embroider
  File "lib\elements\element.py", line 387, in validate
  File "lib\elements\fill_stitch.py", line 321, in validation_errors
  File "lib\elements\fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'

**Comment by kaalleen** [comment] 2023-02-21 18:58
This is a bit too small for jagged edges, even too small for satin stitch border. Is this the size you want to stitch it in? Then I would recommend to redraw and use a running stitch outline. Here is an example how this could look like.

![2083](https://user-images.githubusercontent.com/36401965/220434646-4171339b-6604-4918-bb67-785861860050.svg)

If you see this error again, then you should go ahead and search your document for very small elements and remove them.

**Comment by libbyboss** [comment] 2023-02-21 20:39
Thank you! I've ended up getting rid of the jagged stitches for a first
prototype, but I think I'll redo it with the running stitch.

Libby Boss
(she, her, hers)

**Comment by kaalleen** [comment] 2023-02-25 12:50
The next Ink/Stitch release will have an interesting feature for satin columns. But the column itself shouldn't be too thin for that.

We have seen this issue a lot before you posted it, so I'll close it now as it is a duplicate of #1742

**Closed by kaalleen** 2023-02-25 12:50 UTC

**Comment by libbyboss** [comment] 2023-02-25 14:01
Thank you!
