### ISSUE TITLE
INKSTITCH won't clean up document nor output dst file

### ISSUE THREAD

**Issue by ketabe** [inkstitch/inkstitch#2071] opened 2023-02-14 15:54 UTC
1/ INKSTITCH won't clean up document

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\cleanup.py", line 41, in effect
  File "lib\elements\fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'

2/ INKSTITCH won't generate/output dst file

path22: error: Error during autofill!  This means that there is a problem with Ink/Stitch.
Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 564, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 632, in do_contour_fill
  File "lib\stitches\contour_fill.py", line 137, in offset_polygon
  File "lib\stitches\contour_fill.py", line 186, in _match_polygons_and_holes
  File "shapely\geometry\base.py", line 685, in difference
  File "shapely\topology.py", line 72, in __call__
  File "shapely\topology.py", line 37, in _check_topology
shapely.errors.TopologicalError: The operation 'GEOSDifference_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.multipolygon.MultiPolygon object at 0x21FBCDA8>

shapely.geos - ERROR - TopologyException: Input geom 1 is invalid: Self-intersection at 243.72028457487218 3301.7989738317929
shapely.geos - INFO - Self-intersection at or near point 243.72028457487218 3301.7989738317929

![AI](https://user-images.githubusercontent.com/65393512/218788561-8ad18c12-d93b-48c0-a95d-4c936d8c6a4b.svg)

**Comment by kaalleen** [comment] 2023-02-20 16:42
This is a very challenging image for embroidery. I suppose you will have to think about how to simplify it and redraw it with the bezier tool. When doing this, try to have the three stitch types in mind: fill stitch, satin stitch and running stitch. This can turn into a nice embroidered picture, but it is a lot of work.

**Comment by kaalleen** [comment] 2023-02-25 12:55
Duplicate of #1742

**Closed by kaalleen** 2023-02-25 12:55 UTC
