### ISSUE TITLE
BUG in Inkstitch

### ISSUE THREAD

**Issue by Richard130948** [inkstitch/inkstitch#825] opened 2020-09-22 23:03 UTC
When I ran Institch, design came out fine.  But when I tried to save it as a Inkstitch.zip file,  apparently Inkstitch ran into a problem and I got the following error:

path1020_Black-1-Top (path1020_9): error: Error during autofill!  **_This means that there is a problem with Ink/Stitch._**

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/auto_fill.py", line 212, in to_patches
  File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 55, in auto_fill
  File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 149, in build_fill_stitch_graph
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

**Comment by kaalleen** [comment] 2020-09-27 09:41
Thanks for reporting this issue. It is bothering a lot of users lately.
Duplicate of #734

**Closed** 2020-10-04 12:30 UTC
