### ISSUE TITLE
auto_fill: ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by MrMonster243** [inkstitch/inkstitch#1087] opened 2021-03-14 01:06 UTC
path819-7-5-6: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "/home/runner/work/inkstitch/inkstitch/lib/elements/auto_fill.py", line 212, in to_patches
  File "/home/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/home/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 55, in auto_fill
  File "/home/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/home/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 149, in build_fill_stitch_graph
  File "/home/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

**Comment by kaalleen** [comment] 2021-03-14 08:50
Sorry for this. It's a well known issue of the latest release. We hope it will be gone in the next release.
Usually it is caused by very small fill objects. I just wonder whhy it has been working in one part of Ink/Stitch and not in the other. Try to remove small fill areas with help of the following tool: Extensions > Ink/Stitch > Troubleshoot > Cleanup document ...

We'd like to hear if this solves your issue.

**Comment by kaalleen** [comment] 2021-03-28 09:03
Duplicate of #734

**Closed by kaalleen** 2021-03-28 09:03 UTC
