### ISSUE TITLE
setlocale (lettering & params)

### ISSUE THREAD

**Issue by VroomVroomOuais** [inkstitch/inkstitch#1242] opened 2021-06-10 15:30 UTC
Hey, sorry I posted it a second time, my other account was marked as spam

So whenever I click on "params", I just have an error

I create a object, convert it to a path, try to click on param and it fails

I'm using Windows 10 and Inkscape 1.1

"Ink/Stitch experienced an unexpected error.

If you'd like to help, please file an issue at https://github.com/inkstitch/inkstitch/issues and include the entire error description below:

Ink/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
File "inkstitch.py", line 52, in
File "inkex\base.py", line 141, in run
File "lib\extensions\params.py", line 626, in effect
File "lib\extensions\params.py", line 340, in init
File "lib\extensions\params.py", line 606, in create_tabs
File "lib\extensions\params.py", line 69, in init
wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(0, 0), "C") == 0" failed at ....\src\common\intl.cpp(1694) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!
"

**Comment by kaalleen** [comment] 2021-06-10 16:26
Hey there, thanks for reporting your issue. This happens, when you have a language/country combination which wxpython thinks is uncommon. But there is a fix. Download and install this development build: https://github.com/inkstitch/inkstitch/releases/tag/dev-build-kaalleen-fix-1186

It only differs from Ink/Stitch 2.0 in that point, that it fixes this issue.

**Comment by kaalleen** [comment] 2021-07-19 07:07
Duplicate of #1232

**Closed by kaalleen** 2021-07-19 07:07 UTC
