### ISSUE TITLE
Inkstitch Extension not working - "Inkscape has received additional data from the script executed..."

### ISSUE THREAD

**Issue by akf123** [inkstitch/inkstitch#1077] opened 2021-03-10 20:05 UTC
I downloaded the inkstitch extension on my Mac (Big Sur) and have not been able to use it because I receive error messages every time.  Could anyone offer me some guidance?  I went through all the MacOS download steps to ensure I was doing it right but I'm still having issues.  My experience is limited so any help would be great.  Pics below of the message I get.

<img width="727" alt="Screen Shot 2021-03-10 at 2 55 40 PM" src="https://user-images.githubusercontent.com/80423954/110689678-f899fa80-81b0-11eb-810e-75cde35ebd81.png">
<img width="467" alt="Screen Shot 2021-03-10 at 2 55 57 PM" src="https://user-images.githubusercontent.com/80423954/110689681-fa63be00-81b0-11eb-9bf8-ccc38ae56284.png">

**Comment by kaalleen** [comment] 2021-03-13 08:29
The latest Ink/Stitch release is missing a library for macOS Big Sur. Here you will find a description how you can fix the issue: https://inkstitch.org/docs/install-macos/#addtitional-steps-for-catalina--big-sur

**Comment by kaalleen** [comment] 2021-03-13 08:32
I will be closing this issue, because it is a duplicate of #1081

This error has been worked on. The next release should not be in need of this extra step.

**Closed by kaalleen** 2021-03-13 08:32 UTC
