### ISSUE TITLE
Won't render my preview.

### ISSUE THREAD

**Issue by legotires** [inkstitch/inkstitch#2163] opened 2023-03-24 05:10 UTC
This is my first real-time trying to digitize a more intricate and colorful design but I'm not entirely sure what all the steps are and got this error message.

Ink/Stitch Version: v2.2.0 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 231, in run
  File "lib/extensions/troubleshoot.py", line 29, in effect
  File "lib/elements/fill_stitch.py", line 321, in validation_errors
  File "lib/elements/fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'

The svg is below.

![antoinette head tilt](https://user-images.githubusercontent.com/128776511/227429767-5d9aba12-0316-4a6b-9beb-663790d044e3.svg)

**Comment by tyrosinase** [comment] 2023-03-24 12:32
You have some too-small-to-stitch sections. The upcoming version won't choke on those, but the current version does.

**Comment by kaalleen** [comment] 2023-05-15 21:28
Duplicate of https://github.com/inkstitch/inkstitch/issues/1742

**Closed by kaalleen** 2023-05-15 21:28 UTC
