### ISSUE TITLE
Issue when trying to save as .pes

### ISSUE THREAD

**Issue by Beep1331** [inkstitch/inkstitch#1910] opened 2022-11-15 17:29 UTC
Hello,

I am getting this error when trying to save as .pes.
Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\extensions\base.py", line 200, in elements_to_stitch_groups
  File "lib\elements\element.py", line 329, in embroider
  File "lib\elements\element.py", line 387, in validate
  File "lib\elements\fill_stitch.py", line 321, in validation_erro
  File "lib\elements\fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'

Attaching the .svg file.

![BroBro-011](https://user-images.githubusercontent.com/118299020/201986648-4a6ca2f9-ca5e-46ff-9b56-38a010743ef8.svg)

**Comment by kaalleen** [comment] 2022-11-16 06:20
Duplicate of #1742

Please read there for more info.

**Closed** 2023-02-25 13:49 UTC
