### ISSUE TITLE
Another Issue... (Sorry!)

### ISSUE THREAD

**Issue by matchamatcha1** [inkstitch/inkstitch#829] opened 2020-09-26 01:06 UTC
Hello! I'm so sorry for posting so much, as I'm new to not only the embroidery machine but also vectors.
I came across this issue when trying to use params/ press embroider:

path213: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 212, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 149, in build_fill_stitch_graph
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

Any help would be appreciated, thank you!

**Comment by matchamatcha1** [comment] 2020-09-26 01:07
I'm willing to send the svg file if need be

**Comment by matchamatcha1** [comment] 2020-09-26 02:04
Never mind! I saw that at one point I got an error for small spaces in my design, so I ended up redrawing my design to rid of those small spaces. That seemed to solve my problem!

**Comment by kaalleen** [comment] 2020-09-27 09:39
So great, you could solve your problem.
Still we would like to have a look at the issue. We would be happy to receive the broken SVG file, so we can investigate it.
This error message appears a lot lately and would be worth to be solved as quickly as possible.

**Comment by kaalleen** [comment] 2020-09-27 09:40
Duplicate of #734

**Closed** 2020-10-04 12:19 UTC
