### ISSUE TITLE
Error during autofill: ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by quinnyeslek** [inkstitch/inkstitch#1063] opened 2021-03-05 03:44 UTC
path9692: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 212, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 149, in build_fill_stitch_graph
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

**Comment by kaalleen** [comment] 2021-03-05 17:57
This error we see a lot these days and will hopefully not to be seen in our next release. Until then you will need to take care for very small fill objects. They are too small to be stitched properly with Ink/Stitch and are causing this error. Since they are too small to be stitched out, it wouldn't do any harm to simply delete them from the document. Run Extensions > Ink/Stitch > Troubleshoot > Cleanup document ...  in order to do this.

**Comment by kaalleen** [comment] 2021-03-06 13:12
This is a duplicate of #734. I will close this issue now. Please reopen if it is still needed.

**Closed** 2021-03-06 13:13 UTC
