### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by krylon80** [inkstitch/inkstitch#2217] opened 2023-04-13 15:22 UTC
if someone could assist with the following error, i would appreciate it! thank you,

path507: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.2.0 (osx)

Traceback (most recent call last):
  File "lib/elements/fill_stitch.py", line 556, in to_stitch_groups
  File "lib/elements/fill_stitch.py", line 590, in do_underlay
  File "lib/debug.py", line 133, in decorated
  File "lib/stitches/auto_fill.py", line 62, in auto_fill
  File "lib/stitches/fill.py", line 163, in intersect_region_with_grating
ZeroDivisionError: float division by zero

**Comment by krylon80** [comment] 2023-04-13 15:58
Hi kaaleen, thanks for your quick response. The image i'm working with is a very clean vector-based graphic that doesn't have any elements that I would consider "small" or "thin". Is there a certain threshold I should be aiming for or is there away to have the image scanned and problem elements highlighted? Thank you,

**Comment by tyrosinase** [comment] 2023-04-13 16:06
Make sure your image is scaled right: awhile back we had a lengthy discussion about why a perfectly normal-looking 4x4 SVG was failing even though all the shapes looked fine, until we realized that the scale was set to 4x4 *millimeters*. :facepalm: 

(and I think the next release will have that error fixed so that Troubleshooting correctly picks it up)

**Comment by krylon80** [comment] 2023-04-13 16:45
i don't think there's an issue with the scale. my image is 3x3" in illustrator and loads as 3x3" in inkscape. however, i just noticed that i'm unable to change the ruler unit display from pixels to inches in inkscape. i've selected inches using both the little down arrow button immediately above the right end of the ruler as well as in app preferences but it's still displaying pixels.

what's the best file format for me to load if my intention is to convert to PES/DST? i have JPG, PDF, AI, and SVG versions all created in illustrator. thanks,

**Comment by tyrosinase** [comment] 2023-04-13 16:50
Go over into the page size and see what it says; I think that's also where you change the ruler.

Also if you're so inclined you can edit your pages.csv to include whatever hoops you have: https://silverseams.com/embroidery-patterns/basting-boxes/index.html

(nb: Ink/Stitch does not care what your page size is, it will export all the stitches you create. But it does help for visualizing during design.)

And you should always use the SVG version of things - Ink/Stitch doesn't do anything with bitmaps.

**Comment by krylon80** [comment] 2023-04-13 16:58
again, is there away to have the image screened and problem elements highlighted so i know what may be triggering the error?

**Comment by kaalleen** [comment] 2023-04-13 19:58
You can go through your elements list and render them separately or in smaller groups  (stitch plan preview) to see on which element the error pops up. This usually shows up in pointy corners when they are in an unlucky position. You can even try to change your start and stop position slightly, this may fix the error too.

**Comment by kaalleen** [comment] 2023-05-15 21:09
Duplicate of https://github.com/inkstitch/inkstitch/issues/1829

**Closed** 2023-05-15 21:23 UTC
