### ISSUE TITLE
Auto_fill: NetworkxNoPath (path6)

### ISSUE THREAD

**Issue by mtozier** [inkstitch/inkstitch#2649] opened 2023-12-17 16:33 UTC
I keep recieving an issue with this specific file. I've been able to resolve this issue with others but am still getting this issue here. I have even tried recreating the file completely and am still receiving this error.

Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 729, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 781, in do_auto_fill
  File "lib\debug.py", line 231, in decorated
  File "lib\stitches\auto_fill.py", line 80, in auto_fill
  File "lib\debug.py", line 231, in decorated
  File "lib\stitches\auto_fill.py", line 671, in path_to_stitches
  File "lib\stitches\auto_fill.py", line 632, in travel
  File "networkx\classes\backends.py", line 148, in wrapper
  File "networkx\algorithms\shortest_paths\generic.py", line 173, in shortest_path
  File "networkx\algorithms\shortest_paths\weighted.py", line 2398, in bidirectional_dijkstra
networkx.exception.NetworkXNoPath: No path bet
![NHS_DesignFile_Mari (2)](https://github.com/inkstitch/inkstitch/assets/154079113/fa79d381-8257-488c-bd7c-f7769fe1ed73)
ween (164.6147139074099, 145.5118110236227) and (164.55117611102085, 145.40626789949565).

**Comment by kaalleen** [comment] 2023-12-17 18:58
Interesting. I cannot reproduce with Ink/Stitch 3.0.1 (linux).
Does it always happen or only happen when you select specific shapes?

**Comment by mtozier** [comment] 2023-12-17 18:59
I continue to get this issue when I go to save the file

**Comment by Marif91** [comment] 2023-12-18 09:48
Je pense qu'il est impossible de broder ce fichier, les éléments sont bien trop petits.
<img width="948" alt="Capture d’écran 2023-12-18 à 10 47 16" src="https://github.com/inkstitch/inkstitch/assets/65076100/07060aec-75b5-4dc2-a01a-a9d5c91e2f26">

**Comment by mtozier** [comment] 2023-12-18 14:14
I have been able to save a similar image as .pes for 60 other similar files. The only thing that changes is the name across the top. All the other elements stay the same. Yet this one file won't save as a .pes.

**Comment by kaalleen** [comment] 2023-12-24 07:22
@Marif91 is right, the design will be hard to stitch out and may not look nice.

For instance, the white circle in the center could be just that, a circle. No need to split the white into various shapes here. The black can go as a bean stitch on top. The letters depending on size would be nice as satin or the smaller ones as a bean stitch (running stitch with repeats). As well as the outline around the logo is small enough to go as a bean stitch. Due to distortion during the stitch out the shape may need adaption when you see gaps.

Experiment a little with satins and bean stitches independently from the logo and see how they stitch out. Use the measuring tool to make out which stitch type to use. A good size for satins is up from 1(.5) mm up to 5 or 7. If you need to go wider with a satin use the maximum stitch length setting in the params dialog. It will bring your embroidery experiences a lot forward if you get familiar with the stitch types available. And don't be afraid to try and error.

That said, your logo should still save without an error. That's a bug in Ink/Stitch that shouldn't be happening.

**Comment by kaalleen** [comment] 2024-02-03 09:21
Runs fine with current main branch. I'll close the issue. If you still have questions about the design post them here.

**Closed by kaalleen** 2024-02-03 09:21 UTC
