### ISSUE TITLE
Troubleshoot layer could not be removed

### ISSUE THREAD

**Issue by snguyen0517** [inkstitch/inkstitch#1568] opened 2022-01-31 01:59 UTC
Traceback (most recent call last):
  File "inkstitch.py", line 67, in <module>
  File "inkex/base.py", line 147, in run
  File "lib/extensions/troubleshoot.py", line 43, in effect
  File "src/lxml/etree.pyx", line 943, in lxml.etree._Element.remove
ValueError: Element is not a child of this node.

**Comment by kaalleen** [comment] 2022-02-01 18:58
Huh, thank you for reporting the error. I wonder how this has happened. In any case, the answer that the troubleshoot function wanted to give to you was, that all your elements are valid.

**Comment by kaalleen** [comment] 2023-07-02 18:02
Cannot reproduce the error. Probably fixed. Closing. Please open a new issue if this is showing up again with a current Ink/Stitch version.

**Closed by kaalleen** 2023-07-02 18:02 UTC
