### ISSUE TITLE
error?

### ISSUE THREAD

**Issue by kedamohno** [inkstitch/inkstitch#2044] opened 2023-01-31 04:24 UTC
path2928: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.2.0 (osx)

Traceback (most recent call last):
  File "lib/elements/fill_stitch.py", line 556, in to_stitch_groups
  File "lib/elements/fill_stitch.py", line 590, in do_underlay
  File "lib/debug.py", line 133, in decorated
  File "lib/stitches/auto_fill.py", line 62, in auto_fill
  File "lib/stitches/fill.py", line 163, in intersect_region_with_grating
ZeroDivisionError: float division by zero

it keeps rejecting what i made, so I hope it can be fixed! so far ink stitch seems awesome!

**Comment by kaalleen** [comment] 2023-01-31 21:59
Try to run `Extensions > Ink/Stitch > Troubleshoot > Clean document`. This will remove tiny shapes from your document. If that doesn't work, go through your layers and obejcts dialog and search for small objects. Or (if they are many) select those shapes which you want to keep and reverse selecting and delete everything else.

**Comment by kaalleen** [comment] 2023-02-25 13:15
Duplicate of #1829

**Closed by kaalleen** 2023-02-25 13:15 UTC
