### ISSUE TITLE
Color: TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by bradg17** [inkstitch/inkstitch#2562] opened 2023-10-18 16:44 UTC
I recently setup Inkscape with Ink stitch. I follows the prompts to install and when attempting to edit the Params, by clicking apply and Quit, this message pops up. (see below)

Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v3.0.1 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 250, in run
  File "lib\extensions\output.py", line 57, in effect
  File "lib\stitch_plan\stitch_plan.py", line 35, in stitch_groups_to_stitch_plan
  File "lib\stitch_plan\stitch_plan.py", line 115, in new_color_block
  File "lib\stitch_plan\color_block.py", line 16, in __init__
  File "lib\stitch_plan\color_block.py", line 51, in color
  File "lib\threads\color.py", line 36, in __init__
TypeError: 'NoneType' object is not iterable

Any help would be appreciated!! I'm new here

**Comment by kaalleen** [comment] 2023-10-26 16:52
Do you still have the svg which was causing the error? We'd love to have a look at it. You could also try to find a single element which is causing the error and remove the rest before sending the file.

**Comment by kaalleen** [comment] 2023-12-15 11:53
See also #2524 (I cannot reproduce the error with the provided file).

**Comment by kaalleen** [comment] 2023-12-16 10:10
Closing. Issue has been fixed in current main.
Please try to apply a color through the color palette shown at the bottom of the inkscape window (right click for fill, left click for stroke)

**Closed by kaalleen** 2023-12-16 10:10 UTC
