### ISSUE TITLE
stitch_plan: IndexError: list index out of range

### ISSUE THREAD

**Issue by Cadel13** [inkstitch/inkstitch#1236] opened 2021-06-07 08:59 UTC
I recently downloaded Incscape and Ink/Stich to allow me to design embroidery and the software is experiencing the following issues when I try to 'save as' a file in an embroidery extemsion:
nk/Stitch Version: v2.0.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex\base.py", line 141, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\stitch_plan\stitch_plan.py", line 26, in patches_to_stitch_plan
IndexError: list index out of range

Are you able to assist?
Many thanks,
Cadel.

**Comment by kaalleen** [comment] 2021-06-07 15:25
Interesting. Did you convert your text into path objects? Or could you describe what you were trying to export?
Alternatively we could have a look at your file if you post it here or send it to send-us-files@inkstitch.org

**Comment by kaalleen** [comment] 2021-07-19 07:00
Duplicate of #1199

**Closed by kaalleen** 2021-07-19 07:00 UTC
