### ISSUE TITLE
Lockups in Linux when closing ghost dialog

### ISSUE THREAD

**Issue by tyrosinase** [inkstitch/inkstitch#3049] opened 2024-07-05 02:03 UTC
Downloaded the tar file, opened Inkscape, opened the About box, and crashed my computer. That seems bad.

(None of the other dev versions did this, though I admit I didn't always About them.)

![2024-07-04_21-55](https://github.com/inkstitch/inkstitch/assets/9473609/4009ebf8-7a59-49f4-8364-42fe133a111f)

I get some kind of dialog, but it doesn't fill in. ~~The first time I did it, it took everything down (oomkiller started killing *other* tasks, which is weird)~~

~~The second time, I did a quick killall inkscape and my session survived. The About box hung around and this time I was able to kill it normally with the window control.~~

~~I can reinstall one or more of the previous dev versions and see if any of them have weird About oom situations, if need be.~~ _Update: nope, it's that little ghost dialog box. Try to close it, and I lose mouse control._

(Debian bookworm and LXDE, FWIW.)

**Comment by kaalleen** [comment] 2024-07-05 05:22
Uh, that shouldn't happen! The About extension had to change from a very simple one to one that uses wxpython because Inkscape 1.4 seems to be filtering out extensions that do nothing from the list ... and that's the case with the about extension.

I'll have a look into it later this day. I can't reproduce the issue now, so I might need to try with debian - or have you as a tester of other dev versions. In the meantime... can you try if other wxpython extension cause issues to you on your system as well (element info, params, lettering, tartan, multicolor satin, simulator)? Try closing them through the X on the window frame, especially element info I'd be interested about.

**Comment by tyrosinase** [comment] 2024-07-05 16:04
I'll look into it (by which I mean: my Debian-sysadmin spouse is poking at the syslog - I am a developer not a Linux admin, Jim!) But I'm pretty sure I've been using wxpython stuff for some time - before I loaded the beta I've run:

```
inkstitch-0.0.1-kaalleen-simulator-line-width-option-linux
inkstitch-0.0.1-kaalleen-satin-second-trial-linux
inkstitch-0.0.1-kaalleen-tartan-linux
inkstitch-0.0.1-kaalleen-remove-empty-groups-linux
```

and some older ones. I've had just a couple of what-appears-to-be the same situation on param rendering before, but only occasionally, and never that I could specifically blame Ink/Stitch for - I had always gone to check Firefox or something while the render happened.

**Comment by kaalleen** [comment] 2024-07-05 16:41
I ttried the about extension now on various systems... I can see the inkscape loading dialog in some of them the same way as you do. But I never would have to kill inkscape for exiting out of the about extension. It is now blocking inkscape though as long as it is open because it is a custom gui extension. But I understood that clicking on the x on the about extension window frame didn't close the extension for you and release inkscape?

**Comment by kaalleen** [comment] 2024-07-05 18:10
Ok, finally tested with debian 12.6 (bookworm) with LXDE. Uuuh, ok... all wxpython apps have issues when you move them (leaving a track). Not nice. Closing works well nevertheless. Not sure what to do about the whole experience to be honest.

**Comment by tyrosinase** [comment] 2024-07-06 15:25
I think the problem is a memory leak: it does seem like if I try to close About right away, it is successful, but if I let it sit more than a few seconds my machine does the "mouse clicks no longer work" thing (so presumably About is still closeable with a click *if* I could click). Pretty sure killing Inkscape just stopped the bleeding so that the mouse could still click when I came back to close About, rather than making it newly possible to click.

I'm not sure if the problem is Inkscape/wxpython/something else, yeah. It's not a brand-new issue with this release - just a very predictable one for a change. I've never been sure before if it's Inkscape or not (it only happens when Inkscape is open but that may be because Inkscape is almost always open).

Hmm, I'm going to try the release on the baby laptop, which is also on bookworm/LXDE. It's got much less memory, but I don't think has the same leakage issue.

**Comment by tyrosinase** [comment] 2024-07-07 15:17
More data!

The problem is (probably?) not time-based after all, but rather if I try to dismiss (via the corner X) the little ghost dialog that appears in the middle right. If I do that, I've obviously killed something Very Very Important because I lose all mouse-click ability and (I think) some keyboard control (I can still ctrl-alt-f1, but I can't alt-tab to other windows).

That dialog never fills in, title or otherwise, and comes up behind the Params/Preview etc. which explains why it's rarely been an issue for me previously - About was just small enough it didn't obscure it. And clearly I have an ADHD habit of mindlessly closing that dialog, so it didn't even register to me that that is what is causing the lockup. But I bet I've been seeing it now and then when I come back from Firefox or whatever to check on the preview progress, and accidentally brought it to the front first.

**Comment by lexelby** [comment] 2024-07-08 20:41
> oomkiller started killing other tasks, which is weird

It's surprisingly difficult for the poor kennel to figure out who the jerk is when it's out of RAM.  It just pulls out its gun and hopes for the best!

**Comment by tyrosinase** [comment] 2024-07-09 02:35
Okay, I've rolled back to pre-beta dev release on the main machine (until I figure out the command-line stuff), so I have installed the beta on the little laptop. I have confirmed that yep, I get The Ghost Dialog That Kills The Machine If You Close It on that one too (no surprise, it's also ~~bookworm,~~ Debian, also lxde).

I launched Inkscape from the command line (which reminded me, I seem to be running it as AppImage, if that matters), clicked to close the Ghost Dialog, and nothing happened so I closed the About, and got a crash.

```
<pre>
 0# Inkscape::Application::crash_handler(int) in /tmp/.mount_inksca9lFLSg/usr/bin/../lib/x86_64-linux-gnu/inkscape/libinkscape_base.so.1.3.2.0
 1# 0x00007FC470C74090 in /tmp/.mount_inksca9lFLSg/lib/x86_64-linux-gnu/libc.so.6
 2# Inkscape::DocumentUndo::cancel(SPDocument*) in /tmp/.mount_inksca9lFLSg/usr/bin/../lib/x86_64-linux-gnu/inkscape/libinkscape_base.so.1.3.2.0
 3# 0x00007FC46F6F2EEB in /tmp/.mount_inksca9lFLSg/usr/lib/libgtkmm-3.0.so.1
 4# g_closure_invoke in /tmp/.mount_inksca9lFLSg/usr/lib/libgobject-2.0.so.0
 5# 0x00007FC470180243 in /tmp/.mount_inksca9lFLSg/usr/lib/libgobject-2.0.so.0
 6# g_signal_emit_valist in /tmp/.mount_inksca9lFLSg/usr/lib/libgobject-2.0.so.0
 7# g_signal_emit in /tmp/.mount_inksca9lFLSg/usr/lib/libgobject-2.0.so.0
 8# 0x00007FC46EC39192 in /tmp/.mount_inksca9lFLSg/usr/lib/libgtk-3.so.0
 9# 0x00007FC46EE6D27B in /tmp/.mount_inksca9lFLSg/usr/lib/libgtk-3.so.0
10# g_closure_invoke in /tmp/.mount_inksca9lFLSg/usr/lib/libgobject-2.0.so.0
11# 0x00007FC470180814 in /tmp/.mount_inksca9lFLSg/usr/lib/libgobject-2.0.so.0
12# g_signal_emit_valist in /tmp/.mount_inksca9lFLSg/usr/lib/libgobject-2.0.so.0
13# g_signal_emit in /tmp/.mount_inksca9lFLSg/usr/lib/libgobject-2.0.so.0
14# 0x00007FC46EE179B3 in /tmp/.mount_inksca9lFLSg/usr/lib/libgtk-3.so.0
15# gtk_main_do_event in /tmp/.mount_inksca9lFLSg/usr/lib/libgtk-3.so.0
16# 0x00007FC46E9B3F69 in /tmp/.mount_inksca9lFLSg/usr/lib/libgdk-3.so.0
17# 0x00007FC46E9E70F6 in /tmp/.mount_inksca9lFLSg/usr/lib/libgdk-3.so.0
18# g_main_context_dispatch in /tmp/.mount_inksca9lFLSg/usr/lib/libglib-2.0.so.0
19# 0x00007FC471391400 in /tmp/.mount_inksca9lFLSg/usr/lib/libglib-2.0.so.0
20# g_main_context_iteration in /tmp/.mount_inksca9lFLSg/usr/lib/libglib-2.0.so.0
21# gtk_main_iteration_do in /tmp/.mount_inksca9lFLSg/usr/lib/libgtk-3.so.0
22# Gtk::Main::iteration(bool) in /tmp/.mount_inksca9lFLSg/usr/lib/libgtkmm-3.0.so.1
23# Inkscape::Extension::Implementation::Script::pump_events() in /tmp/.mount_inksca9lFLSg/usr/bin/../lib/x86_64-linux-gnu/inkscape/libinkscape_base.so.1.3.2.0
24# Inkscape::Extension::Implementation::Script::_change_extension(Inkscape::Extension::Extension*, SPDocument*, std::__cxx11::list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, bool) in /tmp/.mount_inksca9lFLSg/usr/bin/../lib/x86_64-linux-gnu/inkscape/libinkscape_base.so.1.3.2.0
25# Inkscape::Extension::Implementation::Script::effect(Inkscape::Extension::Effect*, Inkscape::UI::View::View*, Inkscape::Extension::Implementation::ImplementationDocumentCache*) in /tmp/.mount_inksca9lFLSg/usr/bin/../lib/x86_64-linux-gnu/inkscape/libinkscape_base.so.1.3.2.0
26# Inkscape::Extension::ExecutionEnv::run() in /tmp/.mount_inksca9lFLSg/usr/bin/../lib/x86_64-linux-gnu/inkscape/libinkscape_base.so.1.3.2.0
27# Inkscape::Extension::Effect::effect(Inkscape::UI::View::View*) in /tmp/.mount_inksca9lFLSg/usr/bin/../lib/x86_64-linux-gnu/inkscape/libinkscape_base.so.1.3.2.0
28# Inkscape::Extension::Effect::prefs(Inkscape::UI::View::View*) in /tmp/.mount_inksca9lFLSg/usr/bin/../lib/x86_64-linux-gnu/inkscape/libinkscape_base.so.1.3.2.0
29# 0x00007FC471242D64 in /tmp/.mount_inksca9lFLSg/usr/lib/libgiomm-2.4.so.1
30# g_closure_invoke in /tmp/.mount_inksca9lFLSg/usr/lib/libgobject-2.0.so.0
31# 0x00007FC470180243 in /tmp/.mount_inksca9lFLSg/usr/lib/libgobject-2.0.so.0
32# g_signal_emit_valist in /tmp/.mount_inksca9lFLSg/usr/lib/libgobject-2.0.so.0
33# g_signal_emit in /tmp/.mount_inksca9lFLSg/usr/lib/libgobject-2.0.so.0
34# 0x00007FC4702A7F05 in /tmp/.mount_inksca9lFLSg/usr/lib/libgio-2.0.so.0
35# Gio::Action_Class::activate_vfunc_callback(_GAction*, _GVariant*) in /tmp/.mount_inksca9lFLSg/usr/lib/libgiomm-2.4.so.1
36# 0x00007FC46EB8D812 in /tmp/.mount_inksca9lFLSg/usr/lib/libgtk-3.so.0
37# 0x00007FC46EB8D844 in /tmp/.mount_inksca9lFLSg/usr/lib/libgtk-3.so.0
38# 0x00007FC46EB8D844 in /tmp/.mount_inksca9lFLSg/usr/lib/libgtk-3.so.0
39# 0x00007FC46ECEBEE6 in /tmp/.mount_inksca9lFLSg/usr/lib/libgtk-3.so.0
40# g_closure_invoke in /tmp/.mount_inksca9lFLSg/usr/lib/libgobject-2.0.so.0
41# 0x00007FC470180814 in /tmp/.mount_inksca9lFLSg/usr/lib/libgobject-2.0.so.0
42# g_signal_emit_valist in /tmp/.mount_inksca9lFLSg/usr/lib/libgobject-2.0.so.0
43# g_signal_emit in /tmp/.mount_inksca9lFLSg/usr/lib/libgobject-2.0.so.0
44# gtk_widget_activate in /tmp/.mount_inksca9lFLSg/usr/lib/libgtk-3.so.0
45# gtk_menu_shell_activate_item in /tmp/.mount_inksca9lFLSg/usr/lib/libgtk-3.so.0
46# 0x00007FC46ECE8A63 in /tmp/.mount_inksca9lFLSg/usr/lib/libgtk-3.so.0
47# 0x00007FC46EE6D36F in /tmp/.mount_inksca9lFLSg/usr/lib/libgtk-3.so.0
48# 0x00007FC47016CA56 in /tmp/.mount_inksca9lFLSg/usr/lib/libgobject-2.0.so.0
49# g_signal_emit_valist in /tmp/.mount_inksca9lFLSg/usr/lib/libgobject-2.0.so.0
50# g_signal_emit in /tmp/.mount_inksca9lFLSg/usr/lib/libgobject-2.0.so.0
51# 0x00007FC46EE179B3 in /tmp/.mount_inksca9lFLSg/usr/lib/libgtk-3.so.0
52# 0x00007FC46ECD2ED8 in /tmp/.mount_inksca9lFLSg/usr/lib/libgtk-3.so.0
53# gtk_main_do_event in /tmp/.mount_inksca9lFLSg/usr/lib/libgtk-3.so.0
54# 0x00007FC46E9B3F69 in /tmp/.mount_inksca9lFLSg/usr/lib/libgdk-3.so.0
55# 0x00007FC46E9E70F6 in /tmp/.mount_inksca9lFLSg/usr/lib/libgdk-3.so.0
56# g_main_context_dispatch in /tmp/.mount_inksca9lFLSg/usr/lib/libglib-2.0.so.0
57# 0x00007FC471391400 in /tmp/.mount_inksca9lFLSg/usr/lib/libglib-2.0.so.0
58# g_main_context_iteration in /tmp/.mount_inksca9lFLSg/usr/lib/libglib-2.0.so.0
59# g_application_run in /tmp/.mount_inksca9lFLSg/usr/lib/libgio-2.0.so.0
60# 0x00007FC4734CB420 in /tmp/.mount_inksca9lFLSg/usr/bin/inkscape
61# __libc_start_main in /tmp/.mount_inksca9lFLSg/lib/x86_64-linux-gnu/libc.so.6
62# 0x00007FC4734CBA4E in /tmp/.mount_inksca9lFLSg/usr/bin/inkscape
</pre>
<details><summary>System info</summary>
Inkscape 1.3.2 (091e20e, 2023-11-25)

    GLib version:     2.64.6
    GTK version:      3.24.20
    glibmm version:   2.64.2
    gtkmm version:    3.24.2
    libxml2 version:  2.9.10
    libxslt version:  1.1.34
    Cairo version:    1.18.0
    Pango version:    1.44.7
    HarfBuzz version: 2.6.4

    OS version:       Debian GNU/Linux 11 (bullseye)
</details>
```

... oh hey, I guess the laptop is still on bullseye. At any rate, maybe that helps?

**Comment by kaalleen** [comment] 2024-07-21 10:48
I removed the ghost dialog for the about extension. But it will show up for other Ink/Stitch extensions. I didn't add implements-custom-gui for all of them (which removes the "ghost dialog"), because for inkscape versions < 1.4 the show-stderr method doesn't fully work and we do not want to suppress all messages from stderr or we'd need to add them to wxpython too. Not something I want to do at this stage of development. This goes for messages like please select something otherwise this won't work.

**Comment by tyrosinase** [comment] 2024-07-21 14:49
I'm a little concerned about the alternative being "create a ghost dialog that will crash your computer if you touch it" though. I mean, mayyyyybe if I'm the only one out here running the combo of stuff that triggers it. But it really feels like something that could be damaging to Ink/Stitch's reputation ("oh, I heard that software can kill your computer" is not a great thing to have going around).

**Comment by kaalleen** [comment] 2024-07-21 15:35
I know it's not nice and I truly understand your concerns. But I think more people would be confused not to be told that they actually need to select the right thing (and what that would be). For example they forgot to turn their satin setup actually into a satin and wonder why the gui isn't showing up. 

All custom guis have been acting like that for years now and I'm not going to write wxpython frames for those messages shortly before the next release because they could contain new problems. The next Inkscape version makes the show-stderr method available, although it might be still better to have a wxpython window with the message.

When I try to reproduce the crash on debian with lxde I can't. I am always able to bring back the Ink/Stitch dialog on close it from there. Does that work for you?

**Comment by tyrosinase** [comment] 2024-07-22 14:50
Yeah, losing the gui is even worse.

If I *can* get focus on the Ink/Stitch dialog, I can close it and all is well. But if I wait too long (apparently?), I lose mouse-click ability and some keyboard ability (or maybe LXDE just isn't recognizing particular clicks - I can probably run a diagnostic to see which it is) and then the only way to recover is a reboot. (I thiiiiiink just restarting X has worked, but at that point I'm poking at a tiny SSH window on a phone, so trying to remember how to correctly do that is usually beyond me.)

It's genuinely weird behavior - I thought it was some kind of memory leak and oomkiller running amok (and killing a critical bit of a keyboard driver or something) but I've never been able to catch anything doing that, and oomkiller is only occasionally showing up in the logs so that might be coincidental. (Might be time to upgrade my 8MB machine, for separate reasons.)

I keep being suspicious of my keyboard driver - it's a VARMILO tenkeyless that I love hardware-wise (and moving the mouse closer in has really helped my RSI) but that has some oddball firmware. Linux is definitely an afterthought for it, and it's had some similar lockups in the past. A firmware update fixed it, but I wonder if there's still a residual problem there.

**Closed** 2024-08-17 15:29 UTC
