### ISSUE TITLE
issue when coping and cutting the same object

### ISSUE THREAD

**Issue by 2102nic** [inkstitch/inkstitch#1986] opened 2022-12-29 12:40 UTC
if i make a stitch plan preview of an object it does it without any problems, however if i delete the preview of that object, copy the object, paste the object and try and create a preview of the copied object it gives me this error message:

path28-9: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Ink/Stitch Version: v2.2.0 (osx)

Traceback (most recent call last):
  File "lib/elements/fill_stitch.py", line 556, in to_stitch_groups
  File "lib/elements/fill_stitch.py", line 590, in do_underlay
  File "lib/debug.py", line 133, in decorated
  File "lib/stitches/auto_fill.py", line 62, in auto_fill
  File "lib/stitches/fill.py", line 163, in intersect_region_with_grating
ZeroDivisionError: float division by zero

(the video is showing the issue)
https://user-images.githubusercontent.com/121610658/209952110-d7a7313f-8d51-4950-a00f-c23a28e7d27e.mp4

**Comment by tyrosinase** [comment] 2022-12-29 13:29
When you transform an object (even by moving it), the math in fills can change enough that the stitches will be just slightly different - and this can trigger the problem it has with too-small objects. The next Ink/Stitch release should handle these scraps more gracefully, but you should always clean up the leftover bits regardless - in cases where they *are* large enough to fit stitches into, Ink/Stitch will assume that's what you actually wanted, and go ahead and do so.

**Comment by kaalleen** [comment] 2023-02-25 13:39
Duplicate of #1829

**Closed by kaalleen** 2023-02-25 13:39 UTC
