### ISSUE TITLE
ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by sthwrd** [inkstitch/inkstitch#1009] opened 2021-01-31 00:36 UTC
I'm unsure if this is a me error or an inkstitch error. I can't seem to export this design. I'm on a mid 2014 15' macbook pro High Sierra 10.13.6 (17G14042)

path1478: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

Traceback (most recent call last):
  File "/Users/runner/work/inkstitch/inkstitch/lib/elements/auto_fill.py", line 212, in to_patches
  File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 55, in auto_fill
  File "/Users/runner/work/inkstitch/inkstitch/lib/debug.py", line 125, in decorated
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 149, in build_fill_stitch_graph
  File "/Users/runner/work/inkstitch/inkstitch/lib/stitches/auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

**Comment by kaalleen** [comment] 2021-01-31 08:38
This is an error we are seeing almost every day by now. It is caused by very small fill shapes which can be removed through Extensions > Ink/Stitch > Troubleshoot > Cleanup document...

What is very interesting in your case is your operating system. At the moment we are not releasing any builds for it and the latest release for high sierra should not have this issue. Which Ink/Stitch version are you using?

If you don't mind it would be very interesting for us if you could test a developement branch I am currently testing for high sierra. It can be downloaded here: https://github.com/inkstitch/inkstitch/releases/download/dev-build-kaalleen-inkscape1.0/inkstitch-kaalleen-inkscape1.0-high_sierra-mojave-en_US.zip

**Comment by kaalleen** [comment] 2021-02-06 17:08
Duplicate of #734

**Closed by kaalleen** 2021-02-06 17:08 UTC
