### ISSUE TITLE
autofill error

### ISSUE THREAD

**Issue by MeadowridgeBeeFarm** [inkstitch/inkstitch#1117] opened 2021-04-03 02:26 UTC
path1954: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

**Comment by kaalleen** [comment] 2021-04-03 09:24
Thanks for reporting your error.
I cannot see the whole error message in your post, but I suppose it is a well known error to us (which will be fixed in the next release). It is caused by very small fill objects. You can savely remove them (since they are too small to be embroidered).
Ink/Stitch comes with a tool which will help you with that: Extensions > Ink/Stitch > Troubleshoot > Cleanup document ...

**Comment by kaalleen** [comment] 2021-04-08 15:37
This will be fixed in the next release. Therefore I'll close this issue now. Please reopen if this error still appears in the next Ink/Stitch version.

**Closed by kaalleen** 2021-04-08 15:38 UTC
