### ISSUE TITLE
auto_fill: ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by HowardShank** [inkstitch/inkstitch#924] opened 2020-12-16 23:41 UTC
path107: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 212, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 149, in build_fill_stitch_graph
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

**Comment by HowardShank** [comment] 2020-12-17 00:12
I checked the paths. I've made sure all are closed.

**Comment by kaalleen** [comment] 2020-12-19 11:47
This is mostly caused by leftover fill shapes, very small ones. You could run the function cleanup document which is supposed to remove small elements. As an alternative you could try to solve the issue with the break apart fill objects function. Sometimes you can also find these objects through selecting everything (Ctrl + A) and observing the border boxes of the elements and delete them manually.

**Comment by kaalleen** [comment] 2020-12-19 11:48
We hope to remove this issue soon. It actually shouldn't be too difficult. But we didn't have a lot of time lately.

**Comment by kaalleen** [comment] 2021-01-17 11:50
Duplicate of #734

**Closed by kaalleen** 2021-01-17 11:50 UTC
