### ISSUE TITLE
can not install inkstitch add ons

### ISSUE THREAD

**Issue by Ottobeer** [inkstitch/inkstitch#507] opened 2019-08-03 15:45 UTC
I get this message when I try to install the inkstitch add ons's:

Unexpected error launching Ink/Stitch.
If you're having trouble, please file an issue here, including the text below:
  https://github.com/inkstitch/inkstitch/issues

Tried to launch: inkstitch\bin\inkstitch
Arguments: ['inkstitch\\bin\\inkstitch', '--extension=install', 'C:\\Users\\otto\\AppData\\Local\\Temp\\ink_ext_XXXXXX.svg5AJA6Z']
Debugging information:

Traceback (most recent call last):
  File "inkstitch.py", line 35, in <module>
    extension = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Program Files\Inkscape\lib\python2.7/subprocess.py", line 325, in __init__
    errread, errwrite)
  File "C:\Program Files\Inkscape\lib\python2.7/subprocess.py", line 575, in _execute_child
    startupinfo)
WindowsError: [Error 2] Das System kann die angegebene Datei nicht finden

[ink_ext_XXXXXX.zip](https://github.com/inkstitch/inkstitch/files/3464002/ink_ext_XXXXXX.zip)

**Comment by kaalleen** [comment] 2019-09-03 14:03
Looks like something went wrong with your installation.
Could you confirm your installation path?
It should look similar to the one displayed on this page: https://inkstitch.org/docs/install/

You could also follow the install instructions for windows in this YouTube tutorial:
https://www.youtube.com/watch?v=U5htzWZSjA8&list=PLvlbfDmZyXG1ORmeqHdp4aP7J71e7icJP&index=4

Get back to us, if the problem is still present.

**Comment by kaalleen** [comment] 2020-04-10 07:32
This is most probably an antivirus problem. Due to the age of this issue, I am closing it now.
Please reopen, if adding an exception to the antivirus program doesn't solve the problem.

**Closed by kaalleen** 2020-04-10 07:32 UTC
