### ISSUE TITLE
auto_fill: ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by holly1906** [inkstitch/inkstitch#998] opened 2021-01-27 13:18 UTC
path210: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 212, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 149, in build_fill_stitch_graph
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

**Comment by MK-12-20MM** [comment] 2021-01-27 17:40
Try running the  Extensions > Ink/Stitch > Troubleshoot  to point out any issues with your design.

**Comment by kaalleen** [comment] 2021-01-29 17:25
Hey there. Thank you for reporting your issue. It seems like this error is caused by very small fill shapes in your document. You can easily remove them by running the extension cleanup document (Extensions > Ink/Stitch > Troubleshoot > Cleanup document...). Sorry for your trouble. We hope this error will not show up anymore in the next release.

**Comment by kaalleen** [comment] 2021-02-06 17:04
Duplicate of #734

**Closed by kaalleen** 2021-02-06 17:04 UTC
