### ISSUE TITLE
auto_fill: ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by murmeli07** [inkstitch/inkstitch#1103] opened 2021-03-24 18:07 UTC
Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 225, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 149, in build_fill_stitch_graph
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

[fehlerhafte Datei.zip](https://github.com/inkstitch/inkstitch/files/6199539/fehlerhafte.Datei.zip)

**Comment by kaalleen** [comment] 2021-03-27 08:28
In the current release we have an Ink/Stitch issue which is causing the error. It will be fixed in the next release. It is caused by very small fill shapes, which are too small to stitch. Ink/Stitch comes with a tool that allows you to easily remove small elements from your document. You can find it here: Extensions > Ink/Stitch > Troubleshoot > Cleanup document ...

In your document there is also text which needs to be converted into a stitchable format. Ink/Stitch is not capable to render text as such. Also, if you are willing to put some more time into your design, it would look much nicer, if you used satin columns extensively.

**Comment by kaalleen** [comment] 2021-04-04 09:27
Becase this error has been fixed for the next release, I am going to close this issue now.

**Closed by kaalleen** 2021-04-04 09:27 UTC
