### ISSUE TITLE
gray (path732): error: Error during autofill! 

### ISSUE THREAD

**Issue by Born2live** [inkstitch/inkstitch#2288] opened 2023-05-11 21:23 UTC
Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "lib\elements\fill_stitch.py", line 556, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 590, in do_underlay
  File "lib\debug.py", line 133, in decorated
  File "lib\stitches\auto_fill.py", line 62, in auto_fill
  File "lib\stitches\fill.py", line 163, in intersect_region_with_grating
ZeroDivisionError: float division by zero

**Comment by kaalleen** [comment] 2023-05-13 20:51
Try to remove small elements from your document and also watch out for thin areas in fills. If you enlarge them a little it might help. Or consider to use an other stitch type. For borders satins will look well - or if they are thin a running stitch would do.

**Comment by kaalleen** [comment] 2023-05-15 21:03
Duplicate of #1829

**Closed** 2023-05-15 21:20 UTC
