### ISSUE TITLE
color: TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Guitargal** [inkstitch/inkstitch#1334] opened 2021-08-28 13:44 UTC
Hi, I just installed onto my M1 Mac.
I followed the install instructions using the code in terminal.
I made an embroidery design.
it will not save. I tried as zip as well.
I will try to just do simple lettering and see.

This is the warning from trying to save a simple text. it stitched great on the lettering extension preview.
lib/extensions/base.py:58: DeprecationWarning: inkex.etree was removed, use "from lxml import etree"

I was able to make and save on my 4 year old HP Win 10. but only made about 8 simple things. they cane out great using the auto stitch

it could be rosetta and the M1?
thanks
guitargal

Ink/Stitch Version: v2.0.0 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 52, in <module>
  File "inkex/base.py", line 141, in run
  File "lib/extensions/output.py", line 56, in effect
  File "lib/stitch_plan/stitch_plan.py", line 26, in patches_to_stitch_plan
  File "lib/stitch_plan/stitch_plan.py", line 78, in new_color_block
  File "lib/stitch_plan/stitch_plan.py", line 177, in __init__
  File "lib/stitch_plan/stitch_plan.py", line 212, in color
  File "lib/threads/color.py", line 29, in __init__
TypeError: 'NoneType' object is not iterable

**Comment by kaalleen** [comment] 2021-08-28 16:48
This error looks as if Ink/Stitch hasn't been able to detect the colors of your objects.
I would suggest, you select them one by one and check the colors in the fill and stroke panel. Try also to turn them off and on to reapply them to your objects. Hope it helps.

We have seen this issue being posted by macOS users several times. I believe it could be fixed in the next release, but I am not sure. Would it be possible for you to send us your file, so we can verify?

**Comment by Guitargal** [comment] 2021-08-29 01:26
thanks so much!
here is the thing i am working on


________________________________

**Comment by Guitargal** [comment] 2021-08-29 07:58
I am following a tutorial and started from scratch. I opened it on my HP win 10 and it would not save either.
It was the way i made it I guess.
I started from scratch,
Thanks, sorry to bother you.
Diane
________________________________

**Comment by kaalleen** [comment] 2021-08-29 09:27
Don't be sorry. It is very important for us, that we get information about error messages like this. Only this way we can improve Ink/Stitch. It just seems that we haven't fully understood why files created on macOS systems often show that color issue.

Your file hasn't been attached to your last post. I guess I just forgot to mention, that svg files have to be zipped when you upload them to here, because GitHub will not accept them directly. Alternatively we have created a mail adress for this purpose: send-us-files@inkstitch.org

Thanks for your error report and support. It is much appreciated.

**Comment by billatq** [comment] 2023-11-05 03:30
I ran into the same problem that went away after I changed the fill manually. File to reproduce attached.
[nonetype-repo.zip](https://github.com/inkstitch/inkstitch/files/13258573/nonetype-repo.zip)

**Comment by kaalleen** [comment] 2023-12-16 10:13
Thanks @billatq that is the exact problem. Should be working in main therefore I'll close the issue.

For everyone else who is experiencing the issue, please try to apply a color through the color palette shown at the bottom of the inkscape window (right click for fill, left click for stroke)

**Closed by kaalleen** 2023-12-16 10:13 UTC
Labels: needs steps to reproduce
