### ISSUE TITLE
fill: ValueError: need more than 0 values to unpack (intersect_region_with_grating)

### ISSUE THREAD

**Issue by inakru** [inkstitch/inkstitch#1110] opened 2021-03-30 19:58 UTC
path2299_14_5_1_2_1: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 212, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 133, in build_fill_stitch_graph
  File "D:\a\inkstitch\inkstitch\lib\stitches\fill.py", line 91, in intersect_region_with_grating
ValueError: need more than 0 values to unpack

path2299_14_5_1_2_1: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 212, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 133, in build_fill_stitch_graph
  File "D:\a\inkstitch\inkstitch\lib\stitches\fill.py", line 91, in intersect_region_with_grating
ValueError: need more than 0 values to unpack

path2299_14_5_1_2_1: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 212, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 133, in build_fill_stitch_graph
  File "D:\a\inkstitch\inkstitch\lib\stitches\fill.py", line 91, in intersect_region_with_grating
ValueError: need more than 0 values to unpack

**Comment by kaalleen** [comment] 2021-04-01 18:43
Thanks for reporting your issue. Do you think you could upload a zipped svg file for this issue. It would be interesting to inspect the error further.

**Comment by inakru** [comment] 2021-04-02 14:22
Hi Killen
I am so sorry I am not sure which file it was as I had multiple files open
at the time. I will send the file with pleasure if I know which one it was.
Kind regards
Ina

**Comment by kaalleen** [comment] 2021-04-04 08:27
Ok, thank you!

**Comment by kaalleen** [comment] 2021-04-04 08:38
We once received a file with this error. It turned out, that it was caused by an expand value which made the shape invalid.
Is there a chance, that this was caused by that as well?

**Comment by kaalleen** [comment] 2021-05-04 15:59
I'll close this issue. The new release (v2.0.0) should have fixed this issue. Please reopen, if the error still occurs.

**Closed by kaalleen** 2021-05-04 15:59 UTC
Labels: bug
