### ISSUE TITLE
ink stich wont save as a pes file 

### ISSUE THREAD

**Issue by harvey08999** [inkstitch/inkstitch#2085] opened 2023-02-21 19:40 UTC
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues

Include the error description and also (if possible) the svg file.

Ink/Stitch Version: v2.2.0 (windows)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\output.py", line 56, in effect
  File "lib\extensions\base.py", line 200, in elements_to_stitch_groups
  File "lib\elements\element.py", line 329, in embroider
  File "lib\elements\element.py", line 387, in validate
  File "lib\elements\fill_stitch.py", line 321, in validation_errors
  File "lib\elements\fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'

please help ASAP
![Short-haired-Dachshund-PhotoRoom png-PhotoRoom](https://user-images.githubusercontent.com/126018294/220443451-ddc3e095-9312-4d23-9dfe-46b47d1b6254.svg)

**Comment by kaalleen** [comment] 2023-02-21 20:07
You have a lot of small elements in your file which need to be removed (190). Here is a cleaned up version of your file. You may need to adapt some of the shapes though. Haven't carefully looked at it, I just ran the cleanup extension with a development version.

![2085_modified](https://user-images.githubusercontent.com/36401965/220447088-9c2d9ad6-06d7-4cc1-9aa5-ad2a4ddb169e.svg)

Out of curiosity, how did you create the file?

**Comment by harvey08999** [comment] 2023-02-21 20:08
thank you so much. i just used an online vectorising tool to convert it to jpg so i can convert it into a PES file

**Comment by kaalleen** [comment] 2023-02-25 12:48
Interesting.

I'll close the issue, since we have seen it any time (duplicate of #1742 )

**Closed by kaalleen** 2023-02-25 12:48 UTC
