### ISSUE TITLE
auto_fill: ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by dcm10000** [inkstitch/inkstitch#1037] opened 2021-02-15 03:11 UTC
path446: error: Error during autofill!  This means that there is a problem with Ink/Stitch.

If you'd like to help us make Ink/Stitch better, please paste this whole message into a new issue at: https://github.com/inkstitch/inkstitch/issues/new

Traceback (most recent call last):
  File "D:\a\inkstitch\inkstitch\lib\elements\auto_fill.py", line 212, in to_patches
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 55, in auto_fill
  File "D:\a\inkstitch\inkstitch\lib\debug.py", line 125, in decorated
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 149, in build_fill_stitch_graph
  File "D:\a\inkstitch\inkstitch\lib\stitches\auto_fill.py", line 173, in insert_node
ValueError: min() arg is an empty sequence

**Comment by kaalleen** [comment] 2021-02-15 17:01
This error is caused by very small fill shapes. If you clean your document from them with a tool which you find in Extensions > Ink/Stitch > Troubleshoot > Cleanup document ... you should be fine. We believe this problem should be fixed in the next release.

**Comment by kaalleen** [comment] 2021-03-06 13:11
This is a duplicate of #734. I will close this issue now. Please reopen if it is still needed.

**Closed by kaalleen** 2021-03-06 13:11 UTC
