### ISSUE TITLE
Supporting Python3

### ISSUE THREAD

**Issue by matthijskooijman** [inkstitch/inkstitch#698] opened 2020-05-12 11:08 UTC
In the documentation, I read that inkstitch requires python2, because Inkscape only supports python2. However, since Inkscape [0.92.5](https://inkscape.org/release/inkscape-0.92/?latest=1) and [1.0](https://inkscape.org/release/inkscape-1.0/), Python3 is supported.

In the [detailed release notes](https://wiki.inkscape.org/wiki/index.php/Release_notes/1.0#python3), they write:

> Extensions were updated to be compatible with Python 3. While we'll be migrating away from Python 2, extension writers should aim for support of Python 2.7 and Python 3.5+ for maximum compatibility.
> Windows packages now ship with Python 3 (currently Python 3.7). Python 2 is not bundled anymore, so make sure to update your extension to be compatible.

I guess this means that inkstitch should try to support py2 and py3 for a while (and probably provide binary releases for both) if you want to support both newer and older inkscape versions.

I haven't tried running inkstitch with newer inkscape and py3 yet, just came across these releases notes and wanted to share findings and maybe start discussion.

**Comment by wwderw** [comment] 2020-05-12 22:19
InkStitch has it's python dependencies bundled within itself.  

I've been running both the beta and RC versions of 1.0 (downloading the official release wasn't happening for me when it first came out, going to try again in a bit) with the extension without any issues.

**Comment by matthijskooijman** [comment] 2020-05-13 06:32
> InkStitch has it's python dependencies bundled within itself.

Ah, good point. So that means that on Inkscape 1.0, the *stub* py file is ran using python3, but the rest of inkstitch runs on the bundled python version (so python2). So the current arrangement is actually portable among older and newer versions.

However, it would still be good to upgrade to python3 (or maybe modify the code to allow python2 and python3), given that python2 is [officially EOL since 2020-01-01](https://www.python.org/doc/sunset-python-2/) and will not receive any updates, not even security updates.

I believe that up till now, the blocker for supporting Python3 was that Inkscapes inkex.py (which I think is *not* bundled with inkstitch, but imported from the installed Inkscape version, right?) did not support Python3. Now that has changed, inkstitch could be made to run on Python3 as well (or maybe that already happened and it already can run on Py3?).

**Comment by kaalleen** [comment] 2020-05-14 10:08
Oh yes, it was our plan to switch to Python 3 as soon as possible after Inkscape 1.0 was released. But our time resources are quiet limited and we will need a while to work on it. You seem to know what you are talking about. Are you willing to step in and help us with the transition?

**Comment by lexelby** [comment] 2020-05-14 11:43
Two quick notes:

1. The latest version does away with the stub, and instead Inkscape invokes the Ink/Stitch binary directly.

2.  We do in fact bundle inkex.py (and friends) directly with Ink/Stitch, so we're thankfully insulated from version changes.  That means Ink/Stitch works with Inkscape versions below and above 1.0 without changes, thankfully.  We still do want to switch to Python 3 and inkex.py 1.0+ though :)

**Comment by kaalleen** [comment] 2020-05-14 12:10
The latest version still has the stub.py. This is becoming an issue right now since Inkscape 1.0 is released and everyone is updating their Inkscape versions. Maybe it's time for a new Ink/Stitch release, so we can avoid for people to run into troubles caused by stub.py?

**Comment by kaalleen** [comment] 2020-05-14 12:11
> Thanks, but I'll have to decline (too many projects already...). Maybe I can convince @BrendaH to have a look at this, though :-)

That'd be great ;)

**Comment by lexelby** [comment] 2020-05-14 12:13
Oh!! I thought we had made a release.

I'll try to do it soon but I'm not sure when I'll get a chance.  To do it, you add a commit on the master branch, tag it with v##.##.## and push the tag.

**Comment by matthijskooijman** [comment] 2020-05-14 12:17
> The latest version still has the stub.py. This is becoming an issue right now since Inkscape 1.0 is released and everyone is updating their Inkscape versions. 

Why is this an issue then? The stub looks like it already supports py3? This also contradicts what @wwderw said before:

> I've been running both the beta and RC versions of 1.0 (downloading the official release wasn't happening for me when it first came out, going to try again in a bit) with the extension without any issues.

**Comment by wwderw** [comment] 2020-05-14 12:38
> This also contradicts what @wwderw said before:

I have to wonder, since I'm on KDE Neon (which is based on 18.04 and everyone is also moving to 20.04 which no longer has Python2 could play a part with that as well.

I don't know, I'm just speculating here.

I'll try to spin up a VM of 20.04 and see if I have any issues with it there.

**Comment by wwderw** [comment] 2020-05-14 13:29
Interesting, using Kubuntu 20.04 (wanted to keep it as close to Neon as I could) and the extension does not work with the same RC release that I have that works off of Neon.

**Comment by matthijskooijman** [comment] 2020-05-14 13:46
Could be that the lack of a `python` executable breaks it. Maybe changing the shebang of the stub to `python2` or `python3` would fix it? (though I would have expected that the shebang is ignored by inkscape and it just uses its own bundled python when `interpreter="python"`, but maybe that's not how it works.

**Comment by kaalleen** [comment] 2020-05-16 10:12
> I'll try to do it soon but I'm not sure when I'll get a chance. To do it, you add a commit on the master branch, tag it with v##.##.## and push the tag.

It's done. Through the break apart 2 branch I forgot how messy the menu was at this state :D
Anyway, the new release is out there :)

**Closed** 2021-04-04 10:12 UTC
