### ISSUE TITLE
Missing Params Options

### ISSUE THREAD

**Issue by AlyOops** [inkstitch/inkstitch#1579] opened 2022-02-16 04:30 UTC
Hello  there.

I am hoping one of you inkstitch gurus can help me with an issue I am having. 

I am missing some of my Embroidery Params options.  It only lists 3.  I need to bean a stitch and it doesn't give those options.  I seems a few sub options are missing. 

I use a mas OS Big Sur. I have downloaded the latest version of inkscape and inkstitch. I have even tried uninstalling everything and reinstalled. Same. 

I saw that some window users were having trouble with antivirus. I am wondering if this is something similar?

I greatly appreciate the help. Thank you!

**Comment by AlyOops** [comment] 2022-02-17 20:26
![Screen Shot 2022-02-17 at 3 24 11 PM](https://user-images.githubusercontent.com/99782395/154564942-581bb75f-9977-4450-b5cb-6666e788bedf.png)

**Comment by tyrosinase** [comment] 2022-02-17 20:35
Bean stitches only can be applied to lines, and you have a fill object. See how it's making a teeny grid of stitches in the black area? You want to remove the fill and give the object(s) an outline color (ctrl-shift-F, usually).

It'll need a little more fine-tuning since you'll have a double line going on. https://silverseams.com/2020/03/monogramming-without-a-font/ or https://silverseams.com/tutorials/digitizing-with-ink-stitch/ will talk you through converting fills to satins, which may be what you want to do for the yellow fills. Bean stitch is easier, since you only need one line instead of two rails (plus rungs).

**Comment by AlyOops** [comment] 2022-02-18 02:19
Thank you very much! I wasn't sure if it was supposed to be bean or satin. I will definitely follow those links.  Should the embroidery params list stitch options? It appears like they're missing when I watch the tutorials.  I'm still wondering if it didn't load properly. Thank you for your help!

**Comment by tyrosinase** [comment] 2022-02-18 02:24
It should only list the things it thinks are appropriate for the object type. If you've got an object with a fill color, it'll show you the fill params. If you've got an object with a stroke color, it'll show you the satin and running stitch options.

I forget what it does nowadays when you have an object with both, but I think the done thing is to have separate objects for those, rather than trying to do it all in one.

**Comment by kaalleen** [comment] 2022-04-10 15:00
We possibly will handle this a bit different with the new gui system.
I'll close the issue though, since this is expected behavior at the moment.

**Closed by kaalleen** 2022-04-10 15:00 UTC
