### ISSUE TITLE
New to ink/stitch and i get this error, help!

### ISSUE THREAD

**Issue by Anti-care** [inkstitch/inkstitch#2215] opened 2023-04-12 10:48 UTC
Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex\base.py", line 231, in run
  File "lib\extensions\print_pdf.py", line 312, in effect
  File "lib\extensions\base.py", line 200, in elements_to_stitch_groups
  File "lib\elements\element.py", line 329, in embroider
  File "lib\elements\element.py", line 387, in validate
  File "lib\elements\fill_stitch.py", line 321, in validation_errors
  File "lib\elements\fill_stitch.py", line 274, in shape
AttributeError: 'LineString' object has no attribute 'geoms'

**Comment by kaalleen** [comment] 2023-04-13 15:28
Remove small elements from your file while going through your objects and layers list.

The next Ink/Stitch release will be more forgiving, but it would be recommended to work with a clean document. Ink/Stitch has an extension for this "Troubleshoot > Cleanup document". But this will fail on your file with the current version too.

**Comment by kaalleen** [comment] 2023-05-15 21:30
Duplicate of https://github.com/inkstitch/inkstitch/issues/1742

**Closed by kaalleen** 2023-05-15 21:30 UTC
